NDLANO/frontend-packages

- packages/designmanual/.storybook/preview-head.html
- packages/designmanual/stories/article/FigureWithLicense.jsx
- packages/designmanual/stories/article/LicenseExample.jsx
- packages/designmanual/stories/basic-styles.jsx
- packages/designmanual/stories/helpers.jsx
- packages/designmanual/stories/simple-components.jsx
- packages/ndla-ui/src/Figure/Figure.js
- packages/ndla-ui/src/Figure/component.figure.scss
- packages/ndla-ui/src/LicenseByline/LicenseByline.jsx
- packages/ndla-ui/src/LicenseByline/component.license-byline.scss
- packages/ndla-ui/src/global/elements/_elements.headings.scss
- packages/ndla-ui/src/global/utilities/utilities.grids.scss
- packages/ndla-ui/src/global/utilities/utilities.helpers.scss
- packages/ndla-ui/src/global/utilities/utilities.shame.scss
- packages/ndla-ui/src/main.scss
- Example in license box for thumbnail video
- Figure caption: Styling adjustments. Caption text moved to top
- Removed deprecated classes .article_figure--float-left and .article_figure--float-right NB! Breaking
- Fix floating bug on mobile
- New small version of figure. Example in design manual
- Example of centering text in design manual (used for math)
- Styling of h3.
> Misc adjustments and fixes

- package.json
- scripts/_getPackages.js
- scripts/build.js
- scripts/watch.js
Fixes so that you don't need to run  `yarn bootstrap` before `yarn start` when you have edited som files in other packages than designmanual.
> Build packages before starting storybook

- packages/ndla-ui/src/Dialog/component.dialog.scss
- packages/ndla-ui/src/Tooltip/Tooltip.jsx
- packages/ndla-ui/src/Tooltip/component.tooltip.scss
- packages/ndla-ui/src/TopicIntroductionList/TopicIntroductionList.jsx
- packages/ndla-ui/src/TopicIntroductionList/TopicIntroductionShortcuts.jsx
- packages/ndla-ui/src/TopicIntroductionList/TopicShortcutItem.jsx
- packages/ndla-ui/src/TopicIntroductionList/component.topic-shortcuts.scss
- packages/ndla-ui/src/global/utilities/utilities.shame.scss
- packages/ndla-util/src/noScroll.js
• Semi hack to prevent scrolling on iOS with noScroll function, using position: absolute to #root.
• Minor Tooltip adjustments for better position handling
• Prevent native input on text-fields iOS
• Improved Icons and tooltip for Topiclist (css / internal component fixes)
> phone input and scroll fix + minor dialog css and tooltip updates

- packages/ndla-ui/src/Frontpage/FrontpageHeader.jsx
- packages/ndla-ui/src/Frontpage/FrontpageSearchSection.jsx
Temporary hide search on frontpage cause searches are not ready for launch as intended.
> Removed search from frontpage as default

- packages/designmanual/stories/molecules/mastheads.jsx
- packages/designmanual/stories/pages/SearchPageExample.jsx
- packages/designmanual/stories/search.js
- packages/ndla-ui/src/Filter/FilterList.jsx
- packages/ndla-ui/src/Filter/component.filter.scss
- packages/ndla-ui/src/Masthead/Masthead.jsx
- packages/ndla-ui/src/Masthead/component.masthead.scss
- packages/ndla-ui/src/Search/SearchFilter.jsx
- packages/ndla-ui/src/Search/SearchPage.jsx
- packages/ndla-ui/src/Search/SearchPopoverFilter.jsx
- packages/ndla-ui/src/Search/component.search-page.scss
- packages/ndla-ui/src/Search/component.search-popover-filter.scss
- packages/ndla-ui/src/Search/component.search-result-author.scss
- packages/ndla-ui/src/Search/component.search-result.scss
- packages/ndla-ui/src/global/components/component.tabs.scss
Fixes includes:
• Added Menu Button to header on Search page (btw, it should ALWAYS be there unless on frontpage)
• Keep Filter for Tabs on Searchpage on desktop, even if not results matched.
• On searchpage: Only show checked filter subjects under Subjects. 
• Allow to remove all subject filters in <SearchPopoverFilter />
• Some css changes
Label text corrections will come..
> Search fix before launch

- packages/ndla-article-scripts/src/tableScripts.js
- packages/ndla-ui/src/global/components/component.bodybox.scss
Laget for å justere for tabeller som er inni en c-bodybox. Alle tabeller har default 133% bredde ved desktop + skjermstørrelser, noe som er problematisk når de er i en container med border eller overflow: hidden.
https://trello.com/c/pc0Wkh2J/691-tabeller-i-rammer
> Table in bodybox fix

- packages/ndla-ui/src/Article/Article.jsx
- packages/ndla-ui/src/Article/component.article.scss
Minor fix, adding pseudo element making first-line of articles short to adjust competence button on desktop+ screens
> Fix for articles title first-line width when compentencegoals

- packages/ndla-article-scripts/src/tableScripts.js
• Denne og tabell i ramme fiksen burde vært løst serverside på sikt. Ref:
// detect if parent has c-bodybox class and add container adjustment class
// a hacky fix for table cropped when inside a c-bodybox.
if (el.parentNode.classList.contains('c-bodybox')) {
el.parentNode.classList.add('c-bodybox--contains-table');
}
if (el.parentNode.classList.contains('wrapper')) {
el.classList.remove('c-table__wrapper');
}
> B-feil. Hotfix table in expandable box

- packages/ndla-editor/src/SlateBlockMenu.js
SlateblockPicker krasjer når den åpnes. Usikker på hva som har skjedd / hvilken endring som trigget dette. 
2 feil fikset:
• "React.Children.only expected to receive a single React element child" (Fiks med </>)
• "FocusTrapReact Cannot read property 'ownerDocument' of null" (Trigget via Tabbable.js som FocusTrap bruker). Fikset ved å kun rendre Focustrap kun når den er aktiv.
> Bugfix: Slateblockpicker

- packages/ndla-core/scss/global/settings/settings.global.scss
- packages/ndla-core/src/fonts.js
Bugfix for rending av noen font-tegn i serif som feks ǐ på PC + Chrome. 
Løst ved å bytte 2. valg av serif font til Times. (Chrome rendrer disse feil i Georgia på PC)
Trello: https://trello.com/c/MnvOPzHf/814-feil-visning-av-pinyin-for-kinesisk-i-google-chrome-p%C3%A5-pc
> Fix for serif fallback fonts

- packages/ndla-ui/src/Figure/component.figure.scss
Fix: Prevent floating figures from floating (spolte fag).
Trello: https://trello.com/c/vwyOHVdf/810-ramme-over-bilde
> Fix: Figures with class u-float-full

- packages/designmanual/stories/produksjonssystem/HowtoExamples.jsx
- packages/ndla-howto/src/StaticInfoComponents/index.js
Tekst kommer senere, kan merges as is. Skal brukes i ed som info til status hjelpeikon. (branch: new-article-header)
> Prepared texts for how-to statuses

- packages/core/scss/global/elements/_elements.lists.scss
Remove margins when <p> (only-child) is in <li> - tag
> <p> in <li> = no margin

- packages/core/scss/global/utilities/mixin_icons.scss
- packages/designmanual/stories/molecules/mastheads.jsx
- packages/designmanual/stories/pages/index.jsx
- packages/ndla-ui/src/Masthead/Masthead.jsx
- packages/ndla-ui/src/Masthead/MastheadLanguageSelector.jsx
- packages/ndla-ui/src/Masthead/component.masthead.scss
- packages/ndla-ui/src/Masthead/index.js
- packages/ndla-ui/src/index-javascript.js
- packages/ndla-ui/src/locale/messages-en.js
- packages/ndla-ui/src/locale/messages-nb.js
- packages/ndla-ui/src/locale/messages-nn.js
• Language selector in header (hides on scroll)
• Url should have params so we can pass autoOpen={true} to <MastheadLanguageSelector /> on changing language.
• Keep language selector in footer
> Language selector in header

- packages/ndla-ui/src/locale/messages-en.js
Dersom vi skal kunne vise artikler på engelsk med url ndla.no/en/article/id må denne teksten være på plass.
> Add missing text

- packages/designmanual/stories/article/FigureImage.jsx
- packages/ndla-article-scripts/src/figureScripts.js
- packages/ndla-ui/src/Figure/Figure.js
- packages/ndla-ui/src/Image/Image.jsx
- packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap
Bildeoppløsning oppdaterer seg ikke ved ekspandering av bilde i artikkeltekst. 
https://trello.com/c/w6mXO2i1/244-komprimering-av-bilder
```
Fra Albertine: Sjekk f.eks det sidestilte bilde i denne artikkelen: https://stier.ndla.no/learningpaths/913/step/7242
Fra Johannes: Godt observert - her bytter de ikke ut bildekvaliteten når man klikker på forstørrknappen. Det er en frontendfeil som Cecilie følger mot design-Keyteq tenker jeg. Denne kvaliteten har bildet egentlig Cecilie: https://api.ndla.no/image-api/raw/YJELF8WX.jpg?width=2720
Kan vi fikse dette, @sivmundal og @ivarborthen2?
```
Vi Wrapper img i en picture tag med source element, som ser ut til å fikse problemet, men vanskelig å verifisere.
> Komprimering av bilder

- packages/ndla-ui/src/Masthead/MastheadSearchModal.tsx
Make the closeModal function available to components that uses the MastheadSearchModal
> Forward closeModal function in SearchModal to children

- packages/ndla-ui/src/Article/Article.jsx
ArticleIntroduction brukes i designmanualen så derfor måtte eg ha defaultimplementasjon av renderMarkdown der som gjør ingenting.
> Add renderMarkdown prop to Article

- packages/ndla-article-scripts/src/footnoteScripts.js
Følgende commit endret til å scrolle parent av en eller annen grunn: https://github.com/NDLANO/frontend-packages/commit/3b10ef51d154b7b427bc495a9b17a511d02a05c8
Usikker på hvorfor og kan ikke se noen god grunn. Den hindrer uansett scroll-funksjonalitet i iFrame(og designmanual)
> Fix footnote-scrolling in iFrame

- packages/ndla-video-search/src/VideoSearchResultYouTube.jsx
Fixes https://github.com/NDLANO/Issues/issues/2191
`Shift` metoden som ble kjørt på videooobjectet gjorde selve videoobjectet undefined til neste rerender.
> running shift on the same object on different renders gives undefined

- packages/ndla-ui/src/Image/ImageLink.js
- packages/ndla-ui/src/Image/component.image.scss
- packages/ndla-ui/src/main.scss
Dette ser hackete ut og det er det vel også. Svg-bilder som vises inne i ei lenke får en strek i gjennom seg på grunn av box-shadow som er satt på alle lenker. Ingen andre bildetyper får dette.
Løsninga her er å legge til contentType, og sjekke om denne er lik 'image/svg+xml'. Dersom den er lik settes en class som skjuler box-shadow for lenka.
For at dette skal fungere kreves det at imagePlugin i article-converter oppdateres til å sende inn contentType.
> Skjule box-shadow for bildelenker.

- packages/ndla-modal/src/Modal.js
Har omstrukturert redigeringssiden til ndla film til å likne mer på fagforsideredigeringa, med accordions, header og lagreknapp. Themes-komponentene er de samme som før, og når modal til redigering av navn på dem åpnet, gjorde default at lagreknappen til editoren ble aktivert. La til en preventDefault for å hindre dette, og sjekket at ikke det knakk andre komponenter som bruker modal.
> Utvide redigeringssiden til ndla film

- packages/ndla-ui/src/locale/messages-en.js
- packages/ndla-ui/src/locale/messages-nb.js
- packages/ndla-ui/src/locale/messages-nn.js
beskrivning er ikkje et gangbart ord på nynorsk så i samråd med språkavdelinga i NDLA endres dette til Vis mer og Vis mindre. Brukes for ekspandering av emnetekster.
> Better naming

- packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx
Dersom bruker åpner søket på forsiden og lukker det før det er gått 1 sekund så legges scroll-listener på etterpå som gjør at man ikke kan scrolle. Dette fikser det
> Don't add scroll-listener to search on front-page if modal is closed

- packages/designmanual/stories/simple-components.jsx
- packages/ndla-ui/src/Frontpage/FrontpageHeader.tsx
https://trello.com/c/Yyml13vf/665-dagens-logo-er-p%C3%A5-norsk-b%C3%A5de-i-engelsk-og-p%C3%A5-norsk-burde-v%C3%A6rt-p%C3%A5-engelsk-n%C3%A5r-spr%C3%A5kvelgeren-er-valgt-til-engelsk
> Support locale in logo on frontpage-header

- packages/ndla-ui/src/Article/ArticleByline.tsx
- packages/ndla-ui/src/Article/ArticleSideBar.tsx
- packages/ndla-ui/src/Codeblock/Codeblock.tsx
NDLANO/Issues#2276
For at figureScripts skal kunne plukke opp tekst som skal kopieres må button ha en property med teksten. Mangla dette i forrige PR.
> Add data-copy-string property to trigger script

- packages/hooks/src/useIntersect.ts
Fikser rapporterte feil frå safari-brukere(flest eldre safari versjonar, men også enkelte nyare)
> Check if "IntersectionObserver" is supported in browser

- packages/hooks/src/index.ts
- packages/hooks/src/useComponentSize.ts
- packages/hooks/src/useIsomorphicLayoutEffect.ts
- packages/ndla-ui/src/Breadcrumb/Breadcrumb.tsx
- packages/ndla-ui/src/Breadcrumb/BreadcrumbBlock.jsx
- packages/ndla-ui/src/Breadcrumb/BreadcrumbBlock.tsx
- packages/ndla-ui/src/Breadcrumb/BreadcrumbItem.tsx
Ingen funksjonelle endringer å teste, men kan fint teste at sidene (Spesielt de med brødsmulesti i headeren i guess) fortsatt fungerer som forventet. (Og at det ikke lager warning på useLayoutEffect)
Grunnen til å lage denne `useIsomorphicLayoutEffect` er at `useLayoutEffect` lager en støyete warning på server og på denne måten så bruker vi bare `useEffect` på server istedet. I følge han i [medium blog'en](https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a) så er det en workaround brukt av smarte folk også :smile: ([react-redux](https://github.com/reduxjs/react-redux/blob/d16262582b2eeb62c05313fca3eb59dc0b395955/src/components/connectAdvanced.js#L40))
_Eeeegentlig_ så merket jeg ikke store forskjellene dersom vi bruke `useEffect` på klient også, men ser at vi gjør …
> Avoid using useLayoutEffect hook on server

- packages/ndla-ui/src/Frontpage/FrontpageProgramMenu.tsx
- packages/ndla-ui/src/Navigation/NavigationBox.tsx
Dette skal ikke ha innvirkning på front-end annet at det blir slik som det er tenkt. Horisontal retning under utdaninng og på emner under fag. Vertikal retning på forsiden i listen over utdanninger.
> Fix wrong direction prop in navigation-box

- packages/designmanual/stories/pages/SearchPageExample.jsx
- packages/ndla-ui/src/Search/SearchResult.jsx
Legger til støtte for at ressurser som finnes i fleire fag kan vise breadcrumb ved mouseover på fagnavnet. Krever at searchHelper i ndla-frontend oppdateres til å sette breadcrumbs på subjects.
Kan verifiseres på https://frontend-packages-pr-712.ndla.sh/?path=/story/s%C3%B8k--s%C3%B8keside søkeresultat nummer 3.
> Separate breadcrumb as const and use twice with different css

- packages/ndla-ui/src/Footer/Footer.tsx
Legger på z-index for å unngå dette:
> Adding z-index on footer.

- packages/ndla-forms/src/DropdownMenu.js
Viser kun paginering hvis antall elementer er flere enn antall elementer per side.
- Testes: https://frontend-packages-pr-735.ndla.sh/?path=/story/produksjonssystem--dropdown-with-multiselect
- Velg *med* paginering
- Antall elementer per side defaulter til 10, så sjekk søk som gir færre enn 10 resultater
Har ikke lagt til funksjonalitet for å bytte side i designmanualen.
> Småfiksing på paginering i nedtrekkssøk

- packages/ndla-code/src/Codeblock/Codeblock.tsx
For NDLANO/Issues#2387
Lagt til `data-copied-title` til knappen for at lagre-utseende skal fungere med article-converter. Gir ikke noe effekt på komponenten i designmanualen.
> Kopierknapp for kodeblokk i artikler

- packages/designmanual/stories/article/AudioExample.jsx
- packages/designmanual/stories/article/FigureCaptionExample.js
- packages/designmanual/stories/article/FigureImage.jsx
- packages/designmanual/stories/article/FigureWithLicense.jsx
- packages/designmanual/stories/article/RelatedArticleListExample.jsx
- packages/designmanual/stories/collated-components.jsx
- packages/designmanual/stories/pages/SearchResultTypeExample.jsx
- packages/designmanual/stories/simple-components.jsx
- packages/ndla-ui/src/locale/messages-en.js
- packages/ndla-ui/src/locale/messages-nb.js
- packages/ndla-ui/src/locale/messages-nn.js
NDLANO/Issues#2389
- Lagt til messages fra article-converter
- Byttet ut hardkoda meldinger med å hente de fra messages i @ndla/ui i disse komponentene:
- [AudioExample](https://frontend-packages-pr-738.ndla.sh/?path=/story/enkle-komponenter--lydavspiller)
- [FigureImage](https://frontend-packages-pr-738.ndla.sh/?path=/story/enkle-komponenter--bilde)
- [FigureWithLicense](https://frontend-packages-pr-738.ndla.sh/?path=/story/enkle-komponenter--embedded-innhold)
- [RelatedArticleListExample](https://frontend-packages-pr-738.ndla.sh/?path=/story/sammensatte-moduler--relatert-innhold)
> 2389 flytte tekster fra article converter til UI

- packages/designmanual/stories/organisms/NotionExample.jsx
- packages/designmanual/stories/pages/ArticleAssessmentResource.jsx
- packages/designmanual/stories/pages/ArticleExercise.jsx
- packages/designmanual/stories/pages/ArticleExternalLearningResource.jsx
- packages/designmanual/stories/pages/ArticleLearningPaths.jsx
- packages/designmanual/stories/pages/ArticleLearningmaterial.jsx
- packages/designmanual/stories/pages/ArticleSourceMaterial.jsx
- packages/ndla-notion/package.json
- packages/ndla-notion/src/Notion.jsx
- packages/ndla-notion/src/NotionDialog.js
Grunnen til at Notion oppfører seg rart når den er brukt i article-converter er fordi den ikke legger seg i roten av editorial-frontend, men heller i roten av HTMLen som blir sendt fra article-converter. Slik Notion posisjoneres nå går den ut fra at den finnes i roten av nettsiden.
Forslaget til løsningen er å legge til en prop `customCSS` som gjør at man kan sende med custom css for NotionDialog (og andre elementer i NotionDialog). For noen av stylene som eksisterer fra før kan `!important` være nødvendig å bruke.
PR for article-converter som skal ta i bruk den oppdaterte komponenten:
https://github.com/NDLANO/article-converter/pull/217
> Custom styling prop for Notion

- packages/designmanual/stories/basic-styles.jsx
blokksitat (slike med innrykk) ikkje skal ha sitattegn føre og etter sitatet, men eksempelet i designmanualen vår har fått slike
> fix: blockquote

- packages/designmanual/stories/pages/LearningPathExample.jsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenu.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenuModalWrapper.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathSticky.tsx
- packages/ndla-ui/src/LearningPaths/index.ts
- packages/ndla-ui/src/index.ts
Fixes NDLANO/Issues#2393
- Lagt til safe-area padding nederst på navbaren på læringsstier på mobil, for å legge til nødvendig margin rundt iPhoner med notch (i stedet for hjemknapp).
- Flyttet "Vis læringsstier"-knappen på mobil til å ligge inni LearningPathSticky-komponenten, for at den skal følge samme oppførsel som resten av navbaren.
Med navbars i web på iPhone så er det alltid sånn at man må trykke på den en gang, sånn at navbaren til safari vises, før man får til å trykke på en knapp i den. Så sånn er det fortsatt. Men nå ligger det hvertfall ikke oppå notchen.
**Testing**
- [Designmanual](https://frontend-packages-pr-747.ndla.sh/?path=/story/sidevisninger--l%C3%A6ringssti)(skru på mobilvisning): Ser helt lik ut som før, og på iphone hvertfall forsvinner ikke navbarene til safari …
> 2393 større marger i læringssti footer

- packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx
Gir mulighet til å legge til et element mellom tittel og tekst i SearchItem. Er tenkt til å brukes for å legge til en 'Sett inn' knapp for LTI.
Har ikke fått testet hvordan det ser ut i /lti på grunn av yarn link problemer, men det fungerer fint i /search.
> Add children to search item

- packages/designmanual/stories/produksjonssystem/FileListEditorExample.jsx
- packages/designmanual/stories/produksjonssystem/index.js
- packages/ndla-editor/src/FileListEditor.js
- packages/ndla-editor/src/FileNameInput.js
- packages/ndla-forms/package.json
- packages/ndla-forms/src/CheckboxItem.js
Tilhører NDLANO/Issues#2410
Ting som er oppdatert:
1. CheckboxItem bruker nå ikke innsendt ID som referanse mellom label og CheckboxInput. Det genereres heller en unik id med uuid(). Dette forhindrer at to CheckboxItem bruker samme ID som kan føre til at når man trykker på en checkbox er det en annen  checkbox med samme ID som blir markert.
2. FileListEditor har nå støtte for checkboxes for markering av pdf. Det skal kun dukke opp checkbox på PDF når checkboxes er aktivert.
3. FileListEditorExample er oppdatert med et eksempel som viser bruk med checkboxes.
How to test:
1. https://frontend-packages-pr-751.ndla.sh/?path=/story/produksjonssystem--filelisteditor
2. Test at gammel funksjonalitet fungerer.
3. Test at man kan markere checkboxes.
4. Prøv å framprovosere feil i sortering, krasj …
> 2410 inline visning av pdf i artikkel

- packages/core/scss/global/objects/objects.lists.scss
- packages/designmanual/stories/basic-styles.jsx
NDLANO/Issues#2233
Lager en class som resetter counter for ol-lister. 
Både ed og article-converter må oppdateres til å støtte dette slik at ved kode `<ol start="2">` så må klassen .ol-reset-2 settes på ol-taggen. Det vil resette telleren for liste-elementer til å begynne på start-1 slik at første element viser 2.
Genererer 1-50 for å ha en del å gå på sjølv om det sikkert er sjelden at lister blir så lange. 
Om det finnes bedre måter å gjøre dette på, kom gjerne med forslag. Fant ingen andre gode måter å sette inn en verdi i counter-reset regelen.
> Adding set of reset-classes to reset counter for ordered list

- packages/designmanual/stories/pages/LearningPathExample.jsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenu.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenuModalWrapper.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMobileHeader.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMobileStepInfo.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathSticky.tsx
- packages/ndla-ui/src/LearningPaths/index.ts
- packages/ndla-ui/src/index.ts
For NDLANO/ndla-frontend#618
- Endret slik at høyden på footeren følger safe-area også, sånn at ikke pilene skal legge seg rart
- De endringene jeg hadde gjort for å få knappen som aktiverer læringsstimodalen til å plassere seg riktig funket ikke, så jeg måtte omstrukturere litt for å få den til å bli en del av footeren på riktig måte.
Testes i designmanualen: https://frontend-packages-pr-749.ndla.sh/?path=/story/sidevisninger--l%C3%A6ringssti
Igjen må det inn i now-deployment på ndla-frontend for å være sikker på at pilene og knappen legger seg riktig, men jeg lagde lokale wrappers med samme css som her som jeg testet direkte i pr-en i ndla-frontend, og der kan man se at footeren oppfører seg riktig (https://ndla-frontend-pr-618.ndla.sh/nn/subject:19/topic:1:186579/topic:1:187897/resource …
> nye oppdateringer til læringssti footer

- packages/ndla-ui/src/Search/IsPathToHighlight.ts
- packages/ndla-ui/src/Search/SearchResultSleeve.tsx
Relatert til NDLANO/Issues#2450
Denne PRen fikser to ting:
1. Når du har gjort et søk på ndla.no, men enda ikke markert et resultat med piltaster så vil enter-klikk ta deg til søkesiden. Dette tilsvarer trykk på "se alle treff på søk" som er øverste resultat.
2. Oppdaget en bug. Ved søk på feks "tr" på test.ndla.no så ble ikke alle resultater fremhevet ved trykk nedover med piltaster. Dette gjaldt hvertfall resultater under kategorien "Fag". Skal fungere nå. (Kan ikke bruke path rett i regex når path inneholder ? og /. Dette er tegn som må escapes som "\\?" eller "\\/" for at det skal fungere)
Oppsett:
1. repo: frontend-packages på branch `2450-search-onpress-enter-goto-search`
2. `cd /packages/ndla-ui/`
3. `yarn link`
4. repo: ndla-frontend på branch `master`
5. `yarn link "@ndla/ui"`' …
> Enter click on FrontPageSearch routes to search page.

- packages/ndla-ui/src/LearningPaths/LearningPathSticky.tsx
For NDLANO/ndla-frontend#618
Bredden på størrelsen ble presset ned fordi "vis læringssti"-knappen ble plassert i stickyen og komprimerte plassen. La til `min-width` for å sikre at pilene har den samme kvadratiske wrapperen på alle flater.
På mobil: https://frontend-packages-pr-764.ndla.sh/?path=/story/sidevisninger--l%C3%A6ringssti
> Øke størrelsen på navigeringspilene i læringssti-sticky på mobil

- packages/ndla-ui/src/FactBox/component.factbox.scss
Gjør at knappene til faktaboks blir plassert inne i boksen, slik som det gjøres for de andre boksene. Se: https://editorial-frontend-pr-936.ndla.sh/subject-matter/learning-resource/59228/edit/nb
Har ikke fått test pga yarn link problemer, men er relativt sikker på at det skal fungere
> Add position relative to factbox content

- packages/core/scss/global/tools/tools.functions.scss
Får en error på dette når jeg migrerer til dart-sass. 
>   &[lang='zh'],
^
Top-level selectors may not contain the parent selector "&".
Jeg forstår ikke helt syntaksen her, men prøvde å bare fjerne det den klagde på som uansett så ut til å være overflødig. Har klikket meg litt gjennom kinesisk fagene og alt ser fortsatt likt ut så vidt jeg kan se. Er det noen her som forstår denne koden eller vet hvorfor det er dobbelt opp?
> Fix dart-sass error

- packages/designmanual/stories/pages/FrontpageExample.jsx
- packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx
- packages/ndla-ui/src/Search/SearchResultSleeve.tsx
Relatert til NDLANO/Issues#2499
Utvider FrontPageSearch til å støtte forslag til annet søkeord. Dette er en string `suggestion` som er ordet som skal foreslås og en string `suggestionUrl` som er søket som skal redirectes til.
Hvordan teste:
1. http://frontend-packages-pr-774.ndla.sh/?path=/story/fag-og-emnesider--1-forside
2. Skriv inn et søk på minst tre tegn. Det skal dukke opp resultater og et statisk forslag til annet søkeord.
3. Sjekk at klikk med piltaster fungerer med det nye feltet med foreslått søkeord.
4. Sjekk at det nye feltet har en lenke. (Det fungerer kun å trykke på disse lenkene med ctrl+venstre museknapp i eksempelet).
> 2499 frontpage search suggestion

- packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx
https://trello.com/c/f5xexBKQ/1010-visuelt-element-p%C3%A5-ndla-film-er-breiare-enn-andre-innholdstypar-f%C3%B8rer-til-feil-p%C3%A5-s%C3%B8keside
> Fix word-break in safari search-result

- packages/designmanual/stories/simple-components.jsx
- packages/ndla-ui/src/CreatedBy/CreatedBy.tsx
For å unngå feilmeldinger når innhold åpnes i iframe uten støtte for det.
> Open lti-content in new window

- packages/ndla-ui/src/Search/SearchResult.jsx
- packages/tooltip/src/Tooltip.jsx
Fixes some prop-type warning introduces in https://github.com/NDLANO/ndla-frontend/pull/670. 
Usually the prop sent to SearchResult is of type `Resource`, in this PR the prop is of type `Topic`, hence the warnings.
> fixes prop type warnings in SearchResult and Tooltip

- packages/polyfill/package.json
- packages/polyfill/src/index.js
- yarn.lock
Litt vanskelig å teste, men når vi drar inn core-js 3.x transitivt (feks ved apollo-cli) så tryner det i ndla-frontend
Så denne er kjekk for nye versjoner av core-js.
> Update core-js version and imports in polyfill package

- packages/designmanual/stories/article/RelatedArticleListExample.jsx
- packages/ndla-ui/src/RelatedArticleList/RelatedArticleList.jsx
For NDLANO/Issues#2558
Lagt til en prop `inOembed` som setter `target=_blank` hvis lista over relaterte artikler blir vist i en oembed som f.eks. i en læringssti.
> 2558 Relatert innhold i læringstier linker til ny fane

- packages/ndla-licenses/src/LicenseByline/LicenseIconList.tsx
- packages/ndla-ui/src/AudioPlayer/Controls.tsx
Fixes NDLANO/Issues#2570
Setter `type="button"` på buttons for å overstyre default `type="submit"` for å forhindre at formik lagrer artikkel når man trykker på knappene.
> 2570 fix audioplayer button types

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
For NDLANO/article-converter#235
Lagt til noen oversettelsesfraser for kopiering av apa referansefraser. Greit å vente med denne til strukturen på kopieringsstrengen er godkjent.
> 2571 Bruke apa for kopiering av referanse

- packages/designmanual/stories/collated-components.jsx
- packages/designmanual/stories/molecules/resources.jsx
- packages/designmanual/stories/organisms/CarouselExample.jsx
- packages/ndla-ui/src/ContentTypeBadge/component.content-type-badge.scss
- packages/ndla-ui/src/ResourceGroup/ResourceGroup.jsx
- packages/ndla-ui/src/ResourceGroup/ResourceList.jsx
- packages/ndla-ui/src/ResourceGroup/component.resource-group.scss
- packages/ndla-ui/src/ResourceGroup/component.topic-resource.scss
- packages/ndla-ui/src/ResourcesWrapper/component.resources.scss
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/shapes.js
- packages/ndla-ui/src/types.ts
Har endra ResourceGroup litt slik at den skal kunne vise ei liste med ressurser uavhengig av ressurstype. Eg har fått til at ikonet har korrekt farge, og at navnet på gruppa vises som ekstrainfo, men skulle gjerne hatt det penere. Men der skulle eg gjerne hatt hjelp av en designer. Har du mulighet til å justere på utseendet, @beery ?
Sjekk sida http://localhost:6006/?path=/story/sammensatte-moduler--ugrupperte-l%C3%A6ringsressurser for slik det ser ut i dag.
Sletter også unødvendige eksempelsider.
> ResourceGroup supports one list of resources.

- packages/ndla-i18n/src/i18n.ts
- packages/ndla-i18n/src/index.ts
Gjer eit forsøk til på å dele instans mellom `@ndla/i18n` og listing-frontend. Denne gongen ved å initialisere i18n med eit kall frå frontend.
Sender inn språk og oversettingsfiler i frontend og sender i18n instansen deretter i ein provider.
> Initialiserer i18n med kall frå frontend

- packages/ndla-forms/src/DropdownMenu.js
Fixes https://github.com/NDLANO/Issues/issues/2639
Fungerte å sette z-index til 3, men valgte å sette verdien til 99. Dette er fordi jeg ikke forestiller meg scenarioer hvor man ikke ønsker at dropdownmenyen er fremst. 
Screenshot av fiks i listing:
> Fix overlapping filters in dropdownmenu for listing

- packages/ndla-ui/src/i18n/i18n.ts
- packages/ndla-ui/src/i18n/index.ts
- packages/ndla-ui/src/index.ts
Sidan komponentar i frontend packages ikkje klarar å dele i18n instans med listing-frontend går eg for løysinga med å oppdatere språk med refresh av sida. Alle i18n instansar vil då sjekke URLen etter språkkode og få riktig språk deretter.
Initialisering av i18next skjer i @ndla/ui. Denne blir delt av ui komponentar. I tillegg vil kvar frontend legge til ekstra oversetting i sin eigendefinerte i18n.ts fil.
> initialiserer i18n i ndla/ui

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/model/SubjectCategories.ts
- packages/ndla-ui/src/model/index.ts
NDLANO/Issues#2671
Første steg i å bruke taksonomi for å hente fag er å kunne kategorisere dei. Denne PR legger til kategoriene som brukes på ndla.no i dag. Disse skal brukes i ed for å kategorisere fag, og i ndla.no for å vise gruppert.
> Adding constants for subject categories.

- packages/designmanual/dummydata/mockTopics.js
- packages/ndla-ui/src/Search/ContentTypeResult.tsx
- packages/ndla-ui/src/Search/ContentTypeResultStyles.tsx
- packages/ndla-ui/src/TopicMenu/SubtopicLinkList.jsx
- packages/ndla-ui/src/TopicMenu/TopicMenu.jsx
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/types.ts
Tilknyttet https://github.com/NDLANO/ndla-frontend/pull/746
Ressurser i topic-meny kan nå vises ugruppert. Se bilde eller eksempel i designmanualen:
http://localhost:6006/?path=/story/s%C3%B8k--s%C3%B8kefelt
> Show ungrouped resources in topic menu

- packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
Fixes https://github.com/NDLANO/Issues/issues/2684
Kan testes lokalt via linking ved å navigere seg til fagstoff fra forsiden på ndla.no.
> Byttet ut contentUri med path i ResourceItem for å fikse fagstofflenker

- packages/ndla-editor/src/footer/FooterStatus.tsx
- packages/ndla-editor/src/versionLogs/VersionHistory.tsx
- packages/ndla-ui/src/i18n/__tests__/formatMessage-test.ts
- packages/ndla-ui/src/i18n/formatMessage.ts
- packages/ndla-ui/src/i18n/index.ts
Fixes https://github.com/NDLANO/Issues/issues/2686
Flyttet også `formatMessage` fra å være en default export til å være en named export, som fikser et problem i article-converter.
> Fixed ed and frontend-packages typescript mismatch.

- packages/ndla-ui/src/index.ts
Etter å ha flyttet formatMessage over fra i18n-pakken til ndla-ui så blir den ikke eksportert.
> Add export of formatMessage to ndla-ui

- packages/ndla-ui/src/TopicMenu/SubtopicLinkList.jsx
Legger til sortering av ugrupperte ressurser basert på rank.
Hvordan teste:
1. `ndla link ndla-frontend -l ndla-ui`
2. Mulig `yarn install --force` i ndla-frontend
3. Start ndla-frontend
4. Åpne `http://localhost:3000/nn/subject:1:a3c1b65a-c41f-4879-b650-32a13fe1801b/topic:2:1:187398/topic:4:1:165209/`
5. Sammenlikn læringsressursene på siden med de som dukker opp ved trykk på "innhold" øverst til venstre. Disse listene skal nå være identisk sortert.
> Sort ungrouped resources in masthead topicmenu

- packages/ndla-image-search/src/ImageSearch.js
- packages/ndla-image-search/src/ImageSearchResult.js
- packages/ndla-image-search/src/PreviewImage.js
Tilknyttet https://github.com/NDLANO/editorial-frontend/pull/1160
Legger til støtte for å vise fram en checkbox i bildesøk. Resten av implementasjonen for å sette metabilde gjøres i ed.
Hvordan teste:
- `git checkout 2725-prompt-metaimage-selection` dette repoet og ed.
- `ndla link editorial-frontend -l ndla-image-search`
- Åpne artikkel
- Legg inn bilde i editoren. Det skal være mulig å huke av for at det skal settes som metabilde.
- Åpne forklaring og emne
- Legg inn bilde som visuelt element. Det skal være mulig å gjøre det samme her også.
> Add param to ImageSearch to display checkbox for setting metaimage

- package.json
- packages/ndla-ui/src/Figure/Figure.js
- packages/util/package.json
- packages/util/src/index.ts
- packages/util/src/markdownHelpers.ts
- yarn.lock
https://github.com/NDLANO/Issues/issues/2613
Konsekvensen av dette er at alle FigureCaptions vil være i en `<p/>`. Alternativet er å flytte det "opp", slik at man istedenfor parser i ed og article-converter.
> Add utility functionality for parsing markdown to html. Add markdown parsing to FigureCaption by default.

- packages/ndla-ui/src/Figure/component.figure.scss
https://trello.com/c/xmXa6POJ/141-fjerne-understreking-av-lisensikonene
> Fix byline license-icons

- packages/designmanual/dummydata/mockPrograms.js
- packages/ndla-ui/src/Frontpage/FrontpageAllSubjects.tsx
NDLANO/Issues#2742 og https://trello.com/c/OonNFR4c/1236-justering-forsidefaner
Legger på visible på gruppe for å skjule på forsida, men likevel kunne ha med alle fag i Alle-fana.
Test:
* Sjekk forside på designmanual og sjå at fanene Alle, Utgått og Kommende er med.
> Added visible prop to filter categories on frontpage.

- packages/ndla-notion/src/NotionDialog.js
Den gamle stylingen med `flex-wrap: wrap` gjorde at tekst kunne havne til høyre for bilde. Feks i forhåndsvisning av forklaringen eller visning av forklaring i listing-frontend. Se feks https://liste.test.ndla.no/nb/concepts/2879. Nå vil elementene alltid ligge ovenfor hverandre.
Hvordan teste:
1. checkout
- listing: `master`
- frontend-packages: `2774-bugfix-concept-layout`
2. `ndla link listing-frontend -l ndla-notion`
3. `yarn install --force` i listing
4. Åpne feks http://localhost:3000/nb/concepts/2879. Teksten skal plasseres under bildet.
5. På https://liste.test.ndla.no/nb/concepts/2879 plasseres teksten til høyre for bildet.
> Notion dialog renders content in flex column

- packages/util/src/markdownHelpers.ts
Fixes https://github.com/NDLANO/Issues/issues/2760
Inntil videre har jeg skrudd av nesten all markdown-parsing for captions. Nå støttes **bold**, *kursiv*, <sup>sup</sup> og <sub>sub</sub>
Kan testes ved å linke inn ndla-ui og ndla-util, for deretter å se på http://localhost:3000/subject-matter/learning-resource/31182/edit/nb. Alternativt kan man forsøke å oppdatere captions til å ta i bruk noe fra https://jonschlinkert.github.io/remarkable/demo/.
> 2760 Disabled all markdown parsing except for emphasis, sub and sup

- packages/ndla-ui/src/AudioPlayer/initAudioPlayers.tsx
Fixes https://github.com/NDLANO/Issues/issues/2783
Det overordnede problemet er her fortsatt: `Controls` og `SpeechControl` rendres utenfor appen. Løsningen i denne PR'en er derfor ikke ideell, men den er bedre enn den nåværende situasjonen. 
`LocaleProvider` har blitt fjernet, slik at vi ikke tukler med `18nNextInstance` på samme måte. Dette har den uheldige side-effekten av at komponentene som blir rendret på nytt i `initAudioPlayers` alltid vil være på bokmål. Jeg fikset dette ved å bytte over til `ReactDOM.hydrate`, som gir oss funksjonaliteten uten at innholdet faktisk endrer seg.
> Removed i18nextProvider and switched ReactDOM.render over to ReactDOM.hydrate

- packages/ndla-ui/src/Image/Image.jsx
- packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap
Fikser automatisk skalering av bilder i Image-komponenten. Dette fungerte ikke fordi `<source>` og `<img>` ikke var direkte barn av `<picture>`.
> Source and img tags are now direct children of picture tag in Image

- packages/designmanual/.storybook/preview-head.html
Dersom man åpner designmanualen uten å ha språk satt i local-storage så defaultes det til engelsk. Dette fordi i18n i @ndla/ui har følgende detection-order: ['path', 'localStorage', 'htmlTag'].
Storybook sin preview <html> tag har statisk "lang='en'" attributt og derfor blir det engelsk. Denne hacken fikser dette siden det ikke er mulig å sette preview sin "lang" attributt i html-elementet. Se issue https://github.com/storybookjs/storybook/issues/11706
> Fix default language in storybook preview

- packages/ndla-editor/package.json
- packages/ndla-editor/src/SlateBlockMenu.tsx
- packages/ndla-editor/src/index-javascript.js
- packages/ndla-editor/src/index.ts
- yarn.lock
Fixes https://github.com/NDLANO/Issues/issues/2889
Gjennom fiksing av dette fant jeg ut at React Router 6 må oppgraderes før man kan linke lokalt. Før vi kan gjøre det må vi over til React 17 i Frontend-packages, da React Router 6 er avhengig av dette. 
Hvordan teste: 
1. Lag en ny fil i ED og kopier over innholdet fra SlateBlockMenu. 
2. Erstatt SlateBlockMenu-importen i SlateBlockPicker.
3. Gå inn på http://localhost:3000/subject-matter/learning-resource/31322/edit/nb
4. Marker en seksjon med tekst og trykk på enten inline-konsept eller fotnote. Lukk deretter modalen som dukket opp.
5. Gå til ny linje og trykk på pluss-knappen. Den skal nå funke.
> Fixed issue with slate block menu not showing after clicking other modals by switching from focus-on to focus-trap-react

- packages/ndla-ui/src/Article/ArticleContent.tsx
- packages/ndla-ui/src/CopyParagraphButton/CopyParagraphButton.tsx
- packages/ndla-ui/src/CopyParagraphButton/index.tsx
- packages/ndla-ui/src/CopyParagraphButton/initCopyParagraphButtons.tsx
- packages/ndla-ui/src/index.ts
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/tooltip/index.js
Relates to NDLANO/Issues#2888
Legger til komponenten som vil bytte ut "alle" `h2` headere i artikler i article-converter / ndla-frontend (via `ArticleContent`)
For testing så anbefaler jeg å vente til jeg får ut PR'ene i article-converter og ndla-frontend som depender på denne, men bare å se på koden :smile:
> #2888: Add `CopyParagraphButton` component

- packages/ndla-image-search/package.json
- packages/ndla-image-search/src/ImageSearch.js
- packages/ndla-image-search/src/ImageSearchResult.js
- packages/ndla-image-search/src/PreviewImage.js
Gjør props relatert til checkbox i image-search mer generelt for å kunne brukes til andre formål. Skal nå både kunne brukes til å sette visuelt element fra metabilde og omvendt.
Relatert til NDLANO/Issues#2770. 
Alphaversjoner av pakken er lenket inn og kan testes direkte i PR:
https://github.com/NDLANO/editorial-frontend/pull/1304
> 2770 sync concept meta and visual

- packages/ndla-notion/src/NotionHeader.js
Relatert til NDLANO/Issues#2919
Bumper ed, article-converter og ndla-frontend etter merge og release.
Hvordan teste:
1. Åpne design-manual på /?path=/story/forklaringstjenesten--forklaringstjenesten
2. Trykk på en forklaring.
3. Lukk-knappen skal ha cursor som hånd👆  og ikke vanlig peker.
> Set cursor to pointer on Notion close button

- packages/ndla-ui/src/Figure/Figure.tsx
Gjør id og type optional i Figure for å slippe større endringer i applikasjonene.
> Fix figure typescript

- packages/ndla-notion/src/Notion.tsx
- packages/ndla-notion/src/NotionDialog.tsx
- packages/ndla-notion/src/NotionHeader.tsx
Relatert til https://github.com/NDLANO/Issues/issues/2918
Tanken er at man skal kunne passere inn en publisert-komponent som kan plasseres i NotionHeader.
> Added possibility to add additional header content for a notion

- packages/ndla-ui/src/CopyParagraphButton/CopyParagraphButton.tsx
- packages/ndla-ui/src/CopyParagraphButton/initCopyParagraphButtons.tsx
Oppgradering av denne pakken skal fikse deler av NDLANO/Issues#2937
Hvordan teste:
1. Link inn ndla-ui i ndla-frontend med `ndla link ndla-frontend -l ndla-ui` fra denne branchen.
2. Åpne http://localhost:3000/nb/subject:1:f3d2143b-66e3-428c-89ca-72c1abc659ea/topic:5:186579/topic:3:47954/resource:1:152116.
3. anchors skal ikke lenger være duplikate. Anchor vises fortsatt i audio, men dette burde vi finne en løsning på i article-converter heller.
> CopyParagraphButton hydrate should no longer cause duplicate anchors

- packages/ndla-licenses/src/getCopyString.ts
- packages/ndla-licenses/src/index.ts
- packages/ndla-licenses/src/types.ts
Relatert til NDLANO/Issues#2447
For å vise knapp for kopiering av kildehenvisning i ndla-frontend trengs streng for kopiering. Det finnes funksjoner for å generere disse i article-converter. Funksjonene jeg har lagt til her nå er identiske, men har lagt til parametre for translation og domene for at det skal fungere.
> Add getCopyString and getLicenseCredits to license package

- packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx
Den passeres inn i ndla-frontend, men brukes ikke videre fra FrontPageSearch.
> Remove unused messages prop

- packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx
Brukes ikke innad i komponenten.
> remove unused infoText prop

- packages/ndla-licenses/src/LicenseByline/LicenseIconList.tsx
Tilbakemelding fra https://github.com/NDLANO/ndla-frontend/pull/861
> Made hover color on LicenseIconList a little brighter when using light theme

- packages/ndla-ui/src/CopyParagraphButton/CopyParagraphButton.tsx
Relatert til NDLANO/Issues#2951
Fikser en feil som førte til at header med lang tekst som ble vist over flere ble feil indentert.
Den enkleste måten å teste dette er nok å åpne https://test.ndla.no/nb/subject:1:ff69c291-6374-4766-80c2-47d5840d8bbf/topic:1:7042c278-5b24-4f45-8875-30f034cbeaab/topic:1:68b378fb-2d7e-4301-b0a1-ab10fea6aac9/resource:5de66b75-3aee-4f4b-9ec5-0905a3d1b7bd og legge til stylen manuelt med inspector.
Vanlig måte:
1. Start article-converter lokalt med ndla-ui og ndla-article-scripts linket inn.
2. Start graphql-api med lokal article-converter
3. Start ndla-frontend med lokal article-converter og graphql-api
4. Åpne artikkelen over lokalt.
> Fix CopyParagraph header indentation

- packages/ndla-licenses/src/__tests__/getCopyString-test.ts
- packages/ndla-licenses/src/getCopyString.ts
- packages/ndla-licenses/src/types.ts
En liten glipp i første versjon av getCopyString-funksjonen. Locale skal ikke brukes i translation-funksjonen
> Do not use locale for translations in getCopyString functions

- packages/ndla-licenses/src/__tests__/getCopyString-test.ts
En liten typo i en test som ble oppdaget før publisering av https://github.com/NDLANO/frontend-packages/pull/992. Sjekker at testene går gjennom og merger.
> Fix getcopystring testdata path

- packages/core/scss/global/utilities/utilities.grids.scss
- packages/ndla-ui/src/Figure/Figure.tsx
- packages/ndla-ui/src/Figure/component.figure.scss
Se https://github.com/NDLANO/Issues/issues/2927. Har laget to forslag til løsninger. Testes ved å gå til "Bilder" i designmanualen.
Her er en alternativ løsning hvor animation keyframes er brukt for å fake riktig animasjon på bildeskalering. Den skal være riktig så lenge det er et element ovenfor med 24px margin (feks en paragraf). Om dette ikke er tilfellet vil den nok hoppe 24px ned på slutten av animasjonen
Fordelen sammenliknet med den andre løsningen er at det ekspanderte bildet ikke har `float: right`. Margin collapsing er derfor ikke et problem. Det er derimot usikkert om animasjonen vil se riktig ut på alle enheter
> Scale images correctly both from left and right (v2)

- packages/core/scss/global/utilities/utilities.grids.scss
- packages/ndla-ui/src/Figure/Figure.tsx
- packages/ndla-ui/src/Figure/component.figure.scss
Se https://github.com/NDLANO/Issues/issues/2927. Har laget to forslag til løsninger. Testes ved å gå til "Bilder" i designmanualen.
Animasjonene fungerer fint nå, men dersom elementer over og under har margin, vil summen av marginen bli større. Dette er fordi margin collapsing ikke fungerer når `float` er satt i css.
Har gjort et par endringer for å få animasjonene til å gå i riktig retning. Dette styres av en ny klasse `&--right`
- float-styling er nå alltid satt, og er basert på om bildet er høyrejustert eller venstrejustert.
- left/right-posisjon swappes nå dersom bildet er høyrejustert. Dette gjøres i grids-expand.
> Scale images correctly both from left and right

- packages/ndla-ui/src/LearningPaths/LearningPathMobileHeader.tsx
Fikk feilmelding i ndla-frontend da jeg oppdaterte ndla-ui. En import som må endres fordi komponenten er flyttet til index.ts.
> Fix ContentTypeBadge import

- packages/ndla-accordion/package.json
- packages/ndla-image-search/package.json
- packages/ndla-modal/package.json
- packages/ndla-modal/src/ModalCloseButton.tsx
- packages/ndla-notion/package.json
- packages/ndla-ui/src/Filter/FilterButtons.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenu.tsx
Ikke noen funksjonelle endringer.
Ikoner er brukt flere steder uten at pakken er definert i package.json. Legger det til to steder og rydder litt opp i noen imports.
> Add ndla icon to package.json where missing

- packages/ndla-notion/src/NotionHeader.tsx
En liten quickfix. NotionHeader hadde tidligere definert en funksjon med event som input. Legger dette tilbake da det ikke skulle vært fjernet.
> Add event param to NotionHeader onClose prop definition

- packages/ndla-licenses/src/__tests__/getCopyString-test.ts
- packages/ndla-licenses/src/getCopyString.ts
Fikser formatering og rekkefølge på initialer for personer med mer enn to navn i kildereferanse.
figureApa7CopyString viser kun år, men endrer den nå til å ta inn dato som streng. Så slipper man å opprette og håndtere Date-objekter hvert sted som bruker denne funksjonen.
> Feilretting og forbedring av kildehenvisnings-funksjoner

- packages/ndla-ui/src/Topic/Topic.tsx
Problemet kan sees på https://staging.ndla.no/nb/subject:1:ff69c291-6374-4766-80c2-47d5840d8bbf/topic:1:d80bd6db-2485-4063-ba6c-3a040d039da2/topic:1:00d325d9-d87a-4ef6-9514-7017b0e6a291/
det nederste bildet vises for zooma fordi vi ikkje setter en fit på bildet. Ved å sette object-fit: cover ser det bedre ut i denne sammenhengen. 
Test: Link inn lokalt og sammenlign emnevisninga rundt om kring om det ser greit ut, og spesifikt på den innlinka sida.
> Endrer css for å skalere bilde bedre for emner

- packages/ndla-licenses/src/__tests__/getCopyString-test.ts
- packages/ndla-licenses/src/getCopyString.ts
- packages/ndla-ui/src/Article/Article.tsx
Relatert til NDLANO/Issues#2947
Nye endringer på apa-funksjoner.
Det skal kun vises en rolletype av gangen i prioritert rekkefølge (creators -> rightsholders -> processors).
Creators og processors formateres til å vise etternavn og initialer. Rightsholders vises med fullt navn da dette gjerne er en organisasjon.
Endrer også Article slik at processors kun vises dersom verken creators eller rightsholders finnes.
> apa reference updates

- packages/ndla-ui/src/Article/Article.tsx
Fikser feil nevnt i trello. Var en såpass liten fiks at det er like greit å ta med nå.
Dersom kun rettighetshaver finnes i artikkel vises dette per nå under lisensikonene. Med denne oppdateringen skal det nå vises på samme linje. Om opphavsperson finnes legges rettighetshaver fortsatt på linjen under.
> Show rightsholders on same line as icons when only rightsholders are present

- packages/ndla-ui/src/Article/Article.tsx
- packages/ndla-ui/src/Article/ArticleByline.tsx
Bedre håndtering av ArticlebyLine. Rettighetshaver skal alltid vises dersom det eksisterer. Plasseres på nederste linje dersom opphavsperson finnes, ellers plasseres det øverst.
> Better handle empty contributor lists when rendering article byline

- packages/button/src/MultiButton.tsx
Løser følgende type problem:
Siden `children` proppen er definert som `() => ReactElement` må vi sende children på følgende måten:
```tsx
<Multibutton>
{() => <h1> hei </h1>}
</MultiButton>
```
Istedenfor å bruke den vanlige skrivemåten:
```tsx
<Multibutton>
<h1> hei </h1>
</MultiButton>
```
Endringen jeg innfører tillater oss å sende `children` på vanlig måte.
> changed children prop from function to ReactElement

- packages/core/package.json
- packages/core/src/mq.ts
- packages/ndla-ui/src/ErrorMessage/ErrorMessage.tsx
Ble bare brukt i ErrorMessage, og kunne fint byttes ut med en vanlig mediaquery.
Kan testes ved å sjekke ut den genererte CSS'en på Feilmelding i design-manualen i forskjellige størrelser.
> Removed facepaint dependency

- packages/ndla-licenses/src/__tests__/getCopyString-test.ts
- packages/ndla-licenses/src/getCopyString.ts
- packages/ndla-licenses/src/licenses.ts
- yarn.lock
En liste over endringer:
- Opphavspersoner og rettighetshavere skal listes opp sammen.
- Krediterte personer/organisasjoner skal separeres med komma (ikke &-tegn).
- "NDLA" skal fjernes fra figureApa7CopyString
- Lisenser skal skrives som uten bindestrek i starten og før versjonsnummer. Riktig: _CC BY-SA 4.0_. Feil: _CC-BY-SA-4.0_
> Hotfix article text apa

- packages/ndla-licenses/src/__tests__/getCopyString-test.ts
- packages/ndla-licenses/src/getCopyString.ts
Lisens i copystring for figur skal ikke vises når den er PD (markert for fri gjenbruk). Tilsvarende skal N/A-lisens også skjules.
Fikser samtidig en feil der lisens kunne bli "undefined" dersom lisens ikke finnes.
> Hotfix copystring pd license

- .gitignore
- packages/button/tsconfig.build.json
- packages/carousel/tsconfig.build.json
- packages/core/tsconfig.build.json
- packages/hooks/tsconfig.build.json
- packages/ndla-accordion/tsconfig.build.json
- packages/ndla-audio-search/tsconfig.build.json
- packages/ndla-code/tsconfig.build.json
- packages/ndla-editor/tsconfig.build.json
- packages/ndla-forms/tsconfig.build.json
- packages/ndla-howto/tsconfig.build.json
- packages/ndla-icons/tsconfig.build.json
- packages/ndla-image-search/tsconfig.build.json
- packages/ndla-licenses/tsconfig.build.json
- packages/ndla-listview/tsconfig.build.json
- packages/ndla-modal/tsconfig.build.json
- packages/ndla-notion/tsconfig.build.json
- packages/ndla-pager/tsconfig.build.json
- packages/ndla-tabs/tsconfig.build.json
- packages/ndla-tracker/tsconfig.build.json
- packages/ndla-ui/tsconfig.build.json
- packages/ndla-zendesk/tsconfig.build.json
- packages/safelink/tsconfig.build.json
- packages/switch/tsconfig.build.json
- packages/tooltip/tsconfig.build.json
- packages/util/tsconfig.build.json
Er dette noe vi har prøvd oss på før? Under lett testing har jeg ikke klart å finne noen umiddelbare ulemper med det. Å legge til `incremental`-flagget i build-filene tok `bootstrap`-tiden min fra 86 sekunder til 40 sekunder. Ser at vi kjører `tsc -b` i frontendene, som er i samme gate.
> Add incremental flag to tsconfig.build

- packages/ndla-ui/src/Masthead/Masthead.tsx
When Masthead is fixed we now check when an element gets focus and make sure it is not obstructed by masthead
> UU Fix for Masthead obstructing focused element when navigating using keyboard

- packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx
Kan testes ved å navigere eksempelet med tab-knappen og sjekke at alt fokuseres riktig.
> Removed overflow: hidden in order to show focus border when navigating with tab

- packages/ndla-ui/src/Breadcrumblist/Breadcrumblist.tsx
- packages/ndla-ui/src/Masthead/index.ts
- packages/ndla-ui/src/Masthead/utils.ts
- packages/ndla-ui/src/index.ts
- packages/util/src/resizeObserver.ts
Breadcrumblist ble plassert med en statisk avstand på 85px fra top for å kompensere for masthead. Nå som Masthead har variabel høyde har jeg implementert en hook som returnerer høyden på masthead og oppdateres hver gang den endrer seg.
Hvordan teste:
1. Kjør opp ndla-frontend med ndla-ui linket inn. `ndla link ndla-frontend -l ndla-ui`
2. Gå inn på feks http://localhost:3000/subject:1:19dae192-699d-488f-8218-d81535ce3ae3/topic:2:55163 og sjekk at Breadcrumblist plasseres riktig både med og uten banner.
> Create useMastheadHeight hook. Add variable height to Breadcrumblist

- packages/core/scss/global/utilities/utilities.shame.scss
- packages/ndla-ui/src/MessageBox/MessageBox.tsx
- packages/ndla-ui/src/TopicMenu/TopicMenu.jsx
Fikser litt diverse på masthead:
- Dialog skapte noen problemer da den innfører scroll-lock på body ved åpning av modal. Det førte til at sticky posisjonering av masthead ikke fungerte og det medførte igjen til lite jevn animasjon ut og inn av menyen. Gjør derfor en overstyring av overflow på body som løser problemet. Har ikke sett noen andre sideeffekter av dette så langt.
- Messagebox i masthead er nå uten border-radius og padding.
- Har lagt til støtte for messageboxes i TopicMenu (nødvendig for at meldingsbokser skal vises der også)
> 3023 masthead fixes

- packages/ndla-ui/src/Notion/ConceptNotion.tsx
Scripts må kunne skrus av i Slate for å unngå at editoren krasjer.
> Add prop to disable scripts in ConceptNotion

- packages/ndla-ui/src/Notion/Notion.tsx
En feil som Gunnar påpekte. Teksten i ConceptNotion burde dekke hele bredden av boksen dersom det ikke finnes noe visuelt element.
> Set ConceptNotion text width to 100% if no visual element or image

- packages/designmanual/stories/produksjonssystem/SlateBlockMenuExample.jsx
- packages/ndla-howto/src/StaticInfoComponents/index.ts
Legger til howtos for forklaring og liste av forklaringer.
Disse kan testes i plussmeny på /?path=/story/produksjonssystem--how-to
> Add Concept and ConceptList howtos

- packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx
Kanskje ikke like spennende hover-effekt lenger, men det får nesten bare være.
Kan testes ved å linke inn frontend-packages og hovere over fagartikler.
> Removed bounce from search item description in order to avoid text movement on hover

- packages/ndla-howto/package.json
- packages/ndla-ui/package.json
- packages/ndla-ui/src/Masthead/Masthead.tsx
- packages/ndla-ui/src/MessageBox/MessageBox.tsx
- yarn.lock
Relatert til NDLANO/Issues#3037
Gjør endringer på Masthead og Messageboxes for å støtte:
- Rendering av markdown i messageboxes (hovedsakelig for lenker)
- Lukking av messageboxes.
- Ikke vise messageboxes som allerede er lukket av bruker. (Logikken håndteres i ndla-frontend, men har lagt inn mulighet for å sende inn funksjon onCloseAlert som legger issue-nummer i localStorage)
> 3037 extended alert functionality

- packages/designmanual/stories/molecules/NotionBlock.tsx
- packages/designmanual/stories/organisms/NotionBlockExample.tsx
- packages/ndla-ui/src/Notion/FigureNotion.tsx
- packages/ndla-ui/src/Notion/Notion.tsx
- packages/ndla-ui/src/Notion/NotionVisualElement.tsx
Et par oppdateringer på ConceptNotion:
- Fjerne `caption={title}` fra lisens. Dette førte i praksis til at tittelen ble vist to steder ganske nærme hverandre og var derfor unødvendig.
- Alltid rendre markdown.
- Støtte iframe og external embeds. Disse ble per nå ikke vist.
> 3016 concept block plugin

- packages/ndla-ui/src/Notion/Notion.tsx
Markdown i ConceptNotion skulle vært rendret som body i utgangspunktet. Lokalt på maskinen min fungerer rendering av markdown i article-converter riktig nå. Men det gjør det forsåvidt uten at 'body' er satt også.
> Render concept notion markdown as body

- babel.config.js
- package.json
- packages/carousel/src/CarouselAutosize.tsx
- packages/core/package.json
- packages/core/src/breakpoints.ts
- packages/core/src/colors.ts
- packages/ndla-modal/src/Modal.tsx
- packages/ndla-pager/src/Pager.tsx
- yarn.lock
Så på noe urelatert og kom frem til at polished kunne fjernes, så hvorfor ikke? Nesten all css er hentet ut fra de ferdig-genererte filene, utenom `em`-kalkulasjonen i `CarouselAutoSize`. Der prøvde jeg meg på et regnestykke. `polished` bruker 16 som default-størrelse på `em` hvis man ikke passerer inn noe annet.
> Removed polished in favor of regular css

- packages/designmanual/stories/pages/ResourceBoxExample.jsx
- packages/ndla-ui/src/ResourceBox/ResourceBox.tsx
Relatert til NDLANO/Issues#3002
133% width på ResourceBox settes nå ved hjelp av Figure som har dette innebygd. Dette var nødvendig for enkel bruk av komponenten i Slate. Har samtidig forenklet stylingen.
Hvordan teste:
- Åpne ?path=/story/sammensatte-moduler--ressurs-fra-lenke
- Styling skal se likt ut som før bortsett fra noen små endringer i marginer/padding. Sjekk responsitivitet for alle skjermbredder.
> Resourcebox styling updates

- packages/designmanual/stories/molecules/NotionBlock.tsx
- packages/designmanual/stories/molecules/NotionList.tsx
- packages/designmanual/stories/molecules/NotionSiteTabs.jsx
- packages/designmanual/stories/organisms/NotionBlockExample.tsx
- packages/designmanual/stories/pages/SearchResult.jsx
- packages/ndla-ui/src/Notion/ConceptNotion.tsx
- packages/ndla-ui/src/Notion/FigureNotion.tsx
- packages/ndla-ui/src/Notion/Notion.tsx
- packages/util/src/__tests__/__snapshots__/markdownHelpers-test.ts.snap
- packages/util/src/__tests__/markdownHelpers-test.ts
- packages/util/src/markdownHelpers.ts
Avventer https://github.com/NDLANO/frontend-packages/pull/1115
Lister ble ikke rendret i blokkforklaring. Har derfor gjort noen endringer i markdownHelpers:
- Whitespace blir ikke lenger escaped ved parsing av markdown. 
- Dette fører til at sub og sup KUN vil fungere dersom det ikke er whitespace som innhold. Ser ut til at dette er en forventet begrensning med markdown.
- Lister fungerer nå. Parsing av disse ble forhindret av at whitespace ble escaped. Den klarte ikke å lese `1.\ Første listepunkt` som et listepunkt. Uten escaped whitespace blir det nå `1. Første listepunkt` som er riktig
- Har laget en enkel snapshot-test for å kunne oppdage om noe brekker dersom vi oppdaterer funksjonen mer i framtiden
- Lagt til eksempelvisning av forklaringsblokk med diverse markdown
Fjernet samtidig …
> Markdown list rendering

- packages/designmanual/stories/molecules/NotionBlock.tsx
- packages/designmanual/stories/molecules/NotionList.tsx
- packages/designmanual/stories/molecules/NotionSiteTabs.jsx
- packages/designmanual/stories/organisms/NotionBlockExample.tsx
- packages/designmanual/stories/pages/SearchResult.jsx
- packages/ndla-ui/src/Notion/ConceptNotion.tsx
- packages/ndla-ui/src/Notion/FigureNotion.tsx
133% width på elementer i artikler settes ved å wrappe elementet i en `<Figure type="full" />`. Fjerner derfor dette fra ConceptNotion og endrer eksempelet. (Blokkvisning av forklaringer). 
Sider som er endret:
- https://frontend-packages-pr-1115.ndla.sh/?path=/story/søk--søkeside (Padding har forsvunnet fra sidene, men virker basert på koden som om dette har vært forsøkt fjernet tidligere). 
- https://frontend-packages-pr-1115.ndla.sh/?path=/story/sammensatte-moduler--blokkvisning-begrepsforklaring. Lagt inn eksempel på forklaring der lisens mangler. Grå linje skal vises i bunnen. Se også tab for visning i artikkel.
> Concept notion fullwidth fixes

- packages/designmanual/stories/molecules/NotionBlock.tsx
- packages/designmanual/stories/organisms/NotionBlockExample.tsx
- packages/ndla-article-scripts/src/conceptScripts.js
- packages/ndla-article-scripts/src/figureScripts.js
- packages/ndla-notion/src/NotionDialog.tsx
- packages/ndla-ui/src/Notion/ConceptNotion.tsx
- packages/ndla-ui/src/Notion/FigureNotion.tsx
- packages/ndla-ui/src/Notion/Notion.tsx
- packages/ndla-ui/src/Notion/NotionImage.tsx
- packages/ndla-ui/src/Notion/NotionVisualElement.tsx
Alt kan testes i https://frontend-packages-pr-1118.ndla.sh/?path=/story/sammensatte-moduler--blokkvisning-begrepsforklaring
Har et par oppdatering til:
- Stylingen på lister fungerer generelt ikke bra for lister som vises utenfor artikler. Dette burde klart fikses senere. Kanskje etter omskriving fra sass til emotion. Inntil videre må styling for lister overstyres.
- Test: Sjekk at listen i eksempel holder seg innenfor boksen for alle skjermbredder.
- Rendrer markdown i forklarings-modal.
- Test: Sjekk eksempel. Viktig at spesielt subscript/superscript og liste fungerer.
- Video iframes tilbakestilles ved hver gang en modal lukkes for å stanse avspilling
- Test: Start video i modal og lukk den. Video skal stoppe.
- H5P får tilbakestilt source (tvinge ny render) første gang modalen åpnes. …
> Concept notion fixes. Markdown, list styling, iframe example.

- packages/ndla-article-scripts/src/conceptScripts.js
Scriptet som resizet iframes ved åpning ble kun kjørt når innholdet var plassert i en iframe viewport. Dette skal kjøres uansett om det er i en iframe viewport (blant annet i designmanual) og i ed/ndla-frontend.
> Run iframe resize in concepts also when in production environment

- packages/designmanual/stories/molecules/NotionBlock.tsx
- packages/designmanual/stories/molecules/NotionSiteTabs.jsx
- packages/ndla-article-scripts/src/conceptScripts.js
- packages/ndla-notion/src/NotionDialog.tsx
- packages/ndla-ui/src/Notion/ConceptNotion.tsx
- packages/ndla-ui/src/Notion/FigureNotion.tsx
Gjenstår litt arbeid
Endringer:
- Mulighet til å kontrollere figurtypen på ConceptNotion -> FigureNotion. Dette for å kunne sette den til 'full' og dermed få 133% width som brukes på figurer i artikler.
- Eksemplene er oppdatert til å ta i bruk dette.
- conceptScripts gjør nå en korrekt sjekk for å hente conceptBlockIdentifier. Denne ga falske positiver og positive negativer før. (inline og block har litt forskjellig åpning av modal)
- NotionDialog hadde rar posisjonering. Tilbakestilte størresen på det bredeste formatet til 720px (denne var nylig oppjustert til 880px). Setter heller størrelsen fast i hvert intervall med `width` enn å sette en `max-width`. Da blir den midtstilt og det er ikke fare for at den blir for smal.
- Scroll ved åpning av modal trigger ikke lenger dobbelt.
- …
> Concept iframe resize fix

- packages/ndla-ui/src/Article/component.article.scss
Løser problemet med tegn i mathjax som forsvant. Siden dette må gjøres i både ed og ndla-frontend legger jeg dette inn i frontend-packages.
Hva som forårsaker problemer. Tegnet som forsvinner er en høy strek som i realiteten er en pipe `|` med transform for å gjøre den lenger. Her er det brukt en hack i form av `scaleY(500)` og `overflow:hidden` som i praksis gir 100% høyde. Dette bugger seg med en skalering på 500x (feiler på verdier over 440x ca). Ved å redusere denne til 200x, som er mer enn nok, vil pipen igjen vises.
Kan testes ved å linke ndla-ui inn i ndla-frontend og åpne http://localhost:3000/en/subject:1:734bd33b-da6d-49b0-bb34-c6df5b956f8e/topic:1:2737083d-8400-4a9f-b864-b05c42a470df/topic:1:2cd30524-12fe-41c6-9008-f36146369953/resource:20290ac7-9bad-4b1b-91cd-ef266bc9a028 …
> Force smaller transform on mathjaxdecorator to prevent disappearing elements

- packages/ndla-notion/src/NotionDialogLicenses.tsx
Relatert til NDLANO/Issues#3113
Fikser en feil der komma-separering av forfattere ikke fungerte ordentlig. Se: https://liste.ndla.no/nn/?concept=1805. Her mangler det komma mellom de to første forfatterene. 
Hvordan teste:
- Åpne en av følgende i designmanual: Listevisning eller forklaringstjenesten.
- Trykk på en forklaring.
- Se at forfattere er riktig formatert.
> 3113 author list formatting

- packages/designmanual/dummydata/mockExplanationService.js
- packages/ndla-notion/src/NotionDialogLicenses.tsx
Relatert til NDLANO/Issues#3113
Blingset på indeks i omskriving fra reduceRight til reduce. For å se at innsetting av "og" og komma blir riktig har jeg utvidet den første forklaringen på eksempelet "forklaringstjenesten" med to forfattere til.
> Render conjunction at correct index in dialog licenses

- packages/ndla-pager/src/Pager.tsx
- packages/ndla-ui/src/BlogPosts/BlogPost.tsx
- packages/ndla-ui/src/CreatedBy/CreatedBy.tsx
- packages/ndla-ui/src/Footer/FooterLinks.tsx
Importerer `Link` og `LinkProps` steder man egentlig ikke trenger det. I `styled`-tilfellene vil `SafeLink` holde, mens man heller kan passere inn `SafeLink` som komponent i `Pager`.
> Removed unneeded react router imports to ease rr6 transition

- packages/ndla-modal/src/Modal.tsx
Relatert til NDLANO/Issues#3110
Bredde/høyde-enheter på modal skal nå være riktig slik at modaler får begrenset størrelse.
Hvordan teste:
- Trykk på feideknapp på en av sidene i "Sidevisninger". Modalen skal ikke dekke hele vinduets bredde.
- Åpne "forklaringstjenesten". Modalen skal ikke dekke hele vinduets bredde.
> 3110 modal max width fix

- packages/ndla-ui/src/Article/component.article.scss
Har testet denne størrelsen i ed og jeg har ikke klart å lage formler som er så store at absoluttverdi-markører blir for korte.
> Change absolute marker scaling to 100

- packages/designmanual/stories/pages/ResourceBoxExample.jsx
- packages/ndla-ui/src/ResourceBox/ResourceBox.tsx
Relatert til NDLANO/Issues#3002
Har fått tilbakemelding på design:
- `alt` på bilde skal settes fra bildeobjektet som hentes fra image-api. Dette må nå sendes inn som et bildeobjekt med `src` og `alt`.
Av annet har jeg ryddet litt opp i komponenten:
- Fjernet wrapper rundt bilde
- Satt marginer/gap og liknende fra `spacing`
- Rendering av authors kun dersom authors finnes.
Hvordan teste:
- Sjekk at komponenten ser lik ut som før på /?path=/story/sammensatte-moduler--ressurs-fra-lenke. Spesielt viktig at den oppfører seg bra responsivt fra smal skjerm til full bredde.
> 3002 external embed fullframe type

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Fjerner "Kommer høsten 2022", og gjer klart til neste runde: "Se smakebiter fra fag under utvikling."
> Fjerner "Kommer høsten 2022"

- packages/safelink/src/SafeLink.tsx
Unngår et hardt krasj. RR5 autogenererte en lenke til siden du stod på automatisk. RR6 er ikke like hyggelig. Dette problemet er nok mest hyppig i designmanualen, da store deler av testdataen vår har udefinerte lenker.
> Provide an empty fallback string to account for cases where the SafeLink to prop is undefined.

- packages/designmanual/stories/molecules/breadcrumbs.tsx
- packages/ndla-ui/src/Breadcrumb/BreadcrumbItem.tsx
- packages/ndla-ui/src/Breadcrumb/HeaderBreadcrumb.tsx
En ganske usynlig feil som dukket opp i da komponenten skulle implementeres i ndla-frontend.
Prikkene ved collapse er grå. Dette er også tilfellet på designmanual.ndla.no. Det er bare ikke så lett å se siden grå og blå på hvit bakgrunn ser likt ut:
Hvordan teste:
- Åpne PR-instans av designmanual og sjekk at prikkene er blå.
> Restructure breadcrumbs to make overriding text ellipsis color easier

- packages/ndla-ui/src/Notion/FigureNotion.tsx
Feilretting basert på kommentar i PR https://github.com/NDLANO/article-converter/pull/333. Modal for regler av bruk på et visuelt element skal ha tittel som er tilpasset typen visuelt element. 
Det er snakk om tittelen i denne modalen. Utsnitt hentet fra etter feilen er rettet:
Hvordan teste:
- Åpne /?path=/story/sammensatte-moduler--blokkvisning-begrepsforklaring
- Trykk på visuelt element og deretter "Bruk bildet/video/h5p" på alle blokkforklaringer.
- Tittel i modalen skal nå tilpasse seg typen visuelt element. E.g. om det er et bilde skal det så "Regler for bruk av bildet:". Tidligere sto det alltid "Regler for bruk av forklaring".
> Show correct type in concept block visual element modal

- packages/ndla-ui/src/SearchTypeResult/SearchViewType.tsx
Closes https://github.com/NDLANO/Issues/issues/3120 
Kan testes ved å gå til lti-søk og sjekke at ikonene som endrer visningstype er riktig plassert.
> Fix placing of buttons when few resources

- packages/designmanual/stories/molecules/NotionBlock.tsx
- packages/ndla-ui/src/Notion/ConceptNotion.tsx
- packages/ndla-ui/src/Notion/FigureNotion.tsx
- packages/ndla-ui/src/Notion/NotionVisualElement.tsx
Et par nye endringer som var ønsket. Alt kan testes i /?path=/story/sammensatte-moduler--blokkvisning-begrepsforklaring
Fullscreen knapp på video i blokkforklarings-modal skal fungere ⬇️ 
<details>
<summary>
bilde
</summary>
</details>
Tittel skal vises i toppen av lisensmodal. Både i "Bruk forklaring" fra blokkforklaring og "Bruk -innholdstype-" i modalen.⬇️ 
<details>
<summary>
bilde
</summary>
</details>
Samme sted som over. Utlisting av personer/bedrifter skal nå grupperes på samme måte som i feks bilder. Kategoriseres etter Opphaver, Rettighetshaver og Bearbeider. Hver forfatter får også type foran navnet sitt, feks "Forfatter"⬇️ 
<details>
<summary>
bilde
</summary>
</details>
> Hotfix block concepts

- packages/ndla-ui/src/User/apiTypes.ts
- packages/ndla-ui/src/User/index.ts
- packages/ndla-ui/src/index.ts
Jobber med å nøste opp tooltip-problematikken. Kom over en situasjon fra tidligere PR med `UserInfo`-komponent der det var noe krøll med API-typer. Ikke breaking på runtime, men feil typer. Exposer disse for å ta dem inn i f.eks `ndla-frontend`
> Expose more types for code sharing

- packages/designmanual/stories/pages/MyNdla.tsx
- packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
- packages/ndla-ui/src/MyNdla/Resource/FolderInput.tsx
- packages/ndla-ui/src/MyNdla/Resource/index.ts
- packages/ndla-ui/src/MyNdla/index.ts
- packages/ndla-ui/src/index.ts
Lagt til ny input-komponent for oppretting av ny mappe. En kjapp liste over features. Ellers se figma-skisse for design:
- Aria-label på input (Ny mappe) og knapp (Lukk). Med translations.
- Mulighet for autoFocus. Da blir hele input-feltet markert ved mount.
- props for å legge til mappe ved enter-trykk i input og onClose ved trykk på lukk-knapp.
Animasjon kan gjøres utenom komponenten. Går ut fra at en max-height/opacity-animasjon holder.
<details>
<summary>Figma-skisse</summary>
</details>
> Myndla addfolder input

- packages/ndla-ui/src/Filter/FilterCarousel.tsx
Closes https://github.com/NDLANO/Issues/issues/3150 
Har fikset at knappene kun dukker opp når man skal bla gjennom filtre, og ikke blir værende i bakgrunnen når siden har plass til alle filtrene. "Bla fremover"-knappen ikke lenger henger igjen når man justerer skjermbredden. 
_Her er det feil_: https://test.ndla.no/lti og https://test.ndla.no/search?query=, der knappene "bla fremover" og "bla tilbake" ligger skjult i bakgrunnen og kan trykkes på selv om de ikke er synlige.
> Buttons only exists when necassary and adapted to window size

- packages/ndla-ui/src/ResourceGroup/ResourceGroup.tsx
- packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
- packages/ndla-ui/src/ResourceGroup/ResourceList.tsx
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
For meg gir det meir meining å skru på ny funksjonalitet enn å måtte skru av. I tillegg mangla det parameter i ResourceGroup til å styre visning av favorittikon. Og plassering av tekst i messsages var feil. Berre sjekk mouseover på ikona i launchpad her: https://designmanual.ndla.no/?path=/story/l%C3%A6ringsressurser--fagstoff
> Inverts add to favourites. Move phrases to more logic placement.

- packages/ndla-ui/src/Filter/FilterButtons.tsx
Closes https://github.com/NDLANO/Issues/issues/3160
Når man minsker skjermbredden etter å ha valgt filtre skal man nå kunne se alle filtrene.
> Show all filters when adjusting screen size

- vercel.json
En liten typo i omskrivingen. Dette er verdien som cache-control opprinnelig hadde og fortsatt burde ha. https://github.com/NDLANO/frontend-packages/pull/1142/files
> Fix vercel cache-control headers

- packages/button/src/AddButton.tsx
- packages/button/src/index.ts
- packages/designmanual/stories/molecules/MyNdlaAddToFavoritesExample.tsx
- packages/designmanual/stories/molecules/MyNdlaResourceView.tsx
- packages/designmanual/stories/molecules/TagSelectorExample.tsx
- packages/designmanual/stories/molecules/TreeStructureExample.tsx
- packages/designmanual/stories/my-ndla.jsx
- packages/ndla-ui/src/Resource/resourceComponents.tsx
- packages/ndla-ui/src/TreeStructure/TreeStructure.tsx
Gjorde endringer i MyNdlaAddtoFavoritesExample.tsx for å fullføre modalen slik designet tilsier. 
- Satt inn listeressurs
- Erstattet Ny mappe knappen i treestructureexample.
Modal har en margin top på 42px på h2 som overstyrer den i ListResource. Satt jeg !important på ResourceComponent sin margin. 
https://frontend-packages-pr-1192.ndla.sh/?path=/story/min-ndla--add-to-favorites
Kan testes her når testene er kjørt.
> Completed the design of the favourite resource modal

- packages/ndla-forms/src/Input.tsx
Relatert til NDLANO/Issues#3162
Overstyring av label i fungerte ikke alltid fordi spesifiteten på den originale stylingen og den nye stylingen var lik. Med `&&` dobles klassenavnet-selectoren og den vil dermed få høyere spesifitet.
Kan testes ved å linke ndla/forms inn i ed og sjekke feks bildeskjema. Label ved siden av input-felt skal ikke lenger være oversized.
> Increase specifity for label override

- packages/ndla-ui/src/TreeStructure/FolderItem.tsx
- packages/safelink/src/SafeLink.tsx
Har byttet anchor med SafeLink i trestruktur for at routing skal fungere ved klikk på lenker. La til støtte for ref i SafeLink da dette var nødvendig for funksjonaliteten i trestruktur.
> Use Safelink in treestructure instead of anchor

- packages/ndla-editor/src/FileListEditor.tsx
onChange i FileListEditor ble ikke kalt dersom index === 0. Retter nå opp i dette slik at det er mulig å toggle checkbox i første linje i file editor
> Fix filelisteditor checkbox onclick

- packages/button/src/MenuButton.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
Se: /?path=/story/min-ndla--elementer
Mappe/Ressurs er komponenter der hele elementet er wrappet i en `<a>`. Har derfor satt preventDefault på knapp som brukes for å unngå redirect ved trykk på knappen
> Prevent links from triggering in Resource/Folder when clicking MenuButton

- packages/button/src/MenuButton.tsx
- packages/designmanual/stories/pages/MyNdla.tsx
Et par endring:
- Menyen tilhørende MenuButton (reach) animeres nå inn uten offset på posisjon. Oppsto en visuell bug det korte øyeblikket menyen lå i veien for cursor.
- preventDefault ved trykk på MenuItem. Uten dette vil lenken på Folder/Resource redirecte samtidig 🤷
> Resourcefolder button link restructure

- packages/core/scss/global/utilities/utilities.grids.scss
Done in order to fix lists rendering over figcaption resulting in tooltips not rendering.
Closing https://github.com/NDLANO/Issues/issues/3163
> Add z-index to figure

- packages/button/package.json
- packages/button/src/MenuButton.tsx
- packages/core/scss/global/elements/_elements.page.scss
- packages/ndla-ui/src/Masthead/component.masthead.scss
- packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
- packages/ndla-ui/src/Resource/BlockResource.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
- packages/ndla-ui/src/TopicMenu/TopicMenuButton.jsx
Reach MenuButton har en bug som fører til at popoveren noen ganger forsvinner utfor skjermen ved første klikk. Denne buggen har vi kun klart å framprovosere på veldig smale skjermer.
Løsningen på dette problemet er dessverre ikke en faktisk feilretting, men en måte å omgå det. Har lagt til støtte for at popover kan alignes både til høyre og venstre som default. På den måten kan man sørge for at MenuButtons som er helt til høyre på en siden vil ha en popover som vokser mot venstre.
Buggen er ikke reproduserbar i designmanual, men test følgende:
- /?path=/story/min-ndla--elementer
- Elementer som har menyknapp på høyre side skal ha popover som vokser mot venstre.
> Use menuPopover in menubutton to handle left and right align

- packages/ndla-howto/src/ArticleInModal.tsx
- packages/ndla-modal/src/Modal.tsx
- packages/ndla-ui/src/Article/ArticleByline.tsx
- packages/ndla-ui/src/Article/ArticleNotions.tsx
- packages/ndla-ui/src/CompetenceGoals/CompetenceGoalsDialog.jsx
- packages/ndla-ui/src/Filter/FilterButtons.tsx
- packages/ndla-ui/src/Footer/FooterPrivacy.tsx
- packages/ndla-ui/src/Masthead/MastheadSearchModal.tsx
- packages/ndla-ui/src/ResourcesWrapper/ResourcesTopicTitle.tsx
- packages/ndla-ui/src/SearchTypeResult/PopupFilter.tsx
- packages/ndla-ui/src/SearchTypeResult/components/ItemContexts.tsx
- packages/ndla-ui/src/Topic/Topic.tsx
- packages/ndla-ui/src/User/AuthModal.tsx
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Har lagt til aria-label og aria-labelledby på modaler for tilgjengelighet, samt oversettelser der det var nødvendig.
Har også tilhørende PR i ndla-frontend: https://github.com/NDLANO/ndla-frontend/pull/1044, 
og i editorial-frontend: https://github.com/NDLANO/editorial-frontend/pull/1539
> Add aria-labels to modals and translations

- packages/ndla-ui/src/Resource/BlockResource.tsx
Added :focus on blockresource to show description of blockresource with keyboard navigation.
> MinNdla:  Keyboard navigation support for block resource

- packages/designmanual/stories/collated-components.jsx
- packages/designmanual/stories/molecules/ArticleBylineExample.jsx
- packages/designmanual/stories/molecules/ConceptBlockExample.tsx
- packages/designmanual/stories/molecules/ConceptBlockListExample.tsx
- packages/designmanual/stories/molecules/MessageBoxTabs.jsx
- packages/designmanual/stories/pages/ArticleAdditional.jsx
- packages/designmanual/stories/pages/ArticleAssessmentResource.jsx
- packages/designmanual/stories/pages/ArticleExercise.jsx
- packages/designmanual/stories/pages/ArticleExternalLearningResource.jsx
- packages/designmanual/stories/pages/ArticleLearningmaterial.jsx
- packages/designmanual/stories/pages/ArticleSourceMaterial.jsx
- packages/designmanual/stories/pages/ResourceBoxExample.jsx
- packages/ndla-ui/src/ResourceBox/ResourceBox.tsx
Fixes NDLANO/Issues#3187
Fjerner lisensikoner fra ressurs fra lenke.
Bytter ut navn på tidligere (og eksisterende) medarbeidere med oppdikta navn.
> 3187 remove license icons

- packages/ndla-modal/src/Modal.tsx
https://trello.com/c/gJIPVaCm/124-lagre-avbryt-i-dialogvinduet-forsvinner-bort-fra-vinduet-p%C3%A5-mobil
> Add safe area insets to DialogContent to ensure content is clickable on mobile

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Fjerner variabelnavn. Vi kan heller legge en SafeLink ved siden av.
> Remove folderName variable from addResourceTranslations

- packages/button/src/MenuButton.tsx
https://trello.com/c/0w59epAT/154-litt-rart-hopp-i-br%C3%B8dsmulestien
> Add inline-flex to StyledMenuButton to avoid ActionItem being higher than other crumbs

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Relatert til https://trello.com/c/AoHxZTUr/162-endre-lagre-til-lagre-ressurs-n%C3%A5r-en-ressurs-legges-til-i-en-mappe-og-f%C3%A5r-tags
Legger til ny oversettelse for "Lagre ressurs"
> Add save resource translation

- packages/switch/src/Switch.tsx
inline-flex gjør denne vanskelig å plassere riktig i noen tilfeller.
Jeg klarte ikke finne noen steder der dette utgjorde noen forskjell utenom i revisjsons editoren i editorial-frontend som det kommer egen pr på :^)
> #3192: Make Switch `flex` instead of `inline-flex`

- packages/designmanual/stories/molecules/ModalExample.jsx
- packages/ndla-modal/src/Modal.tsx
- packages/ndla-modal/src/StyledDialogOverlay.tsx
- packages/ndla-ui/src/CompetenceGoals/CompetenceGoalsDialog.jsx
- packages/ndla-ui/src/Filter/FilterListPhone.jsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenuModalWrapper.tsx
https://trello.com/c/B4FRVrAQ/123-lagring-av-ny-mappe-i-dialogvindu-p%C3%A5-mobil-er-litt-lite-intuitivt
https://trello.com/c/KzSByUCq/138-mobil-n%C3%A5r-jeg-skal-hjertemerke-en-ressurs-og-legge-den-i-mappe-er-det-kronglete-%C3%A5-lage-ny-mappe-det-kommer-automatisk-opp-en-dia
Erstatter slideUp-animasjonen med default zoomIn, da den skapte masse problemer som ikke var så enkle å løse. De ser ganske like ut, men både jeg og Henrik mener at zoomIn er mindre desorienterende enn slideUp. Kanskje en forbedring?
Det ser ikke ut som at dette påvirker desktop i det hele tatt, som er et drømmescenario. Hadde dog vært fint om noen kunne testet dette med en Android-emulator.
> Ensure mobile content is accessible on mobile, especially iOS

- packages/ndla-ui/src/NDLAFilm/FilmSlideshow.tsx
- packages/ndla-ui/src/NDLAFilm/NavigationArrow.tsx
Kan sjekkes ved å se at slideshow-bildene ikke lenger ligger synlig på høyresiden av NDLA film.
> Fixed issue where ndla film slideshow overflowed

- packages/designmanual/stories/molecules/NotionBlock.tsx
- packages/ndla-ui/src/Notion/FigureNotion.tsx
- packages/ndla-ui/src/Notion/NotionVisualElement.tsx
Relatert til NDLANO/Issues#3151
Legger til støtte for å sende inn buttons til bildelisens-modal i forklaringsblokk. Har i eksempelkoden lagt inn to dummyknapper. Se øverste eksempel på /?path=/story/sammensatte-moduler--blokkvisning-begrepsforklaring
<details>
<summary>Bilde</summary>
Kommer PR på article-converter etterpå
> Add support for action buttons in concept image modal

- packages/ndla-ui/src/Image/Image.tsx
Fjerner en warning i konsollen, og gjør oss mer HTML-compliant :)
> Don't forward fallbackWidth parameter to img tag to avoid HTML warning

- packages/ndla-icons/src/Icon.tsx
Nå leser skjermleseren opp "image" hver gang den kommer over et ikon, uten å faktisk forklare hva det er. Jeg tror det er god praksis å ignorere ikoner fullstendig by default.
> Hide all icons from screen reader

- packages/ndla-ui/src/Frontpage/FrontpageProgramMenu.tsx
Den gir ekstra-informasjon om hva som finnes bak "alle fag", men det er forvirrende at den leses opp etterpå. Da tenker jeg det er like greit å skjule den.
> Hide beta cursor from screen readers

- packages/ndla-ui/src/Frontpage/FrontpageHeader.tsx
Unødvendig informasjon, den er dekorativ og bør skjules.
> Hide frontpage illustration from screen reader

- packages/designmanual/stories/molecules/MyNdlaAddToFavoritesExample.tsx
- packages/ndla-ui/src/Article/ArticleFavoritesButton.tsx
Fikser en feil der hjerteknapp ikke lenger har riktig farger etter bruk av ButtonV2. Feilen vises på https://designmanual.ndla.no/?path=/story/min-ndla--add-to-favorites
Se /?path=/story/min-ndla--add-to-favorites for riktig visning i PR-instans
> Update IconButtonDualState usage to use correct ButtonV2 colors

- packages/ndla-ui/src/LearningPaths/LearningPathInformation.tsx
Relatert til https://github.com/NDLANO/Issues/issues/3253
Artikler / faktiske steg går greit, men vi tar ikke hensyn til introduksjoner og ting som ikke har artikkel.
> Make it possible to pass skipToContentId to LearningPathInformation

- packages/ndla-ui/src/Breadcrumb/BreadcrumbItem.tsx
- packages/ndla-ui/src/Breadcrumb/HomeBreadcrumb.tsx
gjorde siste element i brødsmulestien om til en lenke og la itl ariacurrent for skjermlesere.
?path=/story/sammensatte-moduler--brødsmulesti
Kan nå tabbes gjennom hele. Skjermlesere hopper ikke over siden man befinner seg på.
> BreadCrumbWCAG

- packages/ndla-forms/src/InputV2.tsx
- packages/ndla-forms/src/index.ts
- packages/util/src/index.ts
- packages/util/src/useForwardedRef.ts
`Input`- og `TextArea`-komponentene har lenge ligget dårlig an når det gjelder tilgjengelighet. Hverken label eller feilmelding har vært koblet opp mot input-feltet. Denne komponenten tvinger deg til å ta hensyn til det, og vil strengt tatt dekke alle behov vi har i ndla-frontend gitt at vi legger på litt ekstra styling. Hvis vi legger inn litt ekstra innsats kan denne også erstatte en del av de semi-korrekte inputene vi har i ED. Tar gjerne litt tilbakemelding. Det mest hårete i koden er `useForwardedRef`, som lar deg ta i bruk en ref som blir forwarded. Dette er vanligvis ikke mulig uten litt magi.
Grunnen til at jeg lagde en ny komponent framfor å modifisere den nåværende er at vi her vil kreve fler props, som vil være breaking. Kan eventuelt ta oppgraderingsjobben, men da må vi …
> Make a more accessible version of the Input component

- packages/ndla-ui/src/Article/ArticleByline.tsx
- packages/ndla-ui/src/Article/ArticleSideBar.tsx
Fixes https://github.com/NDLANO/Issues/issues/3233
Kan sjekkes med skjermleser. Når man klikker på en "kopier"-knapp annonserer skjermleseren at lenken er kopiert.
> Add aria-assertive to copy buttons to announce the copy action

- packages/ndla-ui/src/Frontpage/FrontpageHeader.tsx
Det gir lite mening å gi skjermleseren en lenke til ndla.no/ når man er på ndla.no/.
> Hide ndla logo and link in frontpage header

- packages/button/src/IconButtonV2.tsx
- packages/ndla-ui/src/LanguageSelector/LanguageSelector.tsx
Fjerner feilmeldinger som oppsto fordi custom props ble videresendt til button.
Kan testes ved åpne ?path=/story/enkle-komponenter--knapper-beta og sjekke at feilmeldinger har forsvunnet
> Dont forward custom props to ButtonV2

- packages/ndla-ui/src/Resource/BlockResource.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
- packages/ndla-ui/src/TreeStructure/FolderItem.tsx
Fikser to ting:
- Navigasjonsvarianten av trestruktur vil ikke lenger autofokusere valgt lenke ved trykk. Dette for å ikke komme i konflikt med ønsket fokus for tilgjengelighet.
- I noen tilfeller gir det mening å åpne ressurser automatisk i nytt vindu. Legger derfor til støtte for target blank på liste og blokkressurs.
> Disable autofocus in treestructure. Support blank links in resources

- packages/button/src/IconButtonDualStates.tsx
- packages/ndla-ui/src/Resource/resourceComponents.tsx
Fjerner feilmeldinger grunnet active-prop som er ugyldig og manglende key i liste grunnet en tom fragment.
> Fix error caused by illegal html props and missing keys

- packages/button/src/LoadingButton.tsx
- packages/button/src/index.ts
- packages/ndla-modal/src/ModalCloseButton.tsx
- packages/ndla-ui/src/TreeStructure/ComboboxButton.tsx
- packages/ndla-ui/src/TreeStructure/FolderItem.tsx
- packages/ndla-ui/src/TreeStructure/TreeStructure.tsx
- packages/ndla-ui/src/TreeStructure/index.ts
- packages/ndla-ui/src/TreeStructure/types.ts
- packages/ndla-ui/src/index.ts
Hva som er nytt:
- Ved klikk på enter i trestruktur skal onSelectFolder nå trigges slik at skjemaet i modalen i ndla-frontend blir oppdatert.
- Har laget en ny komponent `LoadingButton` som er en enkel wrapper rundt ButtonV2 med all funksjonalitet, men med innebygd spinner og loading prop.
- Eksponerer flere props fra ModalCloseButton.
> Loadingknapp. Riktig select i trestruktur ved enterklikk.

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/c6YQBcqW/219-p%C3%A5-slutten-av-informasjonen-om-hva-feide-henter-legger-vi-til-tekst
Korresponderende PR kommer i ndla-frontend
> Add translations for user info support

- packages/ndla-ui/src/TreeStructure/AddFolderButton.tsx
- packages/ndla-ui/src/TreeStructure/TreeStructure.tsx
Det er nå mulig å legge til mapper i trestruktur selv om den er lukket. Altså "Ny mappe"-knappen er ikke lenger disabled
> Add folder button works when treestructure is closed

- packages/button/src/MenuButton.tsx
- packages/ndla-ui/src/Breadcrumb/ActionBreadcrumb.tsx
- packages/ndla-ui/src/Breadcrumb/Breadcrumb.tsx
Fixes NDLANO/Issues#3282
To feilrettinger på brødsmulestier:
- Når antallet breadcrumbs endres skal resize trigges. (Kan kun testes på ndla-frontend)
- Tilbakestilt designet på siste elementet i ActionBreadcrumb (versjonen for min ndla) slik at den får blå tekst og bakgrunn på ikon ved hover
Vi har fortsett en utfordring med at outline har offset på et par piksler og blir skjult alle steder vi har overflow hidden. Dette må vi gruble litt på, for det å sette padding overalt er ikke en god løsning på lang sikt. Merkes ved at outline blir kuttet ved tabbing gjennom elementer
> Breadcrumb fixes

- packages/safelink/src/SafeLink.tsx
Den nye utloggingsløsningen fungerer dårlig med `SafeLink`, da server-endepunktene ikke tar hensyn til språk-prefixer. Det enkleste er bare å tvinge `SafeLinkButton` til å være et anchor, og ikke en `Link`.
> Add asAnchor prop to force a safe link to return an anchor

- packages/ndla-ui/src/Resource/BlockResource.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
To små feilrettinger relatert til https://github.com/NDLANO/ndla-frontend/pull/1167.
1. Som oppdaget i PR over så vokste menubutton seg gigantisk i ressurs på mobilvisning dersom tags ikke finnes. Dette er nå løst ved å aligne items til høyre med flex-end
2. Oppdaget samtidig at blokkressurs ved blokkvisning ikke hadde konsekvent høyde. Dette skal nå fungere bedre etter at aspect-ratio er satt på bildet. Object-fit sørger for at bildet holder sitt opprinnelige størrelsesforhold og ikke forvrenges. 
Relatert til punkt 2 oppdaget jeg at svært lavoppløste bilder. Altså bilder med pikselbredde som er smalere enn blokkressursen fungerer dårlig, men dette tar vi senere.
> Prevent large menubuttons in list resource. Better image scaling in block resource.

- packages/ndla-ui/src/Resource/BlockResource.tsx
- packages/ndla-ui/src/TreeStructure/TreeStructure.tsx
Et manglende spørsmålstegn gjorde at blockresource krasjet i noen tilfeller. Ellers har maks mappedybde blitt økt til fem for å matche backend og mappevisning.
> Hotfixes for min ndla

- packages/ndla-ui/src/NDLAFilm/CategorySelect.tsx
- packages/ndla-ui/src/NDLAFilm/FilmMovieSearch.tsx
Ved åpning av ndla film-forside og trykk på "hopp til innhold" flyttes nå fokus til ytterste diven på siden. Dette fører til at hele sidens innhold leses opp. Legger derfor til støtte for å legge dette på menyen for film-emner. Ellers fikset jeg en bug på aria-expanded som var true når knappen var lukket.
Er relatert til https://github.com/NDLANO/ndla-frontend/pull/1115
> Add skiptocontentid to film topic navigation. 

- packages/button/src/AddButton.tsx
- packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
- packages/ndla-ui/src/Resource/resourceComponents.tsx
Økt responsitivitet på blokk og listevisning av ressurs. Har også sørget for at ny mappe-knappen alltid er en perfekt sirkel.
Fikser en feil der tags flyter over tittel.
Anbefaler å både sjekke designmanual og linke inn i https://github.com/NDLANO/ndla-frontend/pull/1174
> Prevent tags overflowing ListCard

- packages/ndla-ui/src/MyNdla/Resource/FolderInput.tsx
Fikser https://trello.com/c/YWWsevhD/280-rare-forslag-til-mappenavn
Skrur av autocomplete på mappe-input.
> Disable folder input autocomplete

- packages/ndla-ui/src/FactBox/component.factbox.scss
Fixes NDLANO/Issues#3305
Sjekk feks https://designmanual.ndla.no/?path=/story/enkle-komponenter--faktaboks og sjå at graderinga ikkje går heilt ned
Sammenlign med pr-installasjon.
> Forhindrer at gradering av innhold i faktaboks stopper 20px over bunn.

- packages/ndla-ui/src/User/UserInfo.tsx
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/cZrlHhnV/286-ta-bort-vi-har-hentet-f%C3%B8lgende-informasjon-om-deg-fra-feide-fordi-det-st%C3%A5r-i-overskriften-uansett
> Remove text and translations about the info we fetch from feide

- package.json
- yarn.lock
Fjerner https://github.com/NDLANO/frontend-packages/security/dependabot/60
Inkludert i babel/core siden v6
> Remove deprecated babel-preset-es2015 package

- packages/ndla-error-reporter/package.json
- yarn.lock
Fikser https://github.com/NDLANO/frontend-packages/security/dependabot/3
Fikser https://github.com/NDLANO/frontend-packages/security/dependabot/48
Dep'en brukes bare i `ErrorReporter`.
> Update isomorphic-fetch to avoid node-fetch vuln

- packages/tooltip/package.json
- yarn.lock
Fjerner `@reach/auto-id0.17`-depen for å unngå en feil som oppstår når man bruker react 17 og webpack 5.
> Downgrade reach to avoid auto-id react 18 error

- packages/ndla-ui/src/Figure/Figure.tsx
NDLANO/Issues#3321
Fjerner bruk av t fra FigureCapition. Så lenge denne brukes fra article-converter vil den aldri bruke nokke anna enn nb fordi språket ikkje tas hensyn til inni komponenten.
> Legger til felt for å sende inn tekster for knapper som skal vises.

- packages/ndla-ui/src/CopyParagraphButton/CopyParagraphButton.tsx
Fikser
https://trello.com/c/pB2h6lWQ/15-uu-knapp-for-lenker-til-h2-gir-ingen-navn-eller-antydning-hva-den-gj%C3%B8r
https://trello.com/c/UtALbg1J/19-knapp-ved-headinger-i-artikler-m%C3%A5-f%C3%A5-navn
Knapp for kopiering av lenke til overskrift hadde manglende beskrivelse, spesielt for skjermlesere.
Endringer:
- anchor-knapp har nå aria-label på format: "Kopier lenke til overskrift: Navn på overskrift".
- Overskrift kan ikke lenger tabbes til. Det er ikke nødvendig å både kunne tabbe til anchor og h2.
Hvordan teste:
- link ndla-ui inn i article-converter og ndla-frontend.
- spinn opp lokalt oppsett med graphql-api, article-converter og ndla-frontend.
- Sjekk ut feks http://localhost:3000/article/31044
- Se at riktig aria-label finnes og at tabbing fungerer som forventet. Test evt med …
> Navn og UU på kopi av overskrift i artikkel.

- packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx
- packages/ndla-ui/src/Search/SearchField.tsx
Fixes https://github.com/NDLANO/Issues/issues/3343
Fixes https://github.com/NDLANO/Issues/issues/3317
Vi har hatt en lignende feil i trestruktur tidligere. I håp om at dette treffer fremtidige luringer:
Apple anser ikke knapper som noe som kan være "activeElement". Dette gjelder hele Apple-økosystemet. De mener at en bruker forventer at et input skal beholde fokus uavhengig av om man trykker på en knapp eller ei. Løsninger som dette vil med andre ord ikke fungere. Dere kan lese rasjonalet (og en spenstig krangel) her: https://bugs.webkit.org/show_bug.cgi?id=22261
Løser det ved å fjerne kodesnutten. Har ikke sett noen umiddelbare problemer med løsningen, men blir heller ikke sjokkert om det er et edge case som ikke lenger dekkes her. Søkesleeven fortjener egentlig litt ekstra kjærlighet …
> Stop relying on activeElement for input blurring, as Safari does not support it properly

- packages/button/src/Button.stories.mdx
- packages/button/src/IconButton.stories.tsx
- packages/button/src/MenuButton.stories.tsx
- packages/button/src/MultiButton.stories.tsx
Noen ganger er ting bare enklere enn man skulle trodd. Fant nå ut hvordan man unngår at undereksempler i Button ikke vises i sidemenyen. Komponent-eksempler kan rendres direkte i `<Canvas>` 🤦 
Ny struktur:
Gammel struktur:
> Sub examples of button is no longer added to storybook sidebar

- package.json
- packages/eslint-config-ndla/base.js
- packages/eslint-config-ndla/package.json
- packages/ndla-tabs/src/FilterTabs.tsx
- yarn.lock
Dersom en dårlig lodash-import påvirker bundle-sizen vår burde vi si fra når folk prøver å gjøre det. Denne regelen gir deg kjeft dersom du importerer direkte fra "lodash", og ikke fra f.eks "lodash/partition".
> Add lodash import rule to eslint config

- packages/designmanual/stories/atoms/DrawerExample.tsx
- packages/designmanual/stories/atoms/ModalV2Example.tsx
- packages/ndla-modal/src/ModalV2.tsx
- packages/ndla-modal/src/modalStyles.ts
- packages/ndla-modal/src/types.ts
Endrer litt på måten størrelsen i modaler fungerer.
Gammelt:
Størrelsene er en prosentvis del av bredde. E.g. modalens bredde varierer fra maskin til maskin.
Ny:
Har definert et par konkrete pikselstørrelser. I Modal V1 var dette i `em`, men ser det som like kurant å bruke `px` heller. Kan godt være design vil komme med innspill på dette etterhvert, men det kan justeres når den tid kommer. `px`-størrelsene er basert på det som var i Modal V1.
Hvordan teste:
Sjekk eksempler på Skuff og Modal
> Change modal to pixel sized definitions

- packages/ndla-ui/src/SearchTypeResult/components/ItemTopicHeader.tsx
Fixes https://github.com/NDLANO/Issues/issues/3364
Er en bug i Safari (om du kan tro det).
> Add workaround to ensure crop remains on round search images when scaling

- packages/ndla-ui/src/Frontpage/FrontpageFilm.tsx
- packages/ndla-ui/src/Frontpage/FrontpageMultidisciplinarySubject.tsx
- packages/ndla-ui/src/Frontpage/FrontpageToolbox.tsx
- packages/ndla-ui/src/InfoWidget/InfoWidget.tsx
- packages/ndla-ui/src/RelatedArticleList/RelatedArticleList.tsx
- packages/ndla-ui/src/SectionHeading/SectionHeading.tsx
- packages/ndla-ui/src/Subject/Subject.tsx
- packages/ndla-ui/src/Subject/SubjectAbout.tsx
- packages/ndla-ui/src/Subject/SubjectArchive.tsx
- packages/ndla-ui/src/Subject/SubjectCarousel.tsx
- packages/ndla-ui/src/Subject/SubjectLinks.tsx
- packages/ndla-ui/src/Subject/SubjectNewContent.tsx
- packages/ndla-ui/src/Subject/SubjectShortcuts.tsx
- packages/ndla-ui/src/Subject/SubjectSocial.tsx
- packages/ndla-ui/src/types.ts
Vi har et ordentlig stort problem med heading-nivåer. 
På forsiden alene:
* Vi har ingen naturlige h1. Vi kan gjøre som NRK og Finn og ha en hidden h1.
* Tverrfaglige temaer bør være h2, ikke h1
* Verktøykassa bør være h2, ikke h1
* Fra Bloggen bør være h2, ikke h1
* NDLA Film bør være h2, ikke h1
* Nyhetsbrev bør være h2, ikke h1
* Følg oss bør være h2, ikke h1
> Proper heading types for section heading

- package.json
- packages/designmanual/.storybook/main.js
- packages/designmanual/package.json
- packages/ndla-ui/package.json
- packages/ndla-ui/src/Animation/DisplayOnPageYOffset.tsx
- packages/ndla-ui/src/Animation/Fade.tsx
- packages/ndla-ui/src/Subject/SubjectShortcuts.tsx
- yarn.lock
Skriver om react-transition-group til framer-motion.
Fade brukes blant annet på språkvelger i masthead på fagsidene ved scroll og i eksempel for strukturredigering.
Er egentlig bare å sammenlikne at animasjonene er like.
> Rewrite animations to framer-motion

- packages/ndla-ui/src/Image/Image.tsx
- packages/ndla-ui/src/Image/ImageLink.tsx
- packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap
Omgjør en endring som ble gjort for å sørge for at svg-er i concept notion ikke ble 0x0 px. Dette løses nå av containeren til det  visuelle elementet i listing frontend (egen PR)
Åpne /?path=/story/sammensatte-moduler--ressurs-fra-lenke i PR-instans og sammenlikn med prod.
Bilde skal nå se slik ut:
I designmanual har bildet masse margin som er feil: https://designmanual.ndla.sh/?path=/story/sammensatte-moduler--ressurs-fra-lenke
> Undo 100% image width to prevent oversized image wrappers in components

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
En knapp med aria-label "Innhold" er ikke beskrivende nok.
> Change aria label for menu button

- packages/ndla-ui/src/Article/ArticleContent.tsx
- packages/ndla-ui/src/CopyParagraphButton/initCopyParagraphButtons.tsx
En liten triviell blemme som ga stort utfall. Er viktig at CopyParagraphButtons hydreres etter tooltips, hvis ikke fjerner tooltip dynamikken til CopyParagraphButton
> Fix hydration order for copyparagraph onclicks to work

- packages/ndla-notion/src/Notion.tsx
Et tooltip kan bare ha et barn, da den merges sammen med barnet sitt.
> Ensure all tooltips only have one child

- packages/ndla-article-scripts/src/tableScripts.js
- packages/ndla-howto/src/StaticInfoComponents/components/Markdown.tsx
- packages/ndla-ui/src/Table/Table.tsx
- packages/ndla-ui/src/Table/component.tables.scss
- stories/molecules/SolutionExample.jsx
- stories/molecules/TableExample.jsx
Fjerner dialog-visning av tabeller. Scrolling burde være nok, og det gjør det enklere å fjerne `Dialog` fullstendig. Dette kommer til å brekke snapshots i article-converter, samt at vi må fjerne noen props der.
> Remove dialog from table

- packages/ndla-ui/src/Programme/Programme.tsx
- packages/ndla-ui/src/Programme/ProgrammeSubjects.tsx
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
I og med at trinn-knappene tar deg til en ny nettside burde de være lenker. De burde også strengt tatt være i en liste. 
Denne vil være breaking for ndla-ui / i ndla-frontend.
> Convert grade buttons to link. Add aria-current. Add aria-label to list

- packages/button/src/ButtonV2.tsx
- packages/button/src/IconButtonV2.tsx
- packages/button/src/index.ts
- packages/button/src/themes.ts
- packages/button/src/types.ts
- packages/ndla-ui/src/Frontpage/FrontpageMultidisciplinarySubject.tsx
- packages/ndla-ui/src/Frontpage/FrontpageToolbox.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenuAside.tsx
- packages/ndla-ui/src/Navigation/NavigationBox.tsx
- packages/ndla-ui/src/Programme/ProgrammeSubjects.tsx
- packages/ndla-ui/src/ResourceBox/ResourceBox.tsx
- packages/safelink/src/SafeLinkButton.tsx
- packages/safelink/src/SafeLinkIconButton.tsx
- packages/safelink/src/index.ts
Legger også til `darker` som en colorScheme. Dette kommer til å være breaking for ndla-frontend og ED.
> Make safelink use v2 styles

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Se tilhørende PR i ndla-frontend https://github.com/NDLANO/ndla-frontend/pull/1267
https://trello.com/c/JFOS9m9e/296-modal-for-favorittmerking-av-fag-som-utlogget-bruker
Oversettelser er basert på denne skissen og engelsk/nynorsk er oversatt på egenhånd
> Add translations for favorite subject login modal

- packages/ndla-ui/src/BannerCard/BannerCard.tsx
- stories/molecules/UkraineBannerExample.tsx
Fixes https://github.com/NDLANO/Issues/issues/3212
Vi bruker bare BannerCard et sted - på forsiden. Der er det innhold på tre forskjellige språk - norsk, engelsk og ukrainsk.
> Add language tags to banner card content

- packages/ndla-ui/src/ResourceGroup/ResourceList.tsx
Før var all tekst stylet med heading-style. Når det forsvinner tar den stylen fra c-article, som har serif som default.
> Force sans font on resource list

- packages/ndla-forms/src/CheckboxItem.tsx
- packages/ndla-ui/src/FileList/File.tsx
- packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
- packages/ndla-ui/src/Search/ActiveFilterContent.tsx
- packages/ndla-ui/src/Search/ContentTypeResult.tsx
- packages/ndla-ui/src/SearchTypeResult/ActiveFilterContent.tsx
- packages/safelink/src/SafeLink.tsx
- packages/tooltip/src/Tooltip/Tooltip.tsx
Fixes https://github.com/NDLANO/Issues/issues/3227
Tooltips ser ut til å bli lest opp rart av skjermleser dersom man ikke har en `Radix.Portal` rundt innholdet. Har også skrevet om `ResourceItem` ganske kraftig.
* Det aktive elementet er nå en lenke
* Fikset tooltip på `access`, `core` og `additional`. De kan ikke nås av skjermleser, men blir lest opp når man fokuserer lenken.
* `Du er her`-teksten blir nå lagt bedre inline. Konsekvensen er at `ContentTypeBadge` blir større når man hovrer `small`-teksten.
> Tooltip fixes and Resource Item a11y adjustments

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Legger til oversettelser på filter i fagsiden. Det ble litt rart når det sto "Active subject" og ikke "Active subjects". Se også tilhørende PR https://github.com/NDLANO/ndla-frontend/pull/1278
> Add subjects translation

- packages/button/src/MenuButton.tsx
- packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
- packages/ndla-ui/src/Resource/BlockResource.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
- packages/ndla-ui/src/Resource/resourceComponents.tsx
Hele containeren til ressurser og mapper fungerer som lenker, men fant ut at ctrl-klikk (åpne i ny fane ikke fungerer) og løsningen per nå krevde mye stopPropagation og preventDefault.
Har funnet en alternativ og bedre løsning der lenken får en usynlig `:after` som dekker hele containeren OG ekstra knapper fungerer fint uten stopPropagation og preventDefault.
Test:
1. Åpne PR-instans.
2. Åpne ?path=/docs/enkle-komponenter-ressurser-blockresource--block-resource
3. Endre lenken til feks https://google.com
4. Trykk på menyknapp eller tag. Det skal ikke trigge redirect til google
5. ctrl-klikk på ressurs. Det skal åpne google i ny fane
6. Trykk på ressurs. Det skal gå til google i samme fane.
Kan også testes ved å linke inn ndla-ui og button i article-converter
> Bedre håndtering av boks som lenke

- packages/ndla-forms/src/CheckboxItem.tsx
fixes https://github.com/NDLANO/Issues/issues/3429
Trykkefeltet til checkboxen strekker seg over hele den svarte linjen i bildet over. Fikset width på input objektet til å være auto som da limiter den til å kun være innenfor checkbox elementet.
CheckboxItem brukes kun i en setting og det er i denne hvor den viser filer og er en gammel komponent så trenger ikke mer omfattende forandring.
> Change ItemBoxInput width to auto to limit growth

- packages/core/scss/global/settings/settings.colors.scss
- packages/core/src/colors.ts
- packages/ndla-notion/src/Notion.tsx
Endring i design på Begrepslenker iht.: 
La til to nye farger i colors.ts i Core for å få det nye designet på plass.
> Design changes to Notion with updates to colors

- packages/select/src/Select/BaseMultiValue.tsx
- packages/select/src/Select/BasePlaceholder.tsx
- packages/select/src/Select/BaseSingleValue.tsx
- packages/select/src/Select/Select.stories.tsx
- packages/select/src/Select/Select.tsx
- packages/select/src/Select/ValueContainer.tsx
Oppdaget at søk på multiselect førte til at input dukket opp direkte etter select sin verdi. Følger heller samme mønster som for singleselect der verdien skjules når brukeren skriver et søk.
Hvordan teste:
1. Åpne Select story og test alle kombinasjoner av isSearchable og isMulti
2. Sjekk at markør alltid plasseres til venstre i boksen og at value skjules mens brukeren skriver noe (Når isSearchable)
Gammel:
Ny ("2 valgte" skjules når brukeren skriver noe):
> Multiselect input fixes

- packages/ndla-ui/src/Footer/FooterPrivacy.tsx
- stories/molecules/footers.jsx
fixes https://github.com/NDLANO/Issues/issues/3437
Linkene som er nederst i footer var ikke veldig behaglige å se på når ser på mindre skjermer. Gjør css'en  for linkene mer conditional. 
Går vekk fra `flex-direction: row` til `flex-direction: column` når skjermen er på telefon størrelse og gjemmer separator linjen.
**Iphone SE**
**Ipad**
> Coniditional CSS for footer link depending on screen size

- packages/ndla-ui/src/Embed/ConceptEmbed.tsx
- packages/ndla-ui/src/Embed/conceptComponents.tsx
- packages/ndla-ui/src/Figure/component.figure.scss
Hva som er gjort:
Overstyrer Popover sin default posisjonering. Den plasseres nå absolute ved desktop og plasseres som en fullscreen modal på mobil med scroll lock.
> Manually position concept popover depending on mobile or desktop

- packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
- packages/ndla-ui/src/Resource/BlockResource.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
- packages/ndla-ui/src/Resource/resourceComponents.tsx
Blokkressurs og mapper har identisk feil der tags ikke har padding til høyre dersom menyknapp ikke finnes. Løser dette på samme måte som det allerede er gjort i ListResource med conditional styling basert på om menyen finnes eller ikke
Fikser også en mer spesifikk feil i blokkvisning av mappe der tags manglet padding over og under dersom menyknapp ikke finnes.
> Fix tag padding for resources and folders without menuItem

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Legger til oversettelse for infoboks på side for forhåndsvisning av ressurs.
Se https://www.figma.com/proto/EqBVpeUUFZi258hkMQ8OOA/Min-NDLA-2022?node-id=483%3A22696&scaling=min-zoom&page-id=322%3A15538&starting-point-node-id=483%3A22489
> Add foldershare page info translation

- packages/ndla-ui/src/Embed/ConceptEmbed.tsx
Fikser en feil der popup tilhørende inline- eller blokkforklaring ble åpnet i feil posisjon. Gjelder spesifikt sammenlikning av språkversjoner i ed der venstre c-article alltid ble valgt som rot for portalen.
> Use closest c-article as root for concept modal portal

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
`Jeg tenker kanskje "Ansatt" (BM) eller "Tilsett" (NN) passer for "employee", "staff" og "faculty". Vi ser at fylkene bruker dette så ulikt så det er ikke mulig for oss å vite at "Faculty" alltid betyr lærer.`
Endrer teacher/staff/faculty oversettelser til en felles verdi -> "ansatt", basert på tilbakemeldingen fra NDLA.
Legger til en ny nøkkel "faculty" i user-roles.
> add faculty to phrases and give teacher/staff/faculty one translation

- packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx
Her var det både en kjent bug fra prod og en framtidig potensiell bug med z-index.
Legger tilbake children som ble fjernet ved et uhell i https://github.com/NDLANO/frontend-packages/pull/1503/files#diff-e8d687ec547ca215b5998998c42cd8a3af02ed476ff8151abce4bed11f32f6a0L147
Legger også på z-index på en wrapper rundt children, slik at dette vil legge seg foran `:after` i searchitem-kortet. Dette er nødvendig for at den skal være klikkbar
> Add children render to search item

- packages/ndla-ui/src/SearchTypeResult/SearchHeader.tsx
Ved søk på søkesiden på ndla.no vises "ingen treff på søk ..." fram til søket er ferdig. Tar nå inn parameter for loading slik at Spinner heller kan vises.
Hvordan teste:
- Link ndla-ui inn i ndla-frontend (https://github.com/NDLANO/ndla-frontend/pull/1310)
- Søk på noe tilfeldig
- Sjekk at Spinner vises fram til søket er ferdig
- Kan teste med skjermleser også. Har lagt på aria-live slik at "loading" og antall søketreff leses opp automatisk.
> Show Spinner instead of no results when search is loading

- packages/button/src/themes.ts
https://trello.com/c/mHPCrh67/149-uu-wcag-247-fokusmarkering-p%C3%A5-alle-bl%C3%A5-knapper-er-for-liten-og-kun-med-fargeendring
Dette er egentlig den eneste kontrast-greia på knapper som er problematisk, tror jeg. Hedvig var enig i at dette var en grei løsning.
> Use a light color on primary theme hover/focus

- .gitignore
- package.json
- tsconfig.json
Jeg har prøvd på dette en gang før, og feilet miserabelt (https://github.com/NDLANO/frontend-packages/pull/1049). frontend-packages har blitt oppgradert en del siden da, og jeg har troen på at vi kan få det til å fungere denne gangen (famous last words). 
Ved lokal testing går bootstrap fra ~100s -> ~50s når buildinfo allerede eksisterer. Typesjekking går fra 18s -> 3s.
> Add incremental flag to root tsconfig to speed up type checking and generation

- package.json
- packages/button/src/ButtonV2.tsx
Denne PR'en fikser en ting som har irritert meg lenge: Knapper beholder fokus-styling inntil knappen mister fokus. I de fleste tilfeller er dette egentlig ikke ønskelig. Dersom man trykker på en knapp burde man få en indikasjon på at knappen er ferdigtrykket, noe man nå ikke gjør. `focus-visible` gjør det samme som focus, men aktiveres ikke av museklikk. Denne løsningen er med andre ord like UU-vennlig som den forrige, om ikke mer.
> Replace button focus styling with focus-visible

- packages/ndla-ui/src/Masthead/Masthead.tsx
Relatert til https://github.com/NDLANO/ndla-frontend/pull/1320/files
Padding er nå lik på tvers av alle størrelser.
> Decrease Masthead content padding

- packages/ndla-licenses/src/contributorTypes.ts
I lisenser så har noen `Type` lik `Author`. I lisens lista får `Opphaver: Undefined <Forfatter>` som ikke er så gøy
> Added Author type in translationtypes

- packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
- packages/ndla-ui/src/Resource/resourceComponents.tsx
Allerede fikset i https://github.com/NDLANO/frontend-packages/pull/1563
Fixes https://github.com/NDLANO/Issues/issues/3499
Er nok mer riktig at dette er en span uansett.
> Fix padding on resource titles by switching away from heading

- packages/ndla-ui/src/MyNdla/SettingsMenu.tsx
Ikke noe kort, bare en melding fra Hedvig på Trello.
> Update padding of first mobile folder menu child to match the others

- packages/core/scss/global/elements/_elements.aside.scss
- packages/core/scss/global/elements/_elements.headings.scss
- packages/core/scss/global/elements/_elements.input.scss
- packages/core/scss/global/tools/tools.aliases.scss
- packages/core/scss/global/utilities/utilities.helpers.scss
- packages/core/scss/global/utilities/utilities.typographic.scss
- packages/core/src/fonts.ts
- packages/ndla-tabs/scss/tabs.scss
- packages/ndla-ui/src/Article/component.article.scss
- packages/ndla-ui/src/Article/component.footnotes.scss
- packages/ndla-ui/src/Aside/component.aside.scss
- packages/ndla-ui/src/Dialog/component.dialog.scss
- packages/ndla-ui/src/FactBox/component.factbox.scss
- packages/ndla-ui/src/Figure/component.figure-license.scss
- packages/ndla-ui/src/Figure/component.figure.scss
- packages/ndla-ui/src/MediaList/component.medialist.scss
- packages/ndla-ui/src/Navigation/NavigationBox.tsx
- packages/ndla-ui/src/Navigation/NavigationHeading.tsx
- packages/ndla-ui/src/RelatedArticleList/component.related-articles.scss
- packages/ndla-ui/src/Table/component.tables.scss
- packages/ndla-ui/src/Translation/component.translation.scss
- packages/ndla-ui/src/Typography/Heading.tsx
- packages/ndla-ui/src/Typography/index.ts
Dette krever egentlig at vi setter oss ned og fjerner en hel del med `/styled.h/d`. Inntil videre har jeg bare valgt å gjøre dette ett sted. Annet enn det har jeg gjort en effort for å sentralisere kinesisk styling til to filer: `tools.aliases.scss`, og `fonts.ts`. Inntil videre sørger denne funksjonen bare for at kall til `font-size(16px, 1.5)` eller `fonts.sizes('16px', 20px)` autogenerer en ekstra stil for elementer som har språket sitt satt til kinesisk. Inntil videre har jeg valgt å  skalere font-størrelse og linjehøyde med 111%, men dette kan (og bør sikkert) justeres på.
Denne PR'en kommer til å brekke styling på ndla-frontend, listing-frontend og ED. Gjerne gi tilbakemelding, da dette er et ganske så vanskelig område å navigere seg i.
Ting som gjenstår:
> New heading styles. Simplify usage of @chinese

- packages/article-converter/src/index.ts
- packages/article-converter/src/plugins/embed/audioEmbedPlugin.tsx
- packages/article-converter/src/plugins/embed/brightcoveEmbedPlugin.tsx
- packages/article-converter/src/plugins/embed/conceptEmbedPlugin.tsx
- packages/article-converter/src/plugins/embed/imageEmbedPlugin.tsx
- packages/article-converter/src/plugins/types.ts
- packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx
- packages/ndla-ui/src/Embed/AudioEmbed.tsx
- packages/ndla-ui/src/Embed/BrightcoveEmbed.stories.tsx
- packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx
- packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx
- packages/ndla-ui/src/Embed/ConceptEmbed.tsx
- packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx
- packages/ndla-ui/src/Embed/ImageEmbed.tsx
- packages/ndla-ui/src/Embed/conceptComponents.tsx
- packages/ndla-ui/src/Embed/index.ts
- packages/ndla-ui/src/Embed/types.ts
- packages/ndla-ui/src/Resource/resourceComponents.tsx
- packages/ndla-ui/src/index.ts
- packages/ndla-ui/src/model/ContentType.ts
- stories/StoryFavoriteButton.tsx
Legger til støtte for å sende inn en hjerteknapp til article-converter.
Tar over for https://github.com/NDLANO/frontend-packages/pull/1563
> Hjertemerking av embeds

- packages/ndla-ui/src/Notion/Notion.tsx
Bør uansett fikses med en migrering i concept-api, men dette hjelper før det.
> Removing whitespace to avoid breaking markdown.

- packages/ndla-ui/src/AudioPlayer/AudioPlayer.tsx
- packages/ndla-ui/src/AudioPlayer/initAudioPlayers.tsx
- packages/ndla-ui/src/Embed/AudioEmbed.tsx
- packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx
- packages/ndla-ui/src/Embed/ImageEmbed.tsx
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
* Bruk en mer React-aktig løsning for å vise/skjule full-teksten på podcast-introduksjon.
* Legge til mulighet for å skjule/vise byline på image-embeds som har satt skjul byline.
* Skjul byline på små bilder som kan ekspanderes. Vises når de er ekspandert.
* Bruker embedData sin caption før vi faller tilbake til metadataen sin caption på Brightcove og Image.
> Small embed fixes 

- packages/ndla-ui/src/Embed/H5pEmbed.tsx
Fixes https://github.com/NDLANO/Issues/issues/3559
Usikker på om dette er noe vi vil gjøre på h5p'er vi ikke får fra oembed også. Hva tenkes? Kan testes ved å linke inn alt og sjekke ut http://localhost:3000/article/37927?disableSSR=true. Krever nok at nye pakker er inne i ndla-frontend, og at man kjører GQL lokalt. Når det er oppdatert er dette en enkel one-liner. Ulempen er at h5p'en tar litt mye plass inntil den har lastet, som kan være en stund for h5p'er som denne (18mb).
> Do not set height to auto when receiving a h5p from oembed

- packages/ndla-ui/src/Embed/RelatedContentEmbed.tsx
Faller altså tilbake til `/article/${id}`
> Fall back to article page if a path cannot be found for a related content embed

- packages/ndla-ui/src/NDLAFilm/FilmMovieSearch.tsx
Fixes https://github.com/NDLANO/Issues/issues/3541
Denne plasseres egentlig ikke ting i to kolonner, men begrenser heller mengden gjenstandar i en kolonne til 4. Dersom vi ender opp med å ha ni fag her vil vi med andre ord ha tre kolonner.
> Place film topics as columns instead of rows

- packages/ndla-ui/src/Typography/Heading.tsx
Uten dette blir ikke `data-inverted` sendt videre til `Heading`-komponenten
> Forward all props to Heading component

- packages/ndla-accordion/src/AccordionHeader.tsx
- packages/ndla-ui/src/Article/ArticleByline.tsx
- packages/ndla-ui/src/index.ts
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Gjør også accordion-headerne om til h2 i article-byline, da det passer bedre med flyten til artikkelen.
Andre småfikser her:
* i18n for "Referanser" i accordion-tittel.
> Expose heading level for accordion header

- packages/ndla-editor/package.json
- packages/ndla-editor/src/FileListEditor.tsx
En liten forskjell her: Vi dekker ikke tilfellet der man oppretter et `Number`-objekt, altså `new Number(3)`. Såvidt jeg vet bruker vi ikke dette noe sted i kodebasen uansett.
> Replace lodash isNumber with native behavior

- packages/ndla-ui/package.json
- packages/ndla-ui/src/AudioPlayer/Controls.tsx
- yarn.lock
Bruker popover fra headless for volumjustering. 
NB: ser Reach fortsatt brukes flere steder inne i Controls, burde det skrives om i egne PRer?
> Rewrite volume popover to headless

- packages/ndla-ui/src/Grid/Grid.tsx
Width ble satt for å få elementene i slate til å kunne ta sin orginale størrelse, det ødelegger for border ved forhåndsvisning/visning. Legger heller den stylingen til i slate så vi opprettholder border styling generelt
> Width ruins border overflow

- packages/select/src/Select/BaseMenu.tsx
- packages/select/src/Select/Select.tsx
Fixes https://github.com/NDLANO/Issues/issues/3590
En litt -ish løsning, men den beste vi kan få til inntil videre radix fikser problemet sitt. Dersom man ikke bruker en portal og eksplisitt setter `pointer-events: auto` på select vil den fungere fint inni modaler.
> Add an inModal prop to select in order to support the new modal

- packages/ndla-ui/src/LearningPaths/LearningPathMenu.stories.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenuContent.tsx
- packages/ndla-ui/src/LearningPaths/LearningPathMenuIntro.tsx
Padding i læringssti-menyen har blitt ødelagt etter endring av base unit. Denne fikser det. 
La til en story for lettere å fikse css.
Test:
Sjekk /?path=/docs/sammensatte-moduler-læringssti-meny--docs og sjå at ting ser bra ut i forhold til stier i test.
> Added story to easier fix padding error in learningpath menu

- packages/ndla-ui/src/Embed/ImageEmbed.tsx
EmbedData.url brukes ikkje til nokke fornuftig (så vidt eg kan sjå). I første omgang er den lik som den andre verdien, men ved å endre i graphql kan vi få klikk på bilde til å åpnes i egen side.
> Adding link to image page.

- packages/ndla-image-search/src/ImageSearchResult.tsx
Bildetitler i søket croppes til høgre for bildet. Fikser det med litt css.
> Display image titles in search

- packages/select/src/Select/ValueContainer.tsx
Synne oppdaget at bokstaver i den minste selecten blir kuttet av på bunnen (man ser det om man zoomer inn). Denne fikser opp i det!
> Fix bug where characters are cut of at bottom in small select

- packages/ndla-ui/src/List/OrderedList.tsx
- packages/ndla-ui/src/global/components/component.bodybox.scss
fixes https://github.com/NDLANO/Issues/issues/3631
CSS funksjonen `counters` tar hensyn for også dybde når man er i andre elementer enn div og gjør at rekkefølgen og dybden i list element identifikasjonen. 
Siden vi kun har enten `bokstav` eller `numerisk` fjernet jeg den ene sjekken om den ikke var `letters` for å rydde litt i koden.
> Replaced counters to more static alternative counter

- packages/ndla-ui/src/Article/ArticleByline.tsx
- packages/ndla-ui/src/FrontpageArticle/FrontpageArticle.tsx
- packages/ndla-ui/src/Hero/Hero.tsx
- packages/ndla-ui/src/Layout/OneColumn.tsx
Legger til støtte for blå farge i header på hero for forsideartikler da det så veldig dårlig ut med grå header over det blå. 
Legger til mulighet for kvit default farge på accordion lisens boks.
> Article by line frontpage article

- packages/ndla-ui/src/TreeStructure/FolderItem.tsx
fixes https://trello.com/c/db2cUopy/327-n%C3%A5r-jeg-%C3%A5pner-en-undermappe-nederst-p%C3%A5-listen-b%C3%B8r-listen-scrolle-nedover-slik-at-jeg-ser-undermappene
Gjør så at om du klikker på nederste element så vil den scrolle videre nedover og vise alt innhold
> Added  focus on picker type on useEffect

- packages/ndla-ui/src/Article/Article.tsx
- packages/ndla-ui/src/FrontpageArticle/FrontpageArticle.tsx
- packages/ndla-ui/src/types.ts
Oppdaget en bug som gjør at ed krasjer når man prøver å forhåndsvise en artikkel i fra html-editor når artikkelen ikke er lagret tidligere. Dette er på grunn av at copyright ikke eksisterer .. Oppdaterer derfor typen til å kunne være undefined
> Update copyright on Article type to possible be undefined

- packages/ndla-ui/src/Table/component.tables.scss
Styling i lister i tabeller var mye større så fjerner font størrelsen som blir lagt på for lister
> Added styling for lists in table

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Trengs til å vises i snackbar når man har kopiert en mappe!
> Add copied folder translation

- packages/ndla-ui/src/User/UserInfo.tsx
- packages/ndla-ui/src/User/__tests__/parseUserObject-test.ts
- packages/ndla-ui/src/User/parseUserObject.ts
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
`primaryAffiliation` er ikke mandatory i feide. Vi bruker `eduPersonAffiliation` i backend og sjekker om den inneholder `employee` da det er felles for alle de ulike rollene.
> Changed from primaryAffiliation to only use affiliation

- packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
Oppdaget at når `Folder` brukes inne i feks `ModalBody` så vil h2-styling overskrives(se bilde), regner med at vi alltid ønsker at margin skal settes til 0  for `FolderTitle`.
> Fix margin in h2 in Folder-component

- packages/ndla-ui/src/Embed/ImageEmbed.tsx
fixes https://github.com/NDLANO/Issues/issues/3682
Det var aria-label på lenken som opplyser om at lenken åpnes i nytt vindu som tar presedens over alt-tekst på bilde som gjorde at alt-teksten ikke ble lest opp av skjemlesere.
Løses ved å fjerne aria-label fra lenken og legge denne teksten som et visuelt skjult element istedet.
> Fix image alt-text not being read by screen readers

- packages/article-converter/src/plugins/embed/fileEmbedPlugin.tsx
- packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx
- packages/ndla-ui/src/Embed/AudioEmbed.tsx
- packages/ndla-ui/src/Embed/BrightcoveEmbed.stories.tsx
- packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx
- packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx
- packages/ndla-ui/src/Embed/ExternalEmbed.stories.tsx
- packages/ndla-ui/src/Embed/H5pEmbed.stories.tsx
- packages/ndla-ui/src/Embed/IframeEmbed.stories.tsx
- packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx
- packages/ndla-ui/src/Embed/ImageEmbed.tsx
- packages/ndla-ui/src/FileList/File.tsx
- packages/ndla-ui/src/FileList/FileList.tsx
- packages/ndla-ui/src/FileList/FileV2.tsx
- packages/types-embed/src/index.ts
Den brukes egentlig ikke til noe nyttlig.
* `Figure` trenger ikke lenger ID'er.
* `File` genererte en ID, men brukte den på en `aria-describedby` uten å faktisk ha et element å peke til.
> Remove the unique sequence requirement for embeds

- packages/button/src/FavoriteButton.tsx
- packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
- packages/ndla-ui/src/ResourceGroup/ResourceList.tsx
- stories/molecules/resources.jsx
Fjerner følgende:
* En margin-prop som kun brukes i storybook.
* Tooltips. Title + aria-label er like brukervennlige, og mye raskere.
* En animasjon som spilles etter at listen har lastet. Den var veldig treg.
> Perf: Optimize ResourceItem css

- packages/ndla-ui/src/ProgrammeCard/ProgrammeCard.tsx
Flytter ansvaret for å gjøre dette over til ndla-frontend istedenfor. Da kan vi sette max-width basert på om man er på mobil eller ei. 
Fixes https://trello.com/c/UXndKiC1/379-responsiv-bug-p%C3%A5-utdanningsprogram
> Do not apply max-width constraints in ProgrammeCard component

- packages/ndla-modal/src/Modal.tsx
- packages/ndla-modal/src/types.ts
Modal-komponenten har som default satt `modal`-propen til true, som skjuler resten av siden for skjemlesere. Man kan velge å manuelt overstyre dette. Å sette `modal` til false fikser problemet med TagSelector, men fjerner `Overlay` fullstendig. Dette gir oss hvertfall en semi-funksjonell `Overlay` når `modal` er false.
> Add ability to still show overlay even if a dialog is not a modal

- packages/ndla-ui/src/ErrorMessage/ErrorMessage.tsx
hydration error on NotFoundPge.
Det er litt kjipt å få en feilmelding på feilmeldingssiden.
> Show error message regardless of window status. This removes a client

- packages/core/scss/global/utilities/utilities.grids.scss
- packages/core/scss/global/utilities/utilities.helpers.scss
- packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Fixes https://trello.com/c/vRMzBySM/388-bildeinfo-og-hjerte-flyttes-utenfor-boksen-i-mindre-st%C3%B8rrelser
Skikkelig knotete opplegg med disse float-klassene, altså. Float fungerer nå slik:
* Til tablet: 65% (13/20)
* Til desktop/stor tablet: 50%
* Mobil: 100% (samme som før)
Kan testes ved linking på http://localhost:3000/article/26617
> Fix floated image sizes on some tablet sizes

- packages/ndla-ui/src/Embed/ImageEmbed.tsx
Ser ut som at `html-react-parser` automagisk parser disse attributtene til tall for oss. Legger inn litt dobbeltarbeid slik at crop fungerer fint uten bruk av en fullverdig html-react-parser.
> Always try to parse numers from focal point and crop

- packages/ndla-ui/src/List/OrderedList.tsx
fixes https://github.com/NDLANO/Issues/issues/3699
Dette var visst ikke et slate issue, men heller et styling issue!
**Teste**:
Lag en nummerert liste og la siste element være tomt, legg et avsnitt med tekst rett under og se på forhåndsvisning av artikkelen
**Før**:
**Nå**:
> Add min-height to fix overlapping li element

- packages/ndla-tracker/package.json
- packages/ndla-tracker/src/HelmetWithTracker.tsx
- packages/ndla-tracker/src/index.ts
- packages/ndla-tracker/src/useTracker.ts
- packages/util/src/index.ts
- packages/util/src/usePrevious.ts
Veldig rudimentær implementasjon av en `useTracker`-hook. Er faktisk usikker på om vi trenger noe mer enn dette. Krever nok en del testing før vi kan gå videre. Har ikke fått testet `HelmetWithTracker` ennå.
Den fungerer på følgende måte: Når en kaller på `trackPageView` vil det sendes et `Pageview`-event til Matomo. Dersom et event allerede har blitt sendt for siden vil den aldri sendes igjen. Man trenger med andre ord ikke å bekymre seg for å kalle den fra en `useEffect`. 
Kan brukes på følgende måte:
```jsx
const TestComponent = () => {
const {trackPageView} = useTracker();
useEffect(() => {
if(!article || !condB) return;
const dims = getAllDimensions({article});
trackPageView({dimensions: dims, title: 'Test title'});
}, [condA, condB])
return <div>Test</div>
}
```
Jeg så på litt …
> Add a hook for matomo tracking

- package.json
- packages/ndla-code/package.json
- packages/ndla-code/src/CodeEmbed.tsx
- packages/ndla-code/src/Codeblock/Codeblock.stories.tsx
- packages/ndla-code/src/Codeblock/Codeblock.tsx
- packages/types-embed/src/codeTypes.ts
- stories/wrappers/SyntaxHiglighter.tsx
https://github.com/NDLANO/Issues/issues/3662
Tar over for https://github.com/NDLANO/frontend-packages/pull/1770
Veldig breaking.
Bakgrunn: `React-syntax-highlighter` fungerer ikke særlig bra på server-siden. I dag fører det til at vi får hydreringsfeil på alle sider som har kodeblokker i seg. En potensiell løsning har vært å ta i bruk en større del av `React-syntax-highlighter`, på bekostning av en stor økning i bundle-size.
Denne PR'en prøver å løse dette ved å fjerne syntax-highlighting fra `CodeBlock`. Vi krever nå istedenfor at komponenten mottar kode som allerede har blitt prosessert av Prismjs. Ansvaret for å kjøre kode gjennom Prismjs har blitt gitt til `article-converter`-delen av GQL. Det er en korresponderende PR der.
Ndla-frontend krever ingen endringer. I ED må vi nok få inn …
> Move syntax highlighting out of CodeBlock

- packages/core/scss/global/elements/_elements.details.scss
- packages/ndla-ui/src/Aside/component.aside.scss
- packages/ndla-ui/src/FactBox/component.factbox.scss
Nummerert bokstavliste i bokser har ekstra marg i forhold til talliste. Det ser litt rart ut og er ikkje i sync med designet.
Kan sjekkes på http://localhost:3000/subject-matter/learning-resource/38289/edit/nb med innlinka endringer.
> Remove roman-list from wide margin

- packages/article-converter/src/plugins/embed/campaignBlockPlugin.tsx
- packages/ndla-ui/src/CampaignBlock/CampaignBlock.stories.tsx
- packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx
- packages/types-embed/src/campaignBlockTypes.ts
Denne er breaking. Oppdaterer `CampaignBlock` til å kun ta imot ett bilde. Det kan enten plasseres på venstre- eller høyresiden, og defaulter til venstre.
> Only allow one image at a time in a campaign block

- packages/ndla-code/README.md
- packages/ndla-code/package.json
- packages/ndla-code/src/CodeBlockEditor/CodeBlockEditor.tsx
- yarn.lock
several times caused weird behavior. Instead, the component accepts a `highlight` function expected to return a formatted string
Gidder ikke legge inn en altfor god beskrivelse på hvordan man skal loade Prism-grammars, da det er så mange forskjellige måter å gjøre det på.
> Remove Prism dependency from ndla/code entirely. Loading Prism languages

- packages/ndla-ui/src/BlogPost/BlogPost.tsx
- packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx
Max-content på blog post fungerer ikke ordentlig i safari. 
Gjør også en endring i måten vi viser bilder på i kampanjeblokken. Vi letterboxer nå bildet til en viss grad når aspect-ratioen er helt på tur
Kan testes på http://localhost:3000/article/38311 med linking.
> More css fixes to new embeds

- packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Alle brightcoves har ikke copyright. Det må vi nesten tillate.
Gjerne kom med designtilbakemeldinger.
> Allow undefined copyright in embed byline

- packages/ndla-licenses/src/CCRel.ts
- packages/ndla-licenses/src/index.ts
- packages/ndla-ui/src/MediaList/MediaList.tsx
- packages/ndla-ui/src/MediaList/index.ts
- packages/ndla-ui/src/index.ts
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Nyttig for å kunne legge til elementer uten to deler. Feks "Innholdet har blitt bearbeidet" i copyright teksten :smile:
> #3715: Allow descriptionless `MediaList` items

- packages/ndla-ui/package.json
- packages/select/package.json
- packages/select/src/Select/BaseControl.tsx
- yarn.lock
- Bumper react-select (ingen breaking endringer)
- Sender ikke lenger videre alle props fra parent i BaseControl, sjekket litt opp i dette og gir ikke mening å passe ned react-select spesifikke props når vi har bygget vår egen div-wrapper(StyledBaseControl), dette fjerner også advarselen som tidligere ble vist i konsoll:
Testet opp mot selects i ed, og de ser ut til å fungere sånn de skal med denne oppdateringen!
> Select updates: package bump + fix console warning

- packages/types-embed/src/brightcoveTypes.ts
Så vi kan ta i bruk denne typen istedenfor den egendefinert i ED.
> Add projection to brightcove api type

- packages/ndla-notion/package.json
Var tidligere snakk om å gjøre `ndla/notion` til sin egen pakke, men jeg er litt var på det. Både `ndla/video-search` og `ndla/audio-search`avhenger av den, og jeg har ikke veldig lyst til at de skal være avhengige av `ndla/ui`. Vi kan dog redusere avtrykket til Notion så godt vi kan, og eventuelt fjerne det helt når vi går vekk fra den gamle bylinen.
> Remove unused deps from ndla/notion

- packages/ndla-tabs/src/Tabs.tsx
Tenker det gir mening å kun vise box-shadow når man navigerer til elementet med tastatur og ikke når man klikker med mus, enige?
Dette vil kun påvirke tabs som brukes med runde kanter, altså feks på dashboard i ed
> Update tabs pseuo class for box shadow styling

- packages/ndla-ui/src/ExpandableBox/ExpandableBox.stories.tsx
- packages/ndla-ui/src/ExpandableBox/ExpandableBox.tsx
- packages/ndla-ui/src/ExpandableBox/index.ts
- packages/ndla-ui/src/index.ts
- stories/simple-components.jsx
Bare en tynn wrapper rundt `details` og `summary`. Kan brukes til å fjerne global css på sikt.
> Add expandable box component

- packages/ndla-ui/src/locale/messages-nn.ts
Ref https://trello.com/c/zEX5dXKW/436-progresjonsvisning-fag skulle det være 'Bygger', ikke 'Byggjer'.
> Changing buildsOn nn translation

- packages/types-embed/src/h5pTypes.ts
Relates to https://github.com/NDLANO/Issues/issues/3758
Legger til støtte for `data-alt` på `h5p` `ndlaembed`'s
> add alttext to h5p type

- packages/core/src/spacing.ts
Utvidet med en ekstra spacing unit. Hoppet mellom 16px (nsmall) og 24px (normal) var litt voldsomt (spesielt mtp tilpasninger mot UU-krav som [sukesskriterie 2.5.8](https://tetralogical.com/blog/2023/10/05/whats-new-wcag-2.2/#2.5.8-target-size-(minimum)-(aa)) i versjon 2.2 av WCAG. Kravet sier 24px, men pga spacing mellom ikoner vil 20px jevnt over være nok for å oppfylle kravet. 16px (nsmall) gjerne litt i minste laget.
> Added spacing value

- packages/article-converter/src/plugins/embed/brightcoveEmbedPlugin.tsx
- packages/article-converter/src/plugins/embed/imageEmbedPlugin.tsx
- packages/article-converter/src/plugins/types.ts
- packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx
- packages/ndla-ui/src/Embed/ImageEmbed.tsx
- packages/ndla-ui/src/Embed/index.ts
- packages/ndla-ui/src/Embed/types.ts
- packages/ndla-ui/src/index.ts
https://github.com/NDLANO/Issues/issues/3813
Implementerer en option som lar konsumenten spesifisere en render-kontekst. I denne omgangen sørger den for at artikkel-rendering alltid tar i bruk caption som satt på embed-data, mens embed-rendering foretrekker "kilde"-data. 
Skal vi se på dette som en breaking for article-converter? Må oppdatere embed-siden i ndla-frontend.
> Differentiate between article and embed rendering

- packages/ndla-ui/src/Embed/IframeEmbed.tsx
- packages/types-embed/src/iframeTypes.ts
https://trello.com/c/3ZHUqmuT/84-kan-ikke-redigere-alt-tekst-for-bilde-som-settes-i-boks-for-ekstern-ressurs
> Add alt text override to iframe embed

- packages/core/src/fonts.ts
- packages/typography/src/Text.stories.tsx
- packages/typography/src/Text.tsx
Vil kreve at når vi bumper pakker at vi må bytte fra `large` til `medium` hvor `Text`-komponenten er brukt og `fonts.size.text.metaTextLarge`.
Fra det jeg har sett er det 2 steder i ndla-frontend.
> Updated text and fonts to match new typography

- packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx
- packages/ndla-ui/src/LicenseByline/LicenseDescription.tsx
Fixes https://github.com/NDLANO/Issues/issues/3832
> Wrap embed description in a spawn, allowing for items to display as inline instead of using parent flex

- packages/ndla-scripts/package.json
- packages/ndla-scripts/src/scripts/vercel-github.js
- yarn.lock
Vi *kan* fjerne vercel-dependencyen også, men da må vi erstatte det med en POST som inneholder alle filene i `storybook-static`. Da har vi heller ikke helt mulighet til å deploye lokalt lenger. Hva tenkes?
> Fetch-based vercel-github script

- packages/ndla-ui/src/ContactBlock/ContactBlock.tsx
- packages/ndla-ui/src/ContactBlock/Contactblock.stories.tsx
Fikser at rettighetshavere vises kommaseparert. Henta koden fra EmbedByline. Kan sjekkes på storybook.
> Show rightsholders comma separated

- packages/ndla-zendesk/src/ZendeskButton.tsx
Fjerner posisjonering fra komponent. Det kan heller spesifiseres ved bruk.
> Remove css specifying positioning zendeskbutton

- packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Fixes https://trello.com/c/nId4jCuA/624-forklaring-uten-lisens-m%C3%A5-ikke-ha-kolon
> Do not show a colon after embed type if there are no caption authors

- packages/ndla-forms/src/InputV3.tsx
Lagt tilbake farga, men beholdt endringa i tykkelse (se forøvrig https://github.com/NDLANO/ndla-frontend/pull/1690).
Sammen med endring i tykkelse bør forskjellen bli tydelig nok.
> Added back focus colour InputV3

- packages/core/scss/global/elements/_elements.details.scss
https://github.com/NDLANO/Issues/issues/3879
Forårsakes av at width og margin ikke klarer bli enige med hverandre. Tenkte først `display: block;`, men sida det kan hende det er en grunn te at det opprinnelig ble valgt å sette width til 100%, så har jeg istedet løst det med box-sizing.
Problemet kan, som nevnt i issuet, f.eks. sees under "Språkutvikling i barnehagealderen" her https://test.ndla.no/article/14955
> Fix UI overflow bug on nested display elements

- packages/button/src/ButtonV2.tsx
Endringer i https://github.com/NDLANO/frontend-packages/pull/2058 gjorde at fokus i modaler ble nærmest usynlig. Det ser dessuten ut til at det er en SafeLinkButton, ikke en ButtonV2, som er i bruk der (så endringa virka ikke). Så har reversert endringene, og legger en ekstra fokus-firkant (som uansett ikke virket) sammen med resten av PRen min her: https://github.com/NDLANO/ndla-frontend/pull/1690
> Visible focus arena modal

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
relatert til https://trello.com/c/Q5vlc0ZQ/655-min-ndla-varsling-om-at-hjertemerka-ressurs-vert-lagt-til-i-delt-mappe
> Add shared folder warning translations

- packages/ndla-ui/src/utils/__tests__/relativeUrl-test.tsx
- packages/ndla-ui/src/utils/relativeUrl.ts
Epost-adresser som parses av markdown returnerer automatisk en mailto-lenke. Dette gjør at disse slipper gjennom article-converter uten å få lagt på path til sida lenka vises på.
> Handle markdown-urls as is

- packages/ndla-ui/src/Article/ArticleHeaderWrapper.tsx
- packages/ndla-ui/src/Article/component.article.scss
Fikser: [Trello](https://trello.com/c/qhYst6yg/670-kompetansem%C3%A5lknappen-svever-helt-oppi-ingressen)
[#3902](https://github.com/NDLANO/Issues/issues/3902)
Nå har jeg bare endret scss, men burde kanskje vurdere å skrive komponenten over til emotion i en annen PR?
> add margin to competence goals

- packages/ndla-ui/src/LicenseByline/index.tsx
- packages/ndla-ui/src/index.ts
Tenkte denne kan brukes i søkeresultat i ed i stedet for LincenseByline som berre viser ikoner.
> Exports license-link to be used in ed

- packages/ndla-ui/src/Navigation/NavigationBox.tsx
- packages/ndla-ui/src/SearchTypeResult/components/ItemContexts.tsx
- packages/select/src/Select/Select.tsx
Liten omskrivning av Select-komponent til å ta i bruk props fra react-select, så slipper de å defineres dobbelt opp! 
Denne er breaking, så kommer tilhørende PR i ed
> Use props from react-select in Select

- packages/core/scss/global/tools/tools.aliases.scss
- packages/core/scss/global/utilities/utilities.helpers.scss
Bruker spacing for å aligne bilder til tekst.
Har forsøkt å gjøre det så likt som tidligere, men med mindre luft over. Har lagt meg på 6px og ikkje 0 fordi ingen marg såg nesten ut til å være for lite.
Synes sjølv det ser ganske bra ut men ekspandering kunne vore bedre.
> Ny xsmall--spacing som speiler xsmall fra spacing.

- packages/ndla-forms/src/InputV3.tsx
fixes https://github.com/NDLANO/Issues/issues/3920
Denne skal fikse at høyden til kommentarer tilpasses riktig når man klikker på elementet
> Add eventlistener on click to handle correct textarea element resizing

- packages/ndla-forms/src/InputV3.tsx
relates to https://github.com/NDLANO/editorial-frontend/pull/2219
Ettersom kommentarer ikke lenger bruker textareaV3 etter PR over er merget trengs ikke denne eventlisteneren heller inntil videre
> Revert on click eventlistener in textareaV3

- packages/ndla-ui/src/Embed/UuDisclaimerEmbed.stories.tsx
- packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx
Legger på rolle for å avgrense uu-innholdet semantisk.
Pluss et par ekstra eksempler.
> Add role region to uu-disclaimer

- packages/ndla-ui/src/Embed/ImageEmbed.tsx
- packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Fixes https://trello.com/c/fpaGOogD/743-sm%C3%A5-bilder-i-mobilvisning-fullbredde-mangler-hjerte-og-byline
Litt tricky greie, det her. Jeg _tror_ dette skal fikse originalproblemet uten å innføre noen nye, men tør ikke si meg helt sikker. Gjerne test litt ekstra.
> Always show embed byline on small images when on small screens

- packages/core/scss/core.scss
- packages/core/scss/global/utilities/utilities.widths.scss
- packages/ndla-ui/src/Layout/LayoutItem.tsx
- stories/basicStyles/banners.stories.tsx
Fixes https://trello.com/c/QGpwQyPt/733-unng%C3%A5-h5p-mobilvisning-endre-ved-%C3%A5-sette-hovedkolonne-til-over-620
Dette vil også påvirke læringssti-navigasjon.
> Increase article width from 66% to 70%

- packages/ndla-ui/src/FramedContent/FramedContent.tsx
- packages/ndla-ui/src/List/UnOrderedList.tsx
Fikser: [Trello](https://trello.com/c/Iuj7CA7M/310-manglende-padding-etter-lister)
Kan testes på: [Kampanje mot kredittkjøp](http://localhost:3000/subject:d1fe9d0a-a54d-49db-a4c2-fd5463a7c9e7/topic:3cdf9349-4593-498c-a899-9310133a4788/topic:1d740ae3-18da-4d49-bdfc-0aa7387e5c58/topic:ca80b078-842d-475a-8cca-9b47affe9614/resource:b29ec816-f825-4073-a348-a797a26e00e7) [Fjellvettreglene](http://localhost:3000/nb/article/10244)
> Fix spacing for lists and related content

- packages/ndla-forms/src/FormControl.tsx
- packages/ndla-forms/src/Label.tsx
- packages/ndla-forms/src/RadioButtonGroup/RadioButtonGroup.stories.tsx
- packages/ndla-forms/src/RadioButtonGroup/RadioButtonGroup.tsx
- packages/ndla-forms/src/RadioButtonGroup/RadioButtonItem.tsx
- packages/ndla-forms/src/index.ts
Makan til rotete opplegg. Tror dette skal være akkurat nok til å tilby universelt utformede radio buttons uten at vi må gi helt slipp på `FormControl`. En `FormControl` skal wrappe en `RadioButtonGroup`, og ikke individuelle `RadioButtonItem`.
> Proper interop between radio buttons and form control

- packages/ndla-forms/src/Label.tsx
Ettersom label er inline by default så ville aldri margins blitt applyet
> Label is inline-block to apply margin

- packages/ndla-accordion/src/AccordionItem.tsx
Denne ble nok med ved en feil i forbindelse med oppdatering av nytt glose-design
Fikser opp i :
> Fix broken borders accordionItem

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
hjelper å løse [trello](https://trello.com/c/YrUA9zoB/755-gjere-moderator-epost-p%C3%A5-arena-klikkbar)
> move moderator email to be on its own

- packages/ndla-ui/src/SearchTypeResult/SearchTypeHeader.tsx
Gjemmer badges i søkeresultat headers for skjermlesere. Visning av denne fører til at skjermleser leser opp "dobbel tittel", og den er i mine øyne kun dekorativ.
> Hide decorative badge for screen readers

- packages/ndla-ui/src/Embed/ConceptEmbed.tsx
Var veeeeeell stor padding ned mot dobbel linja. Fjerner unødvendig css som jeg burde spotta tidligere eller er det bare et scheme fra meg for å få flere PR'er? 🤔
> Removed padding bottom

- packages/article-converter/src/plugins/embed/linkBlockEmbedPlugin.tsx
- packages/ndla-ui/src/LinkBlock/LinkBlock.stories.tsx
- packages/ndla-ui/src/LinkBlock/LinkBlock.tsx
- packages/types-embed/src/linkBlockTypes.ts
https://github.com/NDLANO/Issues/issues/3976
Krever vel en migrering i backend? Usikker på hva den beste måten å gjøre det på er... Fjerne språk og ignorere at det noensinne har blitt satt, eller konvertere `${TITLE}` til `<span lang="nn">${TITLE}</span>`?
> Parse link block title as html. Remove language from embed types

- packages/ndla-ui/src/List/OrderedList.tsx
[Trello](https://trello.com/c/Iuj7CA7M/735-manglende-padding-etter-lister)
Gammel sak, men det ser ut som _ul_ og _ol_ har forskjellig margins som gjør at vi får mangel på spacing under _ol_'s og andre elementer. Legger til margin for å matche _ul_ elementet
Kan testes: [localhost](http://localhost:3000/subject:1:51a7271b-a9d5-4205-bade-1c125a8650b5/topic:2:a4bf97c3-9daf-4587-bc9f-822855432151/topic:1:ffac3f03-e3d0-4ac2-ace3-a83ad8cdbfc1/resource:1:19085)
> added margin similar to ul

- packages/ndla-forms/src/InputV3.tsx
- packages/ndla-forms/src/Select.tsx
Select og Input er nå akkurat like høye, uavhengig av fokus-status og sånt. Dette sørger også for at Input ikke krymper bittelitt når den får fokus.
> Make input and Select buttons more consistent

- packages/ndla-ui/src/BlogPost/BlogPost.tsx
Fixes https://github.com/NDLANO/Issues/issues/3986
Ser ut som manglende margin oppstår når andre elementer enn video (f.eks. bilde) følger også, så har lagt på en generell margin under blogposts.
> Adding margin to neighbouring elements

- packages/ndla-howto/src/ArticleInModal.tsx
- packages/ndla-icons/src/Icon.tsx
- packages/ndla-ui/src/ContactBlock/ContactBlock.tsx
- packages/ndla-ui/src/Navigation/NavigationBox.tsx
- packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
- packages/ndla-ui/src/SearchTypeResult/components/ItemContexts.tsx
We should rely on `aria-hidden` and `style` or `class`.
Denne er strengt tatt litt breaking, men vil ikke påvirke oss.
> Remove `ariaHidden` and `color` props from base Icon. 

- packages/ndla-ui/src/SearchTypeResult/SearchFieldHeader.tsx
Løser en uu-feil hvor knappene i søkefeltet på søkesiden kun leses opp som 'knapp' i skjermleser.
> Adding aria-labels

- packages/ndla-ui/src/ContentTypeBadge/ContentTypeBadge.tsx
- packages/ndla-ui/src/Resource/BlockResource.stories.tsx
- packages/ndla-ui/src/Resource/BlockResource.tsx
- packages/ndla-ui/src/Resource/ListResource.stories.tsx
- packages/ndla-ui/src/Resource/ListResource.tsx
- packages/ndla-ui/src/Resource/resourceComponents.tsx
- packages/ndla-ui/src/utils/resourceTypeColor.tsx
Støtte for et ekstra attributt på resources, slik at resources som ikke er tilgjengelig kan få en grå og kursiv tekst med en fallbacktekst:
Per i dag blir ressursen bare "tom" dersom noe mangler. NDLA har ønsket en fallback-melding dersom den er slettet for å gjøre det mer synlig (https://trello.com/c/kQTBtTTp/771-delt-mappe-siden-finnes-ikke). Vi fjerner ressursen helt den delte mappa, men inne i selve mappa, synliggjør vi med fallbackmelding. Fallback-meldingen i seg selv, når skrift ellers ikke skiller seg særlig ut, gjør egentlig dette mindre synlig. Håpet er at dette tydeliggjør litt mer at det er noe spesielt (altså, at ressursen faktisk er utilgjengelig)
> Support unavailable resources

- packages/ndla-ui/src/Embed/ImageEmbed.tsx
ImageEmbed kan plasserer som en float, som gjør det noe vanskelig å plassere slate-knapper relativt til den. Kan komme oss rundt det ved å sende inn chilren!
> Allow passing children to ImageEmbed

- packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx
- packages/ndla-ui/src/Messages/MessageBox.tsx
Fixes https://github.com/NDLANO/Issues/issues/4040
Flytter contentEditable logikken til MessageBox istedetfor for hele embeden.
> Add attribute to make messagebox noneditable

- packages/ndla-ui/src/locale/messages-nn.ts
Bitteliten skrivefeil, vanskeleg å sjå. Mappar -> Mapper i menyen.
> minor typo - mapper

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Legger til en generisk fallback label slik at artikkelressurser som mangler taksonomi kan se slik ut:
Og ikke slik:
> Adding fallback label for generic article

- packages/ndla-ui/src/List/OrderedList.tsx
https://github.com/NDLANO/Issues/issues/4052
Dette ser kanskje ut som litt mer kronglete kode, men det sparer oss fra å generere n * 50 klasser, der n er mengden nøstede lister. Sikkert greit å teste denne litt nøye, jeg prøvde meg bare på det eksemplet som lå i storybook.
> Do not generate classes for list reset. Instead, rely on css variables and data attributes.

- package.json
- packages/ndla-ui/package.json
- packages/ndla-ui/src/Embed/RelatedContentEmbed.stories.tsx
- packages/ndla-ui/src/Embed/RelatedContentEmbed.tsx
- yarn.lock
Fixes NDLANO/Issues#4049
Konverterer urler for framvisning. Gjør `xn--elevrd-mua.no` om til elevråd.no
> Handle urls on punycode format

- packages/ndla-ui/src/Article/ArticleParagraph.tsx
Fixes: https://github.com/NDLANO/Issues/issues/4057
Så ut som `dir="rtl"` legges på span elementet, ikke paragraph, i ArticleParagraph. Lagt til en selector som tar hensyn til det.
> Add back support for right-to-left languages

- packages/primitives/src/Pagination.stories.tsx
- packages/primitives/src/Pagination.tsx
Her må vi egentlig få inn oversettelser. Har ikke bestemt meg for om det er greiest å endre ark sine props til å kreve at `translations` sendes inn her, eller om det skal være opp til konsumenten. Hva tenker dere?
> Add Pagination

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
Tekster for avpubliserte ressurser, f.eks., artikler, når vi returnerer 410.
> Adding texts for unpublished resources

- packages/primitives/src/Button.tsx
Kan se problemet her: https://frontend-packages-pr-2295.vercel.app/?path=/docs/primitives-dialog--docs hvis man setter size til xsmall
Prøvde å sette aspect-ratio også, men det blir ikke 100% uten å sette noe bredde eller høyde på knappen
> Prevent IconButton resizing

- packages/ndla-ui/src/Embed/ImageEmbed.tsx
Pluss-ikonet i knappen for image resizing vil ellers vandre sørover på f.eks. /article/7640
> Reeling the icon back in

- packages/ndla-ui/src/ContentTypeBadge/ContentTypeBadgeNew.stories.tsx
- packages/ndla-ui/src/ContentTypeBadge/ContentTypeBadgeNew.tsx
- packages/ndla-ui/src/index.ts
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
- packages/ndla-ui/src/model/ContentType.ts
- packages/primitives/src/Badge.tsx
- packages/primitives/src/index.ts
Eksporterer heller en ny versjon enn å slette den gamle inntil videre. Den brukes altfor mange steder i ndla-frontend.
> Create a new version of ContentTypeBadge

- packages/primitives/src/Card/Card.stories.tsx
- packages/primitives/src/Card/Card.tsx
- packages/primitives/src/index.ts
Dette er grunnlaget for RelatedContent, søkeresultater, tverrfaglige caser og kansje `ProgrammeCard`. Har prøvd å gjøre den så stylable som overhodet mulig.
> Add Card component

- packages/primitives/src/Accordion.tsx
- packages/primitives/src/Card/Card.tsx
- packages/primitives/src/Checkbox.tsx
- packages/primitives/src/Combobox.tsx
- packages/primitives/src/Dialog.tsx
- packages/primitives/src/Menu.tsx
- packages/primitives/src/Pagination.tsx
- packages/primitives/src/Popover.tsx
- packages/primitives/src/RadioGroup.tsx
- packages/primitives/src/Select.tsx
- packages/primitives/src/Slider.tsx
- packages/primitives/src/Switch.tsx
- packages/primitives/src/Tabs.tsx
- packages/primitives/src/TagsInput.tsx
- packages/primitives/src/Toast.tsx
- packages/primitives/src/Tooltip.tsx
- packages/primitives/src/__tests__/createStyleContext-test.tsx
- packages/primitives/src/createStyleContext.tsx
Irriterende case, men må håndteres. Nå er oppførselen mer eller mindre klin lik som den er i vanlig `styled`. Tommelfingerregelen er også lik: Hvis man bruker en av våre komponenter eller en string-primitive i `withContext` eller i `withProvider` trenger man ikke sende med `{ baseComponent: true }`.
> Rework createStyleContext to allow for using `asChild` and `consumeCss` on re-styled styled components created through `createStyleContext`

- packages/ndla-ui/src/TagSelector/TagSelector.stories.tsx
- packages/ndla-ui/src/TagSelector/TagSelector.tsx
- packages/ndla-ui/src/i18n/index.ts
- packages/ndla-ui/src/i18n/useComponentTranslations.ts
- packages/ndla-ui/src/index.ts
- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
- packages/ndla-ui/src/locale/messages-se.ts
- packages/ndla-ui/src/locale/messages-sma.ts
- packages/primitives/src/Combobox.stories.tsx
- packages/primitives/src/Combobox.tsx
- packages/primitives/src/Pagination.stories.tsx
- packages/primitives/src/Pagination.tsx
- packages/primitives/src/Tabs.tsx
- packages/primitives/src/TagsInput.stories.tsx
- packages/primitives/src/TagsInput.tsx
Dette er et forslag til hvordan vi kan holde i18next og react-i18next utenfor primitives. Tenker at vi på sikt kan vurdere hvorvidt translations egentlig hører hjemme i `ndla/ui`, men inntil videre kan de fint leve der.
> Add mandatory translations for primitives components. Expose hooks that provide them.

- packages/ndla-ui/src/Layout/LayoutItem.tsx
- packages/ndla-ui/src/Layout/OneColumn.tsx
- packages/ndla-ui/src/Layout/PageContainer.tsx
Begynner å gå veldig lei av at emotion ødelegger for panda. Dersom denne går inn er det kun to komponenter igjen som bruker emotion sin css-prop. Det klarer vi å fikse!
> Temporarily convert layout components to use panda with old styling

- packages/primitives/src/Figure.tsx
Nest siste punkt her: https://github.com/NDLANO/Issues/issues/4097
Fikses default størrelse på Figure når float er definert og ikke size
> Fix default image size on floating images

- packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx
fixes https://github.com/NDLANO/Issues/issues/4148
Problemet med skalering av kampanjeblokk er at det ble designet med tanke på bruk i vanlig side-layout og med ett bilde format. Når vi da bruker den i minNdla der vi har mindre plass pga menyen til venstre, og bildeformatet er varierende, så blir det litt vanskelig å skalere den og samtidig oppfylle designkrav. Jeg har prøvd å trikse litt og Hedvig er enig med at dette er innafor til vi har innført strengere bildekrav i ED. 
Om noen har bedre grid skills så er jeg åpen for forslag på hvordan dette kunne bli løst bedre/enklere 🙏
> new scaling for campaign block

- packages/primitives/src/ErrorMessage/ErrorMessage.stories.tsx
- packages/primitives/src/ErrorMessage/ErrorMessage.tsx
Går vekk fra vår gamle margin-baserte feilmelding. Dropper også alt av implementasjonsdetaljer, så vi heller kan styre dette fra frontendene våre. Jeg mener dette er mer forståelig enn det gamle `messages`-systemet.
> Initial pass at new Error message primitive

- packages/ndla-licenses/src/getCopyString.ts
- packages/ndla-licenses/src/licenseRights.ts
- packages/ndla-licenses/src/licenses.ts
- packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
- packages/ndla-ui/src/LicenseByline/LicenseLink.tsx
fikser [byline tekstfarge](https://trello.com/c/BV3cPn3h/40-byline-tekstfarge), [lisensversjon](https://trello.com/c/6rbpla56/42-alle-cc-lisenser-er-40-versjonstall-m%C3%A5-fremkomme-et-eller-alle-steder)
> fix: byline text and version

- packages/ndla-ui/src/Embed/ImageEmbed.tsx
- packages/primitives/src/Figure.tsx
fixes https://github.com/NDLANO/Issues/issues/4167 (https://trello.com/c/VDewZN14/58-un%C3%B8dvendig-pluss-knapp-i-mobilvisning)
fikser også: https://trello.com/c/QSAoheNI/69-feil-med-visning-av-noen-bilder
> Fix Figure padding on smaller screens for float-images + full width non float images

- packages/ndla-ui/src/FactBox/FactBox.tsx
fikser: https://trello.com/c/wk6zNMh6/36-animasjon-factbox
Fikser opp i lukke-transition i FactBox. Problemet var at max-høyde var veldig mye større enn faktisk høyde på elementet, som gjorde at transition oppleves litt forsinket. Løst ved å ta i bruk grid-triks herfra: https://dev.to/francescovetere/css-trick-transition-from-height-0-to-auto-21de
> Fix FactBox transition

- packages/primitives/src/ArticleLists.tsx
- packages/primitives/src/ArticleOrderedList.stories.tsx
Added example with letter child after last number level. Changed from marker to before.
Baserer seg litt på det som har blitt gjort før panda.
> Gir tilbake liste markering på safari. Det er ikke noe E i safari

- packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
fant denne på forsiden. ser ikke helt bra ut, men breaker det et annet sted at byline ikke har hvitt bakgrunn?
> let byline have transparent background

- packages/ndla-ui/src/Article/Article.tsx
If `contentTypeLabel` is passed in, it replaces the current text in the content type badge. The color remains the same
https://trello.com/c/1Q2xFar3/115-endring-til-overordnet-innholdstype-i-artikkelheader
> feat: bring back contentTypeLabel

- packages/primitives/src/Input.stories.tsx
- packages/primitives/src/Input.tsx
funker på firefox men ikke chrome.. noen forslag? chrome reagerer på `font-weight`, `background-color` og `font-size` endringer men ikke `color` 🤔
"fikser": https://trello.com/c/B5akWzcI/126-for-lav-kontrast-p%C3%A5-hjelpetekst
> add placeholder color

- packages/ndla-audio-search/src/AudioSearch.tsx
- packages/ndla-audio-search/src/AudioSearchForm.tsx
- packages/ndla-audio-search/src/AudioSearchInput.tsx
- packages/ndla-image-search/src/ImageSearch.tsx
- packages/ndla-video-search/src/VideoResultList.tsx
- packages/ndla-video-search/src/VideoSearch.tsx
fikser at artikkelredigerings sidene refreshes når man klikker søk i editoren hvor komponenten er brukt, EG. kampanjeblokk.
Når den blir brukt i andre forms så vil search knappen sin submit sende submit til parent form også. 
Form rundt et søke input trengs vell strengt tatt ikke så lenge man har riktig aria roler? 🤔
> Remove form wrapper on search input

- packages/ndla-ui/src/Embed/IframeEmbed.tsx
BM sjekker om vi kan gjøre dette. :heavy_check_mark: 
Dette gjør at alt av iframes kan scrolles ved behov. Klarert av Sverre, Johannes og Hedvig.
> Allow scrolling in iframe

- packages/ndla-ui/src/CodeBlock/CodeBlock.tsx
- packages/preset-panda/src/globalCss.ts
This allows us to more easily reuse the styling in ED. 
Kan testes med https://github.com/NDLANO/editorial-frontend/pull/2471
> refactor: move code block css to global css.

- packages/primitives/src/Combobox.stories.tsx
- packages/primitives/src/Combobox.tsx
`standalone` is the old default, and has no changes. `composite` allows for seamless composition with `ListItem`
> refactor: replace current variants with `standalone` and `composite`.

- packages/primitives/src/Input.stories.tsx
- packages/primitives/src/Input.tsx
- Skriver om til box-shadow istedenfor outline
- Legger til "small" variant
- Oppdaterer padding til å være riktig i henhold til designet
- Fikser dobbel padding-bug ved bruk av InputContainer
> Input refactor

- packages/ndla-ui/src/Embed/InlineTriggerButton.tsx
Fixes https://trello.com/c/QuvOfwmT/262-dobble-mellomrom-mellom-forklaringer-og-ordene-rundt
> fix: remove inline padding on InlineTriggerButton, avoiding double spacing

- packages/primitives/src/FramedContent.tsx
Fixes https://trello.com/c/Z6BGV4nJ/261-et-bilde-i-tekstboksen-faller-utenfor-tekstboksen
> fix: apply overflow: "hidden" to framed content to ensure floated content remains inside

- packages/preset-panda/src/plugins/__tests__/forwardCssProp-test.tsx
- packages/preset-panda/src/plugins/forwardCssPropPlugin.ts
- packages/styled-system/src/jsx/factory.js
Testen som er lagt til ville feilet før denne endringen ble gjort. Har kjent på dette to ganger i ED, og aldri i ndla-frontend. Fortsatt fint å fikse.
> fix: ensure that re-styled complex components that are aschilded onto a non-complex component still consumes its css prop.

- packages/preset-panda/src/globalCss.ts
- packages/primitives/src/ExpandableBox.tsx
Stilen skal anvendes likt uavhengig av hva vi faktisk rendrer.
> feat: support `asChild` for both `ExpandableBox` and `ExpandableBoxSummary`

- packages/primitives/src/Card/Card.tsx
> fix: only show intense background on hover

- packages/primitives/src/Combobox.stories.tsx
- packages/primitives/src/Combobox.tsx
Tenker å bruke i ED, men sikkert fint å ha i ndla-frontend også!
> feat: split combobox variant into `context` and `variant`, allowing for less styling when composing with other components

- packages/ndla-ui/src/locale/messages-en.ts
- packages/ndla-ui/src/locale/messages-nb.ts
- packages/ndla-ui/src/locale/messages-nn.ts
Synes det var litt rart, men NDLA meiner det dekker både at vi bruker åpen kildekode og at koden vår er åpen. Og dei er norsklærerar så vi får stole på det.
> Ønske fra kommunikasjon!

- packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx
Problemet oppstår når byline går over 2 linjer og det er ikke nok plass til knappen. Flytter knappen under byline-teksten og la til litt margin (visuelt godkjent av Hedvig)
[trello](https://trello.com/c/b0DxBgUA/304-synstolketknappen-ser-litt-tilfeldig-plassert-ut)
> move visually interpreted button

- packages/safelink/src/SafeLinkButton.tsx
- packages/safelink/src/SafeLinkIconButton.tsx
Fører til en typefeil i ndla-frontend, men det kan vi nok rydde opp i. Dette er mer riktig.
> fix: do not define `to` as a string in SafeLink buttons

- packages/ndla-ui/src/LinkBlock/LinkBlock.tsx
Vi har vel mye større sjanse for å få brukere fra norge enn fra andre plasser.
Ideelt sett så burde vi sikkert droppet serverside rendering for alle datoer, men kanskje litt for mye hassle?
> Use `CET` when rendering date instead of `UTC`

- packages/ndla-ui/src/AudioPlayer/Controls.tsx
Denne arver `Field`-attributter fra `Field`-et som wrapper hele artikkel-editoren, som er litt dumt
> fix: wrap controls select in field to work properly with nested fields

- packages/ndla-image-search/package.json
- packages/ndla-image-search/src/ImageMeta.tsx
- packages/ndla-image-search/src/PreviewImage.tsx
- packages/util/src/__tests__/humanFileSize-test.ts
- packages/util/src/humanFileSize.ts
- packages/util/src/index.ts
- yarn.lock
Erstatter pretty-bytes med vår egen implementasjon. Synes det gir mer mening å lene seg på Intl her nå som det har god støtte. Se stackoverflow-lenken dersom du lurer på hvorfor dette ikke bare er en tynn wrapper rundt Intl.
Fixes https://github.com/NDLANO/Issues/issues/4220
> chore: replace pretty-bytes with our own implementation

- packages/preset-panda/src/plugins/__tests__/forwardCssProp-test.tsx
- packages/preset-panda/src/plugins/forwardCssPropPlugin.ts
- packages/styled-system/src/jsx/factory.js
Fant visst en liten bug mens jeg fiklet med noe greier i ndla-frontend!
> fix: explicitly setting consumeCss to false should not consume css

- packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx
Enkel fiks på feil som monsido plukket opp
> fix: do not use empty strings as title or aria-label in brightcove embed

- packages/ndla-ui/src/FactBox/FactBox.tsx
Ser ut som at tabbing ikke fungerer helt som det skal med FactBox nå.
> fix: support both react 18 and react 19 when setting inertness of FactBox

- packages/ndla-ui/src/ContentTypeBlockQuote/ContentTypeBlockQuote.tsx
- packages/ndla-ui/src/ContentTypeFramedContent/ContentTypeFramedContent.tsx
https://trello.com/c/XrulHWyQ/1238-forh%C3%A5ndsvisning-i-ed-viser-ikke-farge-p%C3%A5-tekstboks-hvis-denne-er-satt
Jeg syntes det gir mening at vi viser en default-farge når variant er satt til colored og ingen contentType eksisterer 🤔
> Show colored variant when variant is colored and contentType does not exist

- packages/primitives/src/Checkbox.tsx
> fix: only show Checkbox focus-ring when focus-visible is true

- packages/editor-components/src/hooks/useEditorPopover.ts
- packages/editor/src/playground.stories.tsx
Litt vanskelig å få til interop mellom Slate og alt utenfor slate. Dette fikser et problem som oppsto når man brukte tastatur i richtext-toolbaren.
> fix: make `useEditorPopover` less greedy when the Enter key is pressed

- packages/editor-components/src/index.ts
- packages/editor-components/src/utils/getClosestEditor.ts
LinkPlugin i ED møter på et problem dersom en side har flere slate-editors. Hvis man bruker `document.querySelector` vil man automatisk plukke den første editoren en møter på, ikke den man nødvendigvis står i nå.
> feat: getClosestEditor

- packages/editor-components/src/hooks/useEditorPopover.ts
- packages/editor/src/playground.stories.tsx
I og med at man kan steppe inn og ut av inline-elementer er det ingen grunn til å ignorere kanter. Kunne eventuelt vært en option?
> fix: allow edges when using `useEditorPopover`

- packages/primitives/src/ArticleLists.tsx
- packages/primitives/src/ArticleOrderedList.stories.tsx
- packages/primitives/src/ArticleUnorderedList.stories.tsx
Ikke veldig fan av måten å gjøre dette på, men tror vi kanskje må force stylingen for at vi ikke skal overskrides av et liste element høyere i dom'en. 
Det her tatt utgangspunkt i hvordan vi gjorde det tidligere før nytt design system.  Jeg kan flette sammen logikken om det er ønskelig men jeg synes det var mer ryddig å ha det utenfor.
> Forcing the lists in articles to follow specific style build up

- packages/util/src/__tests__/arrayHelpers-test.ts
- packages/util/src/arrayHelpers.ts
- packages/util/src/index.ts
Erstatter brorparten av lodash-bruken vår i ndla-frontend. Prøvde meg originalt på `es-toolkit`, men det viste seg å være litt for nytt til at vi kunne bruke det. De fleste av disse funksjonene burde være greie nok å forstå seg på. I fremtiden bør vi nok ta en fot i bakken om hva som er verdt å ta eierskap over. Hvis vi implementerer disse selv dropper vi en ganske stor chunk av bundle-størrelsen vår.
> feat: add array helpers

- packages/editor/src/__tests__/createSlate-test.ts
- packages/editor/src/core/createPlugin.ts
- packages/editor/src/core/index.ts
- packages/editor/src/editor/createSlate.ts
- packages/editor/src/index.ts
Sitter og funderer på om det er lurt å ta dette enda litt videre, og tillate vanlig normaliseringslogikk også. Dette kommer til å brukes i ED til å sette ID'er på alle blokknoder uten at vi trenger å lagre ID'ene på server.
> feat: add possibility of normalizing initial editor value before slate has mounted

- packages/editor/src/__tests__/createSlate-test.ts
- packages/editor/src/core/createPlugin.ts
- packages/editor/src/core/index.ts
Ser ut som at jeg har bommet på typene for `override`, så det var aldri mulig å sende det inn. Dette legger til støtte for det, og også støtte for å override `normalizeInitialValue`
> fix: make `override` option work properly when using `configure`. Support overriding `normalizeInitialValue`

- packages/editor/src/plugins/break/breakPlugin.ts
- packages/editor/src/plugins/break/breakTypes.ts
- packages/editor/src/types/index.ts
Begrenser hvor man har lov til å sette inn br-elementer basert på hva parenten er. Tipper dette kommer til å være section, uu-disclaimer, framed-content, details, og aside i ED.
> feat: restrict valid break parents

- packages/editor/src/plugins/break/breakPlugin.ts
> fix: insert break if validBreakParents is empty or if the node parent is not a valid break parent

- packages/editor/src/plugins/break/breakSerializer.ts
Dette sørger for at `\n` ikke endres til `<br />` ved serialisering i summary og blockquote
> fix: do not allow for expanding soft breaks in blockquote and summary by default

- packages/editor/src/editor/createSlate.ts
Tar inspirasjon fra hvordan Plate har gjort ting.
Dette erstatter følgende kodeblokk i `RichTextEditor`
```tsx
useEffect(() => {
Editor.normalize(editor, { force: true });
editor.history = { undos: [], redos: [] };
}, [])
```
> feat: support normalizing the initial value

- packages/editor/src/editor/createSlate.ts
- packages/editor/src/types/index.ts
Erstatter en `useEffect` som kjøres når vi lagrer/resetter artikler. Dette fjerner litt boilerplate fra ED, samt at det lar oss kjøre `normalizeInitialValue` etter at man har lagret en artikkel!
> feat: add ability to reinitialize editor with a new value

- packages/ndla-ui/src/FactBox/FactBox.tsx
Litt uheldig men ingen vei rundt
> fix: ensure that the slate editor does not focus the Factbox button

- packages/editor/src/__tests__/createSlate-test.ts
- packages/editor/src/core/createPlugin.ts
- packages/editor/src/editor/createSlate.ts
- packages/editor/src/types/index.ts
Skal brukes til å lete etter elementer som ikke støttes av editoren. Må komme på noe annet lurt for manglende renderers.
> feat: add an editor function that asserts whether the editor supports a specific type

- .github/workflows/ci.yml
- package.json
- packages/ndla-scripts/package.json
- yarn.lock
Ting har nå begynt å kreve at vi kjører en nyere node-versjon enn vi gjør, så tenker det er like greit å ta hoppet til 22 nå. har byttet over til 22 i vercel, men bare for frontend-packages.
> chore: upgrade to node 22

- packages/ndla-scripts/package.json
- packages/ndla-scripts/src/scripts/vercel-github.js
- yarn.lock
Usikker på om vi egentlig trenger det
> chore: drop cross-spawn-promise. It's not maintained

- packages/ndla-ui/src/FactBox/FactBox.tsx
Ting burde ikke overflowe ut av FactBox når den først rendres. Feilen kan ses på eksempel i master.
> fix: set overflowHidden initial value based on defaultOpen

- packages/preset-panda/README.md
- packages/preset-panda/src/globalCss.ts
- packages/preset-panda/src/plugins/README.md
- packages/primitives/README.md
Bare så jeg ikke glemmer at jeg har skrevet det!
> docs: add initial suggestions for panda and primitives documentation

- packages/editor/src/plugins/paragraph/__tests__/paragraphNormalizer-test.ts
- packages/editor/src/plugins/paragraph/paragraphPlugin.ts
Fixes https://trello.com/c/fnSZ5s7J/1233-autoslette-whitespace-i-bakkant-og-forkant-av-avsnitt-n%C3%A5r-man-lagrer-artikkel-i-ed
Litt usikker på hvor fornøyd jeg er med dette. I all hovedsak fører det til at man får opp "artikkelen er endret"-varselen etter at man har lagret en artikkel, da det ikke er så kult å disable whitespace på slutten av en setning mens man skriver den. Man kan eventuelt gjøre dette under deserialisering, men det blir nok en del mer komplekst. Hva tenker folket? 
Et annet alternativ vi kan utforske er å normalisere før vi lagrer. Da kunne vi hatt normaliseringsregler som kun ble kjørt når en artikkel ble lastet inn  og lagret, for eksempel. 
Kan testes ved å linke inn i ED.
> feat: trim leading and trailing whitespace in paragraphs

- packages/preset-panda/src/typography.stories.tsx
Savna en plass der code-taggen blei vist så laga en liten story
> Adds story to display standard marks

- packages/article-converter/package.json
- packages/core/package.json
- packages/editor-components/package.json
- packages/editor/package.json
- packages/hooks/package.json
- packages/icons/package.json
- packages/ndla-audio-search/package.json
- packages/ndla-error-reporter/package.json
- packages/ndla-image-search/package.json
- packages/ndla-licenses/package.json
- packages/ndla-tracker/package.json
- packages/ndla-ui/package.json
- packages/ndla-video-search/package.json
- packages/preset-panda/package.json
- packages/primitives/package.json
- packages/safelink/package.json
- packages/styled-system/package.json
- packages/util/package.json
Jeg har slått hodet i veggen med en bug som viste seg å være esm/cjs-interop. Tror det er på tide at vi går helt over til ESM nå, men har lagt til rette for at man fortsatt kan kjøre CJS ved behov. 
En kan anse dette som breaking, men vil tro de aller fleste semi-moderne kodebaser tåler det.
> chore: convert to exports field in package.json
