NDLANO/frontend-packages

README.md, package.json
See storybook at: https://NDLANO.github.io/frontend-packages/
=> Add script for deploying storybook to github pages

packages/ndla-licenses/src/licenses.js
=> new copy on bysa

packages/designmanual/stories/article/LicenseExample.jsx, packages/designmanual/stories/basic-styles.jsx, packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/concepts.js, packages/designmanual/stories/helpers.jsx, packages/designmanual/stories/molecules/footers.jsx, packages/designmanual/stories/molecules/resources.jsx, packages/designmanual/stories/molecules/tabs.jsx, packages/designmanual/stories/simple-components.jsx, packages/designmanual/stories/welcome.jsx, packages/ndla-ui/src/footer/Footer.jsx
- Textual changes design manual
- Anchor navigation in design manual
- Add space between label and name in footer editor
=> Textual changes design manual and minor change in ndla-ui

packages/designmanual/stories/basic-styles.jsx, packages/ndla-ui/src/global/components/component.tables.scss
- Fixed misplaced shadow and some styling adjustements on shadow
- Added example for use of colspan and rowspan 
- Styling adjustment for rowspan
=> Styling adjustments tables

.gitignore, packages/designmanual/stories/basic-styles.jsx, packages/ndla-ui/src/global/components/component.article.scss, packages/ndla-ui/src/global/elements/_elements.audio.scss, packages/ndla-ui/src/global/elements/_elements.lists.scss, packages/ndla-ui/src/main.scss
=> Small styling adjustments

packages/ndla-ui/src/global/components/component.aside.scss
- Fixed position of expand button
- Fixed :after element blocking for interactions
No breaking changes
=> C-aside fixes

packages/designmanual/stories/simple-components.jsx, packages/ndla-article-scripts/src/__tests__/iframeScripts-test.js, packages/ndla-article-scripts/src/detailsScript.js, packages/ndla-article-scripts/src/domHelpers.js, packages/ndla-article-scripts/src/iframeScripts.js, packages/ndla-article-scripts/src/index.js, packages/ndla-ui/src/global/elements/_elements.details.scss
- Default aspect ratio on iframe script
- Styling adjustments details BREAKING CHANGES: no content wrapper should be in the markup (section, div etc.)
- On toggle handler details. Resizes videos inside of details. init of toggle script in initArticleScripts(). Available function for removing event handlers
- Designmanual page for details
=> Adjustments iframescript + adjustments details component

packages/ndla-licenses/src/licenses.js, packages/ndla-ui/src/Article/ArticleByline.jsx, packages/ndla-ui/src/global/components/component.aside.scss
- z-index fix for aside. buttons was blocked by floating elements
- Fix license abbreviation formatting in ArticleByLine. 'CC-BY-NC-ND' -> 'CC BY-NC-ND'
=> Aside fix + abbreviation fix ArticleByLine

packages/designmanual/stories/simple-components.jsx
- No license on youtube (in example)
- Textual changes
=> Design manual: Embedded page changes

packages/designmanual/stories/article/FootnotesExample.jsx, packages/designmanual/stories/simple-components.jsx, packages/ndla-article-scripts/src/footnoteScripts.js, packages/ndla-article-scripts/src/index.js, packages/ndla-ui/src/global/components/component.footnotes.scss
* Animation on click
* Mark referenced text on click
* larger clickboxes
* Hover, active and focus styling
BREAKING CHANGES: new markup for footnotes. ref. example
=> Adjustments on footnotes

packages/designmanual/stories/article/LicenseExample.jsx
NB! Text must also be changed in ndla-frontend
=> text change on license box button

packages/designmanual/stories/article/ArticleLoader.jsx, packages/designmanual/stories/pages/ArticleAdditional.jsx, packages/designmanual/stories/pages/ArticleExercise.jsx, packages/designmanual/stories/pages/ArticleLearningmaterial.jsx, packages/designmanual/stories/pages/index.jsx
* All articles (fagstoff, oppgaver og aktiviteter etc.)  should contain launch pad.
* Hovedemne should not contain launch pad.
* Underemne should contain launch pad.
=> fix where launch pad/resources should be visible

packages/designmanual/dummydata/mockResources.js, packages/designmanual/stories/article/RelatedArticleListExample.jsx, packages/designmanual/stories/collated-components.jsx, packages/ndla-ui/src/ContentTypeBadge/component.content-type-badge.scss, packages/ndla-ui/src/RelatedArticleList/RelatedArticleList.jsx, packages/ndla-ui/src/RelatedArticleList/component.related-articles.scss
* Support from more than 2 related articles with expand button
* Styling adjustments
=> Expand button related articles

packages/designmanual/dummydata/mockSearch.js, packages/designmanual/stories/molecules/mastheads.jsx, packages/ndla-ui/src/Search/ContentTypeResult.jsx, packages/ndla-ui/src/Search/SearchField.jsx, packages/ndla-ui/src/Search/component.content-type-result.scss, packages/ndla-ui/src/Search/component.search-field.scss, packages/ndla-ui/src/global/components/component.topic-menu.scss, packages/ndla-ui/src/topicMenu/TopicMenu.jsx
- Styling adjustments on search autocomplete and content type result (both used in autocomplete and in topic menu). 
- Placeholder for no hit
BREAKING CHANGES:  some new static messages/translations used and rename of allResultLabel to allResultButtonText
=> styling adjustments on autocomplete and content type result

packages/designmanual/stories/basic-styles.jsx, packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/molecules/footers.jsx, packages/designmanual/stories/simple-components.jsx, packages/ndla-ui/src/Aside/component.aside.scss, packages/ndla-ui/src/RelatedArticleList/RelatedArticleList.jsx, packages/ndla-ui/src/RelatedArticleList/component.related-articles.scss
- Related articles adjustments
- Textual changes design manual
- Fix semantics aside, and margin on first-child. BREAKING CHANGES: First header level should be h1 instead of h2
=> Small fixes

packages/designmanual/stories/pages/BetaFrontpage.jsx, packages/ndla-ui/src/Article/component.article.scss, packages/ndla-ui/src/InfoBox/InfoBox.jsx, packages/ndla-ui/src/InfoBox/component.info-box.scss, packages/ndla-ui/src/InfoBox/index.js, packages/ndla-ui/src/global/objects/objects.lists.scss, packages/ndla-ui/src/index.js, packages/ndla-ui/src/main.scss
- Added infobox on beta front page
- Textual changes
- Small styling adjustment on list. BREAKING CHANGES: added class o-list--no-margin-top
=> Beta frontpage infobox and adjustments

packages/designmanual/stories/molecules/resources.jsx, packages/ndla-ui/src/ResourceGroup/ResourceGroup.jsx, packages/ndla-ui/src/ResourceGroup/ResourceList.jsx, packages/ndla-ui/src/ResourceGroup/component.topic-resource.scss
- Remove show more, show less button.
- design adjustments on mobile
=> Launchpad adjustments

packages/designmanual/stories/article/RelatedArticleListExample.jsx, packages/designmanual/stories/collated-components.jsx, packages/ndla-ui/src/Frontpage/FrontpageHighlighted.jsx, packages/ndla-ui/src/Frontpage/component.frontpage-highlighted.scss, packages/ndla-ui/src/InfoWidget/InfoWidget.jsx, packages/ndla-ui/src/InfoWidget/component.info-widget.scss, packages/ndla-ui/src/RelatedArticleList/RelatedArticleList.jsx, packages/ndla-ui/src/RelatedArticleList/component.related-articles.scss, packages/ndla-ui/src/ResourceGroup/component.resource-group.scss, packages/ndla-ui/src/ResourcesWrapper/ResourcesTitle.jsx, packages/ndla-ui/src/ResourcesWrapper/component.resources.scss, packages/ndla-ui/src/SectionHeading/SectionHeading.jsx, packages/ndla-ui/src/SectionHeading/component.section-heading.scss, packages/ndla-ui/src/SectionHeading/index.js, packages/ndla-ui/src/Subject/Subject.jsx, packages/ndla-ui/src/Subject/SubjectAbout.jsx, packages/ndla-ui/src/Subject/SubjectArchive.jsx, packages/ndla-ui/src/Subject/component.subject-about.scss, packages/ndla-ui/src/Subject/component.subject-archive.scss, packages/ndla-ui/src/Subject/component.subject.scss, packages/ndla-ui/src/main.scss
- New design on external related articles
- Section heading common compontent and design adjustments
=> Section headings and external related article

packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/molecules/TwoColumnsExample.jsx, packages/designmanual/stories/molecules/resources.jsx, packages/designmanual/stories/pages/ArticleAdditional.jsx, packages/designmanual/stories/pages/ArticleAssessmentResource.jsx, packages/designmanual/stories/pages/ArticleExercise.jsx, packages/designmanual/stories/pages/ArticleExternalLearningResource.jsx, packages/designmanual/stories/pages/ArticleLearningmaterial.jsx, packages/designmanual/stories/pages/ArticleSourceMaterial.jsx, packages/ndla-ui/src/ResourcesWrapper/ResourcesTopicTitle.jsx, packages/ndla-ui/src/ResourcesWrapper/component.resources.scss, packages/ndla-ui/src/ResourcesWrapper/index.js, packages/ndla-ui/src/index.js
- Launch pad subject heading.
- Topic shortcuts label text prop.
- Removed wrong description in designmanual about launch pad
=> Launchpad heading + static text fix

packages/designmanual/stories/article/FigureWithLicense.jsx, packages/designmanual/stories/simple-components.jsx
- Removed link from embedded examples
- Added embedded float left and right examples
=> Cleanup Embedded content examples

packages/ndla-ui/src/RelatedArticleList/RelatedArticleList.jsx
resolves https://github.com/NDLANO/Issues/issues/1057
requires https://github.com/NDLANO/article-converter/pull/94
=> Added support for dangerouslySetInnerHTML in RelatedArticleList

packages/designmanual/stories/basic-styles.jsx, packages/ndla-ui/src/global/tools/tools.functions.scss
Added support for lang="zh" which should be used on Chinese text when we cant seperate it into traditional or simple chinese. (lang=zh-Hant, zh-Hans)
=> Chinese subject

packages/designmanual/stories/pages/ArticleAdditional.jsx, packages/ndla-ui/src/Search/ToggleSearchButton.jsx, packages/ndla-ui/src/common/ClickToggle.jsx
• Bugfix for search in Masthead (minor changes to ClickToggle component)
• Import error ArticleBylineExample in ArticleAdditional.jsx
=> fixed bug on seach masthead and article example

packages/ndla-tabs/src/FilterTabs.jsx
Required by: https://github.com/NDLANO/Issues/issues/1117
=> Hotfix: Search page: missing setState (breaks), prop change fix

packages/designmanual/stories/pages/SearchPageExample.jsx, packages/ndla-tabs/src/FilterTabs.jsx
Required by https://github.com/NDLANO/Issues/issues/1117
=> Fix searchpage example and filtertabs

packages/designmanual/stories/beta.jsx, packages/designmanual/stories/molecules/BetaNotificationExample.jsx, packages/ndla-ui/src/Beta/BetaNotification.jsx, packages/ndla-ui/src/Beta/component.beta-notification.scss, packages/ndla-ui/src/Beta/index.js, packages/ndla-ui/src/index.js, packages/ndla-ui/src/main.scss
Simple message for users while in Beta.
Note: Remember if users has accepted (prob via LocalStorage?)
=> Info box for beta-pages

packages/ndla-article-scripts/src/relatedArticlesToggle.js, packages/ndla-ui/src/Hero/component.hero.scss, packages/ndla-ui/src/Masthead/component.masthead.scss, packages/ndla-ui/src/RelatedArticleList/component.related-articles.scss, packages/ndla-ui/src/global/utilities/utilities.shame.scss
• IE Fix for expand/collapse js-script
• Moved ZenDesk button 'Spør NDLA' to float on right side
• Fix for IE Header height
• Fix for IE Scroll Event listener (Caused Breadcrumbs not to show in header on scroll)
=> Ie hide collapse fix

packages/designmanual/stories/article/ArticleLoader.jsx, packages/designmanual/stories/molecules/mastheads.jsx, packages/designmanual/stories/organisms/CompetenceGoalsExample.jsx, packages/designmanual/stories/pages/ArticleAdditional.jsx, packages/designmanual/stories/pages/ArticleAssessmentResource.jsx, packages/designmanual/stories/pages/ArticleExercise.jsx, packages/designmanual/stories/pages/ArticleExternalLearningResource.jsx, packages/designmanual/stories/pages/ArticleLearningmaterial.jsx, packages/designmanual/stories/pages/ArticleSourceMaterial.jsx, packages/designmanual/stories/pages/SearchPageExample.jsx, packages/designmanual/stories/search.js, packages/ndla-ui/src/Article/Article.jsx, packages/ndla-ui/src/Article/component.article.scss, packages/ndla-ui/src/CompetenceGoals/CompetenceGoals.jsx, packages/ndla-ui/src/CompetenceGoals/component.competence-goals.scss, packages/ndla-ui/src/CompetenceGoals/index.js, packages/ndla-ui/src/Dialog/component.dialog.scss, packages/ndla-ui/src/Search/SearchPage.jsx, packages/ndla-ui/src/Search/SearchResult.jsx, packages/ndla-ui/src/Search/component.search-result.scss, packages/ndla-ui/src/TopicMenu/TopicMenu.jsx, packages/ndla-ui/src/index.js
Competence goals fixes and also included on searchpage.
Note: Will require props / messages to work
=> Compentence goals new

packages/designmanual/stories/organisms/CompetenceGoalsExample.jsx, packages/ndla-tabs/src/FilterTabs.jsx, packages/ndla-ui/src/Article/Article.jsx, packages/ndla-ui/src/Article/ArticleByline.jsx, packages/ndla-ui/src/CompetenceGoals/CompetenceGoals.jsx, packages/ndla-ui/src/CompetenceGoals/component.competence-goals.scss, packages/ndla-ui/src/Dialog/component.dialog.scss, packages/ndla-ui/src/Hero/component.hero.scss, packages/ndla-ui/src/ResourceGroup/ResourceList.jsx, packages/ndla-ui/src/ResourcesWrapper/ResourcesTopicTitle.jsx, packages/ndla-ui/src/Tooltip/Tooltip.jsx, packages/ndla-ui/src/TopicIntroductionList/TopicIntroductionList.jsx, packages/ndla-ui/src/TopicIntroductionList/TopicShortcutItem.jsx, packages/ndla-ui/src/common/ClickToggle.jsx, packages/ndla-ui/src/global/elements/_elements.input.scss, packages/ndla-ui/src/global/elements/_elements.page.scss, packages/ndla-ui/src/global/objects/objects.content.scss
• Justeringer av modalboks størrelser for competenceGoals og lisensboks.
• Fiks for FilterTabs (utregninger av kollapse i dropdown funket ikke når man gikk fra liten til stor skjerm).
• Auto scroll til content av artikler på mobil.
• Footer og input css fix for IE
• ClickToggle/Dialog fikses og la ResourcesTopicTitle.jsx bruke ClickToggle til å håndtere modal open/close states.
=> css/qa and filterTab fix

packages/ndla-ui/src/Footer/Footer.jsx, packages/ndla-ui/src/Footer/privacyTexts.js, packages/ndla-ui/src/Footer/privacy_nb.js, packages/ndla-ui/src/Footer/privacy_nn.js, packages/ndla-ui/src/Frontpage/component.frontpage-film.scss
=> privacyText nn + css changes frontpage

packages/ndla-tabs/package.json, packages/ndla-tabs/src/Tabs.jsx, packages/ndla-ui/package.json, packages/ndla-ui/src/Dialog/Dialog.jsx, packages/ndla-ui/src/common/ClickToggle.jsx, yarn.lock
- Solves issue described in https://github.com/NDLANO/Issues/issues/1218
- Tab improvement (better a11y)
=> ClickToggle refactoring - improved tabbing in dialogs

packages/ndla-licenses/src/licenses.js
A-feil.
Oppdaterte CC lenker til versjon 4
=> updated links (A-feil)

packages/designmanual/stories/LanguageWrapper/LanguageSelectorNonMessages.jsx, packages/designmanual/stories/LanguageWrapper/index.js, packages/designmanual/stories/licenses.js
Added language selector to licenses in storybook
=> Storybook langselector licenses

packages/designmanual/dummydata/index.js, packages/designmanual/dummydata/mockDownloadArticleText.js, packages/designmanual/stories/article/LicenseBox.jsx, packages/ndla-ui/src/Button/CopyButton.jsx, packages/ndla-ui/src/MediaList/component.medialist.scss, packages/ndla-ui/src/global/utilities/mixin_icons.scss, packages/ndla-ui/src/global/utilities/utilities.shame.scss, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js, packages/ndla-util/README.md, packages/ndla-util/package.json, packages/ndla-util/src/downloadPdf.js, packages/ndla-util/src/index.js
• Example for code to download text as a PDF-file.
• <CopyButton /> Ref fix
• Styling fixes and messages in Licensebox example
=> Download text licensebox

packages/designmanual/stories/ComponentInfo.jsx, packages/designmanual/stories/produksjonssystem/AccordionExample.jsx, packages/designmanual/stories/produksjonssystem/index.js, packages/designmanual/stories/wrappers/StoryBody.jsx, packages/ndla-accordion/README.md, packages/ndla-accordion/package.json, packages/ndla-accordion/src/Accordion.js, packages/ndla-accordion/src/index.js, packages/ndla-core/src/fonts.js, packages/ndla-core/src/spacing.js
• Accordion + example and documentation
• Added some styling variables in ndla-core
• Name fix for Storybody in designmanual
=> Accordion component

packages/designmanual/stories/article/FigureWithLicense.jsx, packages/ndla-core/scss/global/settings/settings.colors.scss, packages/ndla-core/scss/global/utilities/utilities.grids.scss, packages/ndla-core/scss/global/utilities/utilities.helpers.scss, packages/ndla-ui/src/Article/component.article.scss, packages/ndla-ui/src/CompetenceGoals/component.competence-goals.scss, packages/ndla-ui/src/Filter/component.filter.scss, packages/ndla-ui/src/ResourceGroup/component.resource-group.scss, packages/ndla-ui/src/ResourceGroup/component.topic-resource.scss, packages/ndla-ui/src/Subject/component.subject-new-content.scss, packages/ndla-ui/src/TopicIntroductionList/component.topic-introduction.scss
Styling and fontsizes adjustments
=> styling fixes

packages/ndla-tabs/package.json, packages/ndla-tabs/src/FilterTabs.jsx, yarn.lock
Fixes prop handling issue in current production release. Required to resolve https://github.com/NDLANO/Issues/issues/1317
- Refactors component update and props handling causing IE 11 to crash
- Does not fix CSS issue
=> IE11 ndla-tabs fix

packages/ndla-editor/src/SlateBlockMenu.js
=> Slateblock fixes

packages/ndla-licenses/src/__tests__/licenses-test.js, packages/ndla-licenses/src/licenses.js
Oppdaterte navn i henhold til bestilling. Litt språkvask på nynorsk.
=> Updated names according to spesification

packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Fixes NDLANO/issues#1418
* Added missing text
=> Added missing text

packages/ndla-button/scss/button.scss, packages/ndla-core/scss/global/elements/_elements.footer.scss, packages/ndla-ui/src/Hero/component.hero.scss, packages/ndla-ui/src/MediaList/component.medialist.scss, packages/ndla-ui/src/Subject/component.subject-archive.scss, packages/ndla-ui/src/Subject/component.subject-header.scss, packages/ndla-ui/src/Subject/component.subject.scss, packages/ndla-ui/src/Tooltip/Tooltip.jsx, packages/ndla-ui/src/TopicIntroductionList/component.topic-shortcuts.scss, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
• IE11 fix tooltip
• Button styling
• IE11 Breadcrumb position fix
• IE11 usecontent image size fix
• Removed Archive button from subjectpages (with CSS, will be available later)
• Missing messages
=> IE11 bugfixes and styling + button styling fix

packages/ndla-editor/src/ItemName.js, packages/ndla-editor/src/Structure.js
Some small changes to make Structure-component usable in taxonomy-editor.
=> Reusable structure

packages/designmanual/stories/article/AudioExample.jsx, packages/designmanual/stories/article/FigureWithLicense.jsx, packages/designmanual/stories/article/LicenseBox.jsx, packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/simple-components.jsx, packages/ndla-audio-search/src/AudioSearchResult.js, packages/ndla-licenses/src/licenses.js, packages/ndla-notion/src/NotionDialogLicenses.js, packages/ndla-ui/src/Article/Article.jsx, packages/ndla-ui/src/Figure/Figure.js, packages/ndla-ui/src/Figure/FigureFullscreenDialog.js, packages/ndla-ui/src/Figure/FigureLicense.js, packages/ndla-ui/src/Figure/FigureLicenseDialog.js, packages/ndla-ui/src/LicenseByline/LicenseByline.jsx, packages/ndla-ui/src/LicenseByline/LicenseIconDescriptionList.jsx, packages/ndla-ui/src/MediaList/MediaList.jsx, packages/ndla-video-search/src/VideoSearchResultBrightcove.jsx
Connected to:
- https://github.com/NDLANO/ndla-frontend/pull/299
- https://github.com/NDLANO/article-converter/pull/118
=> Fixes translation on licenses #1486

packages/ndla-ui/src/FileList/File.jsx
Added target="_blank" to open file in new tab.
=> #1453 Add property to open new tab

packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Trello: https://trello.com/c/kSN6lMdi/672-feil-visning-av-forfattere
=> label corrections

packages/ndla-video-search/src/VideoSearch.jsx, packages/ndla-video-search/src/VideoSearchList.jsx, packages/ndla-video-search/src/VideoSearchResultYouTube.jsx
- don't save the search to state if the selected type has changed
- simplify the key property so it can't fail in the future
=> fix: don't save search if selected has changed

packages/ndla-ui/src/Table/component.tables.scss
Trello: https://trello.com/c/vyFgWaQY/802-tabell-i-boks-sladdes
Husk å flytte trellokort når klar til test
=> table in details size fix

packages/ndla-modal/src/Backdrop.js, packages/ndla-modal/src/Modal.js, packages/ndla-modal/src/index.js
Also moves Backdrop to a separate component
=> Fix Safari backdrop issue 

packages/ndla-ui/src/Table/component.tables.scss, packages/ndla-ui/src/TopicMenu/SubtopicLinkList.jsx, packages/ndla-ui/src/TopicMenu/TopicMenu.jsx, packages/ndla-ui/src/TopicMenu/component.topic-menu.scss, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
• Hover/Focus states i meny
• Lukk menu hvis på fagforside og trykker på Fagforside lenken
=> Menu focus and close on topic button

packages/ndla-ui/src/AudioPlayer/component.audio-player.scss
https://trello.com/c/Xs8j5jle/199-bl%C3%A5-lenkefarge-p%C3%A5-lydavspiller-ikonet
=> fix: typo in sass selector for audioplayer speech

packages/ndla-ui/src/AudioPlayer/AudioPlayer.js, packages/ndla-ui/src/AudioPlayer/component.audio-player.scss
https://trello.com/c/cIZ2lP11/593-inkonsekvent-spoling-av-lyd-titler-alle-lydtitler-fjernes
=> chore: remove unused typelabel from audioplayer

packages/designmanual/stories/article/FigureCaptionExample.js, packages/designmanual/stories/article/FigureImage.jsx, packages/designmanual/stories/simple-components.jsx
https://trello.com/c/nfQLoiJB/100-eksterne-lenker-p%C3%A5-bilde
=> chore: Added example for external link on image figcaption

packages/designmanual/stories/produksjonssystem/FileListEditorExample.jsx, packages/ndla-editor/src/FileListEditor.js, packages/ndla-editor/src/FileNameInput.js, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
- move out all editing of file array to props functions
- Split ut component
=> Filelist refactoring

packages/designmanual/stories/molecules/breadcrumbs.jsx, packages/designmanual/stories/molecules/mastheads.jsx, packages/ndla-ui/src/Breadcrumb/BreadcrumbBlock.jsx, packages/ndla-ui/src/Breadcrumb/BreadcrumbItem.jsx, packages/ndla-ui/src/Breadcrumb/component.breadcrumb-block.scss, packages/ndla-ui/src/Breadcrumb/useWindowSize.js, packages/ndla-ui/src/Masthead/component.masthead.scss
• Prop to BreadCrumb in header to calculate max-width and shorten links/name
Trello: https://trello.com/c/V5ZtEafw/823-br%C3%B8dsmule-kan-bli-for-lang-i-sticky-header
=> Controll Breadcrumb in sticky header

packages/ndla-editor/src/FileListEditor.js, packages/ndla-editor/src/FileNameInput.js
Pass ref to FileNameInput
Trello: https://trello.com/c/pRMZZGAA/150-filer-feil-ved-visning-i-ed
=> fix: revert ref for FileNameInput

packages/ndla-ui/src/Figure/component.figure.scss
• Remove blocking width/left/right for .c-figure .u-float-full classes
=> Fix: dont blocking full width for figure images

packages/carousel/src/Carousel.tsx, packages/carousel/src/CarouselAutosize.tsx, packages/ndla-ui/src/Frontpage/FrontpageFilm.jsx, packages/ndla-ui/src/Frontpage/component.frontpage-film.scss, packages/ndla-ui/src/Subject/SubjectCarousel.jsx
• Fixes for carousel center alignment
• Fix for duplicated className component.frontpage-film.scss
=> Fix carousel

packages/designmanual/stories/produksjonssystem/AccordionExample.jsx, packages/ndla-accordion/src/AccordionPanel.js
• Trenger denne for å få riktig bredde på innhold i redigeringspanel i ED.
=> Custom sidepadding as prop to Accordion

packages/core/scss/global/elements/_elements.lists.scss
=> fix: move <p> selector to <li>

packages/ndla-ui/src/Search/SearchResult.jsx
=> Add spinner on loading

packages/designmanual/dummydata/mockFilm.js, packages/ndla-ui/src/NDLAFilm/FilmSlideshow.jsx, packages/ndla-ui/src/NDLAFilm/SlideshowIndicator.jsx, packages/ndla-ui/src/NDLAFilm/component.film-slideshow.scss
• Slide fix
• Always allow indicator navigation
• Text padding increase on larger screens
=> Fixes for swiping slideshow ndla-film

packages/designmanual/stories/produksjonssystem/StructureExample.jsx, packages/ndla-editor/src/ItemName.js, packages/ndla-editor/src/ItemNameBar.js, packages/ndla-editor/src/Structure.js, packages/ndla-forms/package.json, packages/ndla-notion/src/Notion.jsx, packages/ndla-notion/src/NotionDialog.js, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
simplifies Structure component slightly, use nested selectors instead of passing in css name props, renames some things etc
=> Refactor structure

packages/ndla-editor/src/FileNameInput.js
Må åpne url på fil, ikke path i tilfelle den ligger annet sted.
=> open url, not path

packages/ndla-modal/src/Backdrop.js, packages/ndla-modal/src/Modal.js, packages/ndla-ui/src/CompetenceGoals/CompetenceGoalsDialog.js, packages/util/src/index.ts, packages/util/src/noScroll.ts
• Fixes for Modal iOs close
• Fixes for closeOnBackdrop
• Fixes for modals controlled by props
=> Bugfixes modal

packages/ndla-ui/src/NDLAFilm/FilmContentCard.jsx, packages/ndla-ui/src/NDLAFilm/MovieGrid.jsx
connects to NDLANO/Issues#1785
=> Add showTags flag

packages/designmanual/stories/atoms/ButtonExample.js, packages/ndla-button/src/Button.jsx, packages/ndla-ui/src/Masthead/MastheadLanguageSelector.jsx, packages/ndla-ui/src/Search/ToggleSearchButton.jsx
https://trello.com/c/QpANxa2m/211-spr%C3%A5kvelger
=> Ghost pill knapp for språkvelger

packages/core/scss/global/elements/_elements.quotations.scss, packages/core/scss/global/objects/objects.lists.scss
https://trello.com/c/PfQgnIVC/236-endre-sitat-og-sm%C3%A5-store-bokstaver-lister-i-visning
Små style endringer i liste og sitater
=> Small style change for lists and quotes

packages/ndla-ui/src/Frontpage/FrontpageCombinedSubjects.tsx
=> Add noscroll on close

packages/core/scss/global/elements/_elements.footer.scss, packages/ndla-zendesk/src/ZendeskButton.js
• Ignore if https://github.com/NDLANO/frontend-packages/pull/474 is merged (_element.footer.scss is removed in that PR)
=> Zendesk styling fix ndla-film

packages/ndla-ui/src/Footer/FooterLinks.tsx
Linkene på forsida funker ikkje.
=> Creates external links

packages/ndla-ui/src/BlogPosts/BlogPost.tsx, packages/ndla-ui/src/Frontpage/FrontpageCombinedSubjects.tsx, packages/ndla-ui/src/Frontpage/FrontpageMenuPortal.tsx, packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx, packages/ndla-ui/src/Search/SearchField.jsx, packages/ndla-ui/src/Search/component.search-field.scss
Fixes for IE11:
• Frontpage menu buttons
• Frontpage menu modal
• Frontpage blogposts
• Search-sleeve
• Search-field-input
=> Fixes for ie11

packages/designmanual/dummydata/index.js, packages/designmanual/dummydata/mockLanguages.js, packages/designmanual/stories/molecules/mastheads.jsx, packages/designmanual/stories/pages/FrontpageExample.jsx, packages/ndla-button/src/Button.jsx, packages/ndla-ui/src/Frontpage/FrontpageHeader.tsx, packages/ndla-ui/src/LanguageSelector/LanguageSelector.tsx, packages/ndla-ui/src/Search/ToggleSearchButton.jsx
• Fix for styling (remove underline + spacing/padding fixes)
• Remove all links in top of frontpage
• Dummy Language options for Design manual
=> LanguageSelector styling

packages/designmanual/stories/pages/FrontpageExample.jsx, packages/ndla-ui/src/BlogPosts/BlogPost.tsx, packages/ndla-ui/src/BlogPosts/BlogPostWrapper.tsx, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
• Licenses updated to use icons, (new props)
• Content changed (+ moved to messages)
• Removed linkTextShort prop for <BlogPost />
• Styling fixes
=> Blog: Styling and content fix

packages/ndla-ui/src/Search/ActiveFilters.jsx, packages/ndla-ui/src/Search/component.active-filters.scss, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Om man velger for mange fagfiltre i søket eksploderer søkefeltet.
=> Added max length and concatination for search filters on desktop

packages/designmanual/images/film_illustrasjon.svg, packages/ndla-ui/src/Footer/privacy_nb.tsx, packages/ndla-ui/src/Frontpage/FrontpageFilm.tsx, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Typo i messages,
Ndla film banner på forsiden, visuell bug på små skjermer
=> Små bugfikser

packages/core/src/shadows.ts, packages/ndla-modal/package.json, packages/ndla-modal/src/Modal.js, packages/ndla-modal/src/ModalBody.js, packages/ndla-modal/src/ModalHeader.js, packages/ndla-modal/src/StyledDialogOverlay.tsx, packages/ndla-ui/src/Masthead/MastheadSearchModal.tsx, packages/ndla-ui/src/Search/component.search-field.scss, yarn.lock
refactor Modal
- use reach/dialog instead of focus-trap-react, since it is not well maintained, and reach is simpler and cleaner. 
- Remove unnecessary code
- clean up css usage
Check that:
=> Modal refactor

packages/core/scss/global/objects/objects.content.scss, packages/designmanual/stories/molecules/breadcrumbs.jsx, packages/designmanual/stories/molecules/footers.jsx, packages/designmanual/stories/molecules/mastheads.jsx, packages/designmanual/stories/pages/LearningPathExample.jsx, packages/designmanual/stories/pages/index.jsx, packages/ndla-ui/src/Breadcrumb/Breadcrumb.jsx, packages/ndla-ui/src/Breadcrumb/BreadcrumbItem.jsx, packages/ndla-ui/src/Breadcrumb/component.breadcrumb.scss, packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx, packages/ndla-ui/src/LanguageSelector/LanguageSelector.tsx, packages/ndla-ui/src/Layout/PageContainer.jsx, packages/ndla-ui/src/LearningPaths/LearningPathInformation.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenu.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuAside.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuContent.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuIntro.tsx
Fix inverted for learningPaths.
Note props:
<LearningPathMenu /> (invertedStyle)
<LearningPathInformation /> (invertedStyle)
<LanguageSelector /> (invertedOutlineLargeScreensOnly)
<PageContainer /> (ndlaFilm + learningPath)
=> Fix inverted learningpaths

packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
=> opphavsmann -> opphavar

packages/ndla-editor/src/footer/Footer.tsx
Stops footer from being placed on top of h5p
=> reduce z index to 100

packages/designmanual/stories/produksjonssystem/StructureExample.jsx, packages/designmanual/stories/produksjonssystem/index.js, packages/ndla-editor/package.json, packages/ndla-editor/src/ItemNameBar.js, packages/ndla-editor/src/MakeDNDList.tsx, packages/ndla-editor/src/Structure.js, yarn.lock
Make Structure support DND, add to designmanual
=> Structure dnd

packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
La til footerSocialMediaLinksYoutube på nn/nb/en.
Henger saman med endring i ndla-frontend/src/containers/Page/components/Footer.jsx
=> footerSocialMediaLinksYoutube

packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
=> la til oversettingar på læringsstiar

packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Ordet meny fungerer ikkje, me tester om Innhold/Innhald/Content fungerer.
=> Meny -> Innhold

packages/hooks/src/useWindowSize.ts
Forsøker å fikse ssr av læringsstier og der finnes ikkje window. Erstatter med dummyverdier.
=> Add check for window

packages/designmanual/stories/simple-components.jsx, packages/ndla-ui/src/CreatedBy/CreatedBy.tsx, packages/ndla-ui/src/CreatedBy/index.ts, packages/ndla-ui/src/index-javascript.js, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
"Utarbeidet av" komponent til bruk i LTI-versjoner av artikler
=> Created by component

packages/ndla-ui/src/Search/SearchResultSleeve.tsx
Tar også med queryparametre slik at ssr av søkeside fungerer.
=> Fix ssr of searchpage

babel.config.js, package.json, packages/ndla-video-search/src/VideoSearchResultYouTube.jsx, packages/ndla-video-search/src/videoHelpers.js, yarn.lock
Avoid exceptions and nullpointers.
=> Add optional chaining to fix videosearch.

packages/ndla-ui/src/FileList/File.jsx
=> #1948: Add possibility of creating dead filelinks with fileExists property

packages/ndla-ui/src/Footer/Footer.tsx, packages/ndla-ui/src/Footer/FooterLinks.tsx, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
- Removes footer animation
- Makes footer links section optional by not passing links prop
- Adds vacancies common link in footer
=> Footer updates

packages/ndla-listview/src/ListItem.js, packages/ndla-listview/src/ListView.js
renderMarkdown er en funksjon som må returnere en fragment med html-formatert kode.
```
<Fragment>
<span dangerouslySetInnerHTML={{ __html: rendered }} />
</Fragment>
```
=> Prepare listview for markdown

packages/ndla-image-search/src/ImageSearchResult.js, packages/ndla-image-search/src/PreviewImage.js
=> Bug fix: Removes double uri encoding

jest.config.js, packages/button/package.json, packages/button/src/Button.jsx, packages/button/src/MultiButton.tsx, packages/button/src/index.js, packages/designmanual/stories/atoms/ButtonExample.js, packages/ndla-forms/src/PopupWrapper.tsx
New button-component for button with sub-items
=> Multi-button

packages/button/package.json, packages/button/src/MultiButton.tsx
Trenger å kunne ha feks ikon som innholdet i en knapp
=> #1985: Allow passing children to MultiButton

packages/ndla-licenses/src/licenseRights.js, packages/ndla-licenses/src/licenses.js
https://github.com/NDLANO/Issues/issues/2009
https://github.com/NDLANO/Issues/issues/2031
=> added NA license

packages/ndla-licenses/src/licenseRights.js, packages/ndla-licenses/src/licenses.js
https://github.com/NDLANO/Issues/issues/2009
https://github.com/NDLANO/Issues/issues/2031
Fixed "NA" description to match the one from backend, which is "N/A"
=> fixed NA title to match the one from backend

packages/button/src/MultiButton.tsx
Fix for å kunne gjemme den mini lagre knappen
=> added prop that allows to hide the second save button in EditorFooter

packages/designmanual/dummydata/mockExplanationService.js, packages/designmanual/package.json, packages/designmanual/stories/pages/ExplanationService.jsx, packages/ndla-forms/package.json, packages/ndla-forms/src/DropdownInput.js, packages/ndla-forms/src/DropdownMenuItem.js, packages/ndla-forms/src/Input.js, packages/ndla-howto/package.json, packages/ndla-image-search/package.json, packages/ndla-listview/package.json, packages/ndla-listview/src/ListItem.js, packages/ndla-modal/package.json, packages/ndla-modal/src/Modal.js, packages/ndla-notion/package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
=> Forklaringstjenesten updates

packages/core/scss/global/elements/_elements.lists.scss, packages/ndla-ui/src/Table/component.tables.scss
Justering igjen av lister og tabell spacing
=> Spacing adjustment to global lists and tables

packages/designmanual/dummydata/mockTaxonomyStructure.js, packages/ndla-editor/src/structure/ItemNameBar.js, packages/ndla-editor/src/structure/Structure.js
https://github.com/NDLANO/Issues/issues/2051 Legge til støtte for å vise synlighet i strukturredigering
=> Issue#2051 show italic if visible: false

packages/ndla-ui/src/Table/component.tables.scss
=> #2097: removing excess padding from paragraphs in table headers

packages/util/src/cookieHandler.ts
https://github.com/NDLANO/Issues/issues/2144
* La til samesite støtte hos cookies, setter strict som default og lax ellers.
=> added samesite support in cookies

packages/button/src/Button.jsx, packages/designmanual/dummydata/mockPrograms.js, packages/designmanual/stories/atoms/ButtonExample.js, packages/designmanual/stories/pages/FrontpageReDesignExample.jsx, packages/designmanual/stories/pages/ProgrammePage.jsx, packages/designmanual/stories/pages/index.jsx, packages/ndla-ui/src/Frontpage/FrontpageAllSubjects.tsx, packages/ndla-ui/src/Frontpage/FrontpageProgramMenu.tsx, packages/ndla-ui/src/Navigation/NavigationBox.tsx, packages/ndla-ui/src/Programme/Programme.tsx, packages/ndla-ui/src/Programme/index.ts, packages/ndla-ui/src/index-javascript.js, packages/ndla-ui/src/locale/messages-en.js, packages/safelink/src/SafeLinkButton.tsx
- Lys grå knapp støtte
- Fjernet transformX/Y ved hover på mørk knapp
- Renamet program -> programme
- Oppdatert designmanual forside og programside
=> Re design updates

README.md, packages/ndla-zendesk/src/ZendeskButton.js
Fixes https://github.com/NDLANO/Issues/issues/2190
Ser ut til at classname er borte på elementet, byttet til id'en istedet så ut til å fungere.
=> Changed from targeting classname to id for zendesk in css

packages/core/scss/global/objects/objects.content.scss
=> Fixes double scrollbar in LTI

packages/button/src/Button.jsx, packages/designmanual/dummydata/mockPrograms.js, packages/designmanual/stories/molecules/mastheads.jsx, packages/designmanual/stories/pages/ArticleAdditional.jsx, packages/designmanual/stories/pages/ArticleAssessmentResource.jsx, packages/designmanual/stories/pages/ArticleExercise.jsx, packages/designmanual/stories/pages/ArticleExternalLearningResource.jsx, packages/designmanual/stories/pages/ArticleLearningmaterial.jsx, packages/designmanual/stories/pages/ArticleSourceMaterial.jsx, packages/designmanual/stories/pages/FrontpageReDesignExample.jsx, packages/designmanual/stories/pages/MultidisciplinarySubjectArticle.jsx, packages/designmanual/stories/pages/ProgrammePage.jsx, packages/designmanual/stories/pages/SubjectPage.jsx, packages/designmanual/stories/pages/index.jsx, packages/ndla-ui/src/Article/ArticleSideBar.tsx, packages/ndla-ui/src/Article/component.article.scss, packages/ndla-ui/src/Breadcrumblist/Breadcrumblist.tsx, packages/ndla-ui/src/Frontpage/FrontpageProgramMenu.tsx, packages/ndla-ui/src/Navigation/NavigationBox.tsx, packages/ndla-ui/src/Navigation/NavigationTopicAbout.tsx, packages/ndla-ui/src/Programme/Programme.tsx
- Oppdatert visning i designmanual av læringsressurser
Justeringer på fagsider(Bokmerkenavigasjon, navigasjon)
=> Re design adjustments

packages/designmanual/stories/article/ArticleLoader.jsx, packages/designmanual/stories/pages/MultidisciplinarySubjectArticle.jsx, packages/ndla-ui/src/Article/component.article.scss, packages/ndla-ui/src/Breadcrumblist/Breadcrumblist.tsx
=> Fix multidisciplinary-subject pages

packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx
Håper dette fikser problemet med at søkefeltet kommer for langt opp på iOS
=> Fix search on iOS

packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx
Såg ikkje ut til at første forsøk fiksa det. Ser bedre ut med denne fiksen
=> Fix search on iOS attempt 2

packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Rettar emner til emne (utan r i fleirtal)
og bytter Lengre/Kortare beskriving til Vis mindre/meir
og tilsvarande på bokmål: Vis mer/mindre
=> retter emner - emne

packages/designmanual/stories/organisms/CompetenceGoalsExample.jsx, packages/ndla-modal/src/Modal.js, packages/ndla-ui/src/CompetenceGoalTab/CompetenceGoalTab.tsx, packages/ndla-ui/src/CompetenceGoalTab/CompetenceItem.tsx, packages/ndla-ui/src/CompetenceGoals/CompetenceGoalsDialog.js
Se i packages/designmanual/stories/organisms/CompetenceGoalsExample.jsx "CompetenceGoalTabdata" for struktur på data
=> Competence-goals with grouped heading

packages/ndla-ui/src/Article/Article.jsx
=> Add parameter to article page

packages/ndla-ui/src/Frontpage/FrontpageAllSubjects.tsx, packages/ndla-ui/src/Navigation/NavigationBox.tsx
https://trello.com/c/b79aNkJY/668-litt-rar-visning-av-meny-p%C3%A5-safari-mac
Fikser spacing på boksene, samt spacing i utlisting av alle fag på forsiden
=> Fixes styling-problems in navigation-box and frontpage-subjects

packages/ndla-ui/src/Navigation/NavigationHeading.tsx
https://trello.com/c/0CqgahLm/672-endre-tittelen-i-u%C3%B8nskede-fagforsider-slik-at-subject-vises-med-mindre-skriftst%C3%B8rrelse
=> Adjust styling in sub-heading in navigation-box

packages/ndla-article-scripts/src/figureScripts.js, packages/util/src/copyTextToClipboard.ts
Fixes NDLANO/Issues#2276
Firefox og edge støtter ikkje permission api for clipboard: https://bugzilla.mozilla.org/show_bug.cgi?id=1560373
Reverter https://github.com/NDLANO/frontend-packages/commit/a44a879e57adf90249a3818a505c186377d907bd
=> Revert usage of permissions api

packages/core/scss/core.scss, packages/core/scss/global/elements/_elements.code.scss, packages/ndla-ui/src/Codeblock/Codeblock.tsx
Ref: https://github.com/NDLANO/article-converter/pull/199
=> Prevent codeblock styling from external

packages/ndla-ui/src/locale/messages-en.js
=> Update messages-en.js: competance -> competence

packages/designmanual/stories/molecules/ArticleBylineExample.jsx, packages/ndla-ui/src/Article/Article.jsx, packages/ndla-ui/src/Article/ArticleByline.tsx, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
https://trello.com/c/tZJYJYBx/406-legge-til-linje-for-leverand%C3%B8r
=> Added support for suppliers in article-byline

packages/ndla-ui/src/Footer/FooterLinks.tsx
https://trello.com/c/17YoiVzh/734-endre-ikon-i-footer
=> Change colors on SoMe-icons in footer

packages/ndla-code/src/Codeblock/Codeblock.tsx
Det er jo ikkje en FC som sendes inn.
Trengs for https://github.com/NDLANO/editorial-frontend/pull/794
=> Use correct parameter type

packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
https://trello.com/c/nlOPLwYO/742-endre-ordlyd-p%C3%A5-knappen
=> Update article use-content-button text

packages/ndla-ui/src/Frontpage/FrontpageProgramMenu.tsx, packages/ndla-ui/src/Programme/Programme.tsx
Fixes NDLANO/Issues#2322
Legger til husk av alle fag og valgt nivå.
=> Remember grade selection and all subjects

packages/ndla-howto/src/ArticleInModal.js, packages/ndla-howto/src/StaticInfoComponents/index.js
Fikser feilmelding om manglende key
=> Fix missing key warning

packages/designmanual/stories/simple-components.jsx, packages/ndla-notion/src/NotionHeader.js, packages/ndla-notion/src/index.js, packages/ndla-ui/src/CreatedBy/CreatedBy.tsx, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Partially fixes: https://github.com/NDLANO/Issues/issues/2306
Er usikker på Phrases, prøvde å basere meg på de andre komponentene men gir ikke alltid mening i konteksten med forklaringer
=> 2306 legge til forklaring under bruk innhold

packages/ndla-code/src/languages.tsx
NDLANO/Issues#2351
Legger til bash som mulig språk
=> Added bash to code editor

packages/designmanual/stories/pages/ExplanationService.jsx, packages/ndla-listview/src/ListView.js, packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
https://trello.com/c/ssB7x01t/780-s%C3%B8k-fungerer-ikke-riktig-ved-s%C3%B8k-p%C3%A5-skyvemast-m%C3%A5-jeg-velge-fag-f%C3%B8r-treff-vises
=> Show hit-count in list-view

packages/designmanual/stories/simple-components.jsx, packages/ndla-ui/src/NDLAFilm/AllMoviesAlphabetically.tsx, packages/ndla-ui/src/NDLAFilm/FilmContentCard.jsx, packages/ndla-ui/src/NDLAFilm/FilmMovieSearch.jsx, packages/ndla-ui/src/NDLAFilm/FilmSlideshow.jsx, packages/ndla-ui/src/Search/IsPathToHighlight.ts, packages/ndla-ui/src/Search/__tests__/Highlight-test.js
NDLANO/Issue#2367
Fjerner subjects fra ndla-film-komponenter
=> Remove /subjects from urls

packages/core/scss/global/elements/_elements.code.scss, packages/designmanual/.storybook/preview-head.html, packages/designmanual/stories/basic-styles.jsx, packages/designmanual/stories/codeblock/CodeblockExample.jsx, packages/designmanual/stories/simple-components.jsx, packages/ndla-code/src/Codeblock/Codeblock.tsx
https://trello.com/c/gNwpz1Wj/428-utvide-kodevisning
PR i front-end for å inkludere font: https://github.com/NDLANO/ndla-frontend/pull/608
Usikker på om "Source Code Pro" fonten må inkluderes andre plasser(ED?)
=> Styling changes on codeblock

packages/designmanual/stories/produksjonssystem/MultiSelectDropdownExample.jsx, packages/ndla-forms/src/DropdownMenu.js
- Lagt til pager i dropdownmenu
- Også lagt til i designmanual som et alternativ under produksjonssystem > dropdown med multiselect
=> Conditional pager i DropdownMenu

packages/ndla-ui/src/Breadcrumb/BreadcrumbBlock.tsx, packages/ndla-ui/src/MultidisciplinarySubject/MultidisciplinarySubject.tsx, yarn.lock
Relates to NDLANO/Issues#2375
Denne flytter egentlig bare litt logikk til ndla-frontend for å litt enklere kunne gjenbruke litt kode
=> #2375: Move multidisciplinary navigation box handling out of frontend-packages

packages/designmanual/stories/article/RelatedArticleListExample.jsx, packages/designmanual/stories/collated-components.jsx
https://trello.com/c/ixXyLgWC/848-bytte-ut-relatert-artikkel
=> Changed heading for related content

packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
Endret ordlyden til å konsistent bruke lydfil i stedet for lydklipp.
I forbindelse med denne: NDLANO/article-converter#216
=> changed word sound lydklipp -> lydfil

packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx
Fikser bug i https://github.com/NDLANO/ndla-frontend/pull/599
=> Search item breadcrumb fix

packages/designmanual/stories/molecules/mastheads.jsx, packages/designmanual/stories/pages/LearningPathExample.jsx, packages/designmanual/stories/pages/SearchResultTypeExample.jsx, packages/designmanual/stories/pages/SubjectPage.jsx, packages/designmanual/stories/produksjonssystem/CodeBlockEditorExample.jsx, packages/designmanual/stories/produksjonssystem/FooterExample.jsx, packages/designmanual/stories/produksjonssystem/MultiSelectDropdownExample.jsx, packages/designmanual/stories/produksjonssystem/ProductionToolVersionLog.jsx, packages/eslint-config-ndla/base.js
Legger til regel i eslint så man får error ved bruk av console.log i koden.
=> Eslint rule: no-console error

packages/ndla-ui/src/RadioButtonGroup/component.radio-button-group.scss
=> reverted important attribute to font-size label

packages/designmanual/stories/produksjonssystem/UploaderExample.jsx, packages/ndla-forms/src/UploadDropZone.js, packages/ndla-forms/src/__tests__/filetypeHelper-test.js, packages/ndla-forms/src/filetypeHelper.js
Fikser dra og slipp filer til filopplaster. Sjekker enten type eller filnavn.
=> Make drag and drop files work again.

packages/ndla-ui/src/locale/messages-en.js, packages/ndla-ui/src/locale/messages-nb.js, packages/ndla-ui/src/locale/messages-nn.js
https://trello.com/c/BBwmw6ar/434-endre-ordlyd-p%C3%A5-emnebeskrivelse
=> Change show-more link-text on topic

packages/ndla-editor/package.json, packages/ndla-editor/src/SlateBlockMenu.js, yarn.lock
=> Fix info modal focus fighting

packages/ndla-forms/src/Input.js
Fikser scrolling i chrome ved innsetting av bilde
Relatert til https://github.com/NDLANO/editorial-frontend/pull/923
=> Fix scrolling on insert image

packages/ndla-code/src/Codeblock/Codeblock.tsx, packages/ndla-code/src/index.ts
Relates to NDLANO/Issues#2495
Som vi snakka om på standup :smile:
=> #2495: Don't show language if title is available

packages/designmanual/stories/simple-components.jsx
Markere at smal tekstboks eksempel i designmanual er inaktiv
=> Minor design-adjustments

packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/pages/FrontpageExample.jsx, packages/ndla-ui/package.json, packages/ndla-ui/src/Footer/FooterLinks.tsx, packages/ndla-ui/src/MessageBox/MessageBox.tsx, yarn.lock
https://trello.com/c/YKEumopK/784-varslingssystem-til-sluttbrukar
=> Message box

.github/workflows/ci.yml
Sjekker at push er til master og kjører yarn deploy for å oppdatere designmanual.ndla.no
=> Add yarn deploy and remove tests

packages/ndla-ui/src/Programme/Programme.tsx, packages/ndla-ui/src/Programme/ProgrammeSubjects.tsx
Dette forsvant ved omskriving av sida til egen komponent. Har lagt inn igjen kode som blei sletta. Har også oppdatert navnet på grunn av en skrivefeil.
=> Fixing remembering selected grade level.

packages/ndla-ui/src/SearchTypeResult/PopupFilter.tsx
Ref: https://github.com/NDLANO/ndla-frontend/pull/663
=> Adjust view when only subjects are available in search-filter popup

packages/designmanual/stories/pages/SubjectPage.jsx, packages/ndla-ui/src/Navigation/NavigationTopicAbout.tsx
Markdown i emne-ingress vises ikkje på subjectpage. Legger til støtte for å sende inn rendermetode.
=> add renderMarkdown parameter

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
oppsto -> oppstod
occurd -> occurred
Kanskje ikkje i bruk? Men la til 2021 i info om fagfornyelsen: Høsten 2020 og 2021
=> Mindre rettingar i språk

packages/ndla-icons/README.md, packages/ndla-icons/src/contentType/SubjectMaterial.tsx, packages/ndla-icons/svg/contentType/subject-material.svg, packages/ndla-ui/src/ContentTypeBadge/component.content-type-badge.scss
https://trello.com/c/1ODKgori/443-ikonet-for-innholdstyper-m%C3%A5-revurderes
=> Update subject-material icon

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Har fått teksten på bokmål. Har lagt inn slik eg trur det skal være på nynorsk og engelsk. Men her må språkkyndige verifisere
https://trello.com/c/UPQEIQm1/1085-oppdatere-tekst-p%C3%A5-visjon-p%C3%A5-footeren
=> Endre visjonsteksten i footer

packages/ndla-ui/src/AudioPlayer/AudioPlayer.tsx
https://trello.com/c/naZNxJ5v/451-kvadratisk-bilde-podcast
=> Make image in podcast square

packages/ndla-ui/src/CompetenceGoalTab/CompetenceGoalTab.tsx
https://trello.com/c/GqEOYBfp/412-merke-ndlano-med-informasjon-fra-udir
=> License on competence texts

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
https://trello.com/c/pzffrSto/453-rette-skrivem%C3%A5te-p%C3%A5-visjonstekst
=> Endre skrivefeil på visjonstekst

package.json, packages/designmanual/dummydata/mockTypeahead.js, packages/designmanual/stories/produksjonssystem/MultiSelectDropdownExample.jsx, packages/ndla-forms/src/DropdownMenuImage.js, packages/ndla-forms/src/DropdownMenuItem.js, packages/safelink/src/SafeLink.tsx, yarn.lock
For å kunne disable episoder som allerede er valgt i episode søk for podcast-serier
=> Make it possible to disable single `DropdownMenuItem`s

packages/designmanual/stories/article/FigureImage.jsx, packages/ndla-article-scripts/src/figureScripts.js, packages/ndla-ui/src/Figure/FigureBylineExpandButton.tsx, packages/ndla-ui/src/Figure/component.figure.scss, packages/ndla-ui/src/Figure/index.js, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Fixes NDLANO/Issues#2550
Har lagd en knapp-komponent og funksjonalitet for å vise/skjule byline under bilder.
=> Optional skjule byline

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
https://trello.com/c/0BNJ1Tt1/454-endre-ordlyd-p%C3%A5-knapp-i-lisensboks
=> Changed text on copy source reference button

packages/ndla-ui/src/locale/messages-en.ts
Fixes https://github.com/NDLANO/Issues/issues/2617
=> Add english translation for AddArticleModal

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Closes https://github.com/NDLANO/Issues/issues/2622
=> Replace "created by" with "retrieve from" for en, nn, nb

packages/ndla-ui/src/Topic/Topic.tsx
Er med å fikser https://github.com/NDLANO/Issues/issues/2583
Fikser et display issue, length vil være tilgjengelig på objektet selv ved tomme arrays som ofte forekommer.
=> Conditional check displayed a zero instead of nothing

packages/ndla-ui/src/Frontpage/FrontpageMultidisciplinarySubject.tsx, packages/ndla-ui/src/Frontpage/FrontpageSearch.tsx, packages/ndla-ui/src/Search/SearchFieldForm.tsx
Fikset typene så de matchet hva de egentlig var.
=> WelcomePage to TS

packages/ndla-ui/src/Frontpage/FrontpageProgramMenu.tsx
https://trello.com/c/iVx4qJGW/131-ta-bort-ledeteksten-og-pilen
=> Possible to show/hide beta-cursor on frontpage

packages/designmanual/stories/pages/ArticleAdditional.jsx, packages/designmanual/stories/pages/ArticleAssessmentResource.jsx, packages/designmanual/stories/pages/ArticleExercise.jsx, packages/designmanual/stories/pages/ArticleExternalLearningResource.jsx, packages/designmanual/stories/pages/ArticleLearningmaterial.jsx, packages/designmanual/stories/pages/ArticleSourceMaterial.jsx, packages/ndla-ui/src/Article/ArticleByline.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
https://trello.com/c/xgB8Rpam/120-design-for-utskrift-av-ressurs
=> Changed print-button in articles

packages/designmanual/dummydata/mockPrograms.js, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
https://trello.com/c/gCYFmMAz/137-endre-navn-p%C3%A5-tabs
=> Change name of subject categories on frontpage

packages/designmanual/stories/molecules/ModalExample.jsx, packages/ndla-modal/src/Modal.js, packages/ndla-ui/src/Article/ArticleByline.tsx
https://trello.com/c/AR1VI3kr/121-lisensboks-skal-bytte-farge-fra-lysebl%C3%A5-til-hvit
https://trello.com/c/6xnSx9OY/139-lisensboksen-hopper-opp-og-ned
=> Changed background-color in license-box and position at top

packages/ndla-notion/src/NotionDialog.js, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Legger til en oversettelse som ikke eksisterte.
=> Added missing notions translation

packages/ndla-ui/src/Footer/FooterLinks.tsx
=> Fyr og deling er arkivert

packages/ndla-ui/src/locale/messages-nn.ts
På nynorsk brukar me e-ending.
Prøv å fjerna filter -> Prøv å fjerne filter
=> lang: fjerna -> fjerne

packages/ndla-ui/src/AudioPlayer/Controls.tsx
https://trello.com/c/sbxHAfzX/142-podcast-lydfil-har-feil-retning-p%C3%A5-skip-back-foreward
=> Switch back/forward position in audio-player

packages/designmanual/package.json, packages/ndla-code/package.json, packages/ndla-ui/package.json, yarn.lock
Snyk gir utslag på react-syntax-highlighter. Bumping skal visstnok fikse det.
=> Bump react-syntax-highlighter

packages/ndla-ui/src/Figure/component.figure.scss, packages/util/src/markdownHelpers.ts
Ikke helt likt slik det var tidligere, men ikke langt unna.
Kan testes ved å linke lokalt og sjekke http://localhost:3000/nn/subject-matter/learning-resource/31182/edit/nn.
=> Fikse padding i FigureCaption

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/model/SubjectCategories.ts
NDLANO/Issues#2746
Ny kategori som skal brukes for å markere fag som aktive for visning på ndla.no
=> Added new category

packages/ndla-editor/src/index-javascript.js, packages/ndla-editor/src/index.ts, packages/ndla-editor/src/structure/Fade.tsx, packages/ndla-editor/src/structure/ItemNameBar.tsx, packages/ndla-editor/src/structure/MakeDNDList.tsx, packages/ndla-editor/src/structure/Structure.tsx
Refaktorerte Structure-komponenten for å gjøre det enklere å forbedre ytelsen til struktursiden ved en senere anledning.
=> Refactored Structure component to TypeScript

packages/designmanual/stories/article/FigureImage.jsx, packages/designmanual/stories/simple-components.jsx, packages/ndla-article-scripts/src/figureScripts.js, packages/ndla-licenses/src/LicenseByline/LicenseIconList.tsx, packages/ndla-ui/src/Figure/Figure.js, packages/ndla-ui/src/Figure/FigureExpandButton.js, packages/ndla-ui/src/Figure/component.figure.scss, packages/ndla-ui/src/Image/Image.jsx, packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap
https://trello.com/c/pW1TdtCU/144-justering-av-expand-visning-av-bilder-i-artikkel
https://trello.com/c/awLg7HxU/72-redesigne-bildemodulen
NB: article-converter må endres for å vise expand-knapp korrekt. PR: https://github.com/NDLANO/article-converter/pull/270
=> Justering av expand visning av bilder i artikkel og lisensvisning

packages/designmanual/stories/produksjonssystem/StructureExample.jsx, packages/ndla-editor/src/structure/ItemNameBar.tsx, packages/ndla-editor/src/structure/Structure.tsx
NDLANO/Issues#2758
Brukes for å rendre et ikon for feil i strukturen
=> #2758: Adds function prop to allow rendering something before titles in structure

packages/ndla-ui/src/Topic/Topic.tsx
https://trello.com/c/u9nyyVcY/1272-ingresser-p%C3%A5-ndla-film-er-ikke-lesbare
=> Fix colors on topics with inverted-style

packages/core/package.json, yarn.lock
=> fixed regex vulnerability

packages/ndla-ui/src/Topic/Topic.tsx
https://trello.com/c/aUVvDCUU/1278-safari-mister-border-radius-et-%C3%B8yeblikk-ved-hover-p%C3%A5-emnebeskrivelsebilde
=> Fix safari-issue on topic-image hover

packages/ndla-howto/src/StaticInfoComponents/index.js
Se forklaring av testing i https://github.com/NDLANO/editorial-frontend/pull/1198
=> Add howto for visual element

packages/ndla-ui/src/Article/ArticleByline.tsx
https://trello.com/c/XGeD0YwE/1345-tom-linje-n%C3%A5r-det-ikke-er-opphaver
=> Don't show "written by" in article-byline if authors are empty

packages/ndla-ui/package.json, packages/util/package.json
Whops jeg la disse feil plass i den første PR'en :shrug:
=> Move dependencies to correct package

packages/ndla-ui/src/MultidisciplinarySubject/MultidisciplinarySubject.tsx, packages/util/src/__tests__/cookie-test.ts, packages/util/src/cookieHandler.ts
Nyttig for å kunne sette cookies som går ut på dato (feks tokens med utløpsdato)
=> Adds options to set expiration and path for cookies created with the cookie handler

packages/designmanual/dummydata/mockResources.js, packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
NDLANO/Issues#2893
Passer på at artikler er synlige i launchpad sjølv om dei er tilleggstoff.
Test
Lager alpha-versjoner av ndla-ui og lager pr i ndla-frontend.
=> Make active resource show in launchpad

packages/ndla-forms/package.json, packages/ndla-howto/package.json, packages/ndla-image-search/package.json, packages/ndla-listview/package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/CopyParagraphButton/CopyParagraphButton.tsx, packages/ndla-ui/src/CopyParagraphButton/initCopyParagraphButtons.tsx, yarn.lock
Relatert til https://github.com/NDLANO/article-converter/pull/294. Kan testes direkte i article-converter PR.
=> Bugfix 2888 h2 anchors

packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Velg språk er betre
https://trello.com/c/btHZjXuY/1435-ny-spr%C3%A5klov-forbyr-m%C3%A5lform
=> velg målform -> velg språk

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
=> Added missing keys

packages/ndla-ui/src/Figure/Figure.tsx, packages/ndla-ui/src/Hero/Hero.tsx, packages/ndla-ui/src/Hero/index.ts, packages/ndla-ui/src/Image/Image.tsx, packages/ndla-ui/src/Image/ImageLink.tsx, packages/ndla-ui/src/Image/index.ts, packages/ndla-ui/src/Topic/Topic.tsx, packages/ndla-ui/src/types.ts
Fixes https://github.com/NDLANO/Issues/issues/2916
Er fortsatt noen type-feil når man linker lokalt, men disse må fikses i ndla-frontend og er ikke "feil" i den forstand at noe er galt i frontend-packages.
=> Update types to fix type errors in NDLA frontend

packages/ndla-tabs/src/ArticleTabs.tsx, packages/ndla-tabs/src/Tabs.tsx, packages/ndla-ui/src/Translation/TranslationBox.tsx
Fikser en feil i typingen av tabs som må gjennom før alle pakker oppdateres i forbindelse med NDLANO/Issues#2919
=> Change tabs content type to correct type

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Bytta blogginnlegg, utan å bytte bilde på forsida.
=> Nytt blogginnlegg

packages/ndla-ui/src/Figure/Figure.tsx, packages/ndla-ui/src/Figure/FigureBylineExpandButton.tsx, packages/ndla-ui/src/Figure/index.ts
Noen små oppdateringer på typer for at pakkene skal fungere uten feilmeldinger i article-converter.
=> Typescript adjustments

packages/ndla-notion/src/Notion.tsx
Ser ut som at denne har forsvunnet under omskriving. Legger den tilbake igjen, da den brukes i ED.
=> Re-added subtitle prop to notion

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Har endra lisens, vert dette plukke opp automatisk?
license: 'CC-BY-NC-SA-4.0',
->
license: 'CC-BY-SA-4.0',
=> Nytt blogginnlegg1

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
=> Retter opphav

packages/ndla-licenses/package.json, packages/ndla-ui/src/Image/Image.tsx, packages/util/package.json, yarn.lock
Erstatter det med bruk av `??`
=> Removing defined

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nn.ts
en: Syncer tekst med læreplan
nn: kunna -> kunne
=> competenceGoalTitle

packages/ndla-ui/src/Table/component.tables.scss
Fixes https://github.com/NDLANO/Issues/issues/2952
Kan eventuelt legge til mer/mindre. Inntil videre la jeg til medium.
=> Added a little more space underneath every table

packages/ndla-licenses/src/LicenseByline/LicenseByline.tsx, packages/ndla-licenses/src/LicenseByline/LicenseIconList.tsx, packages/ndla-ui/src/BlogPosts/BlogPost.tsx
https://github.com/NDLANO/Issues/issues/2949
La til hvit som defaultProps på BlogPost.
=> Added props to LicenseByline and BlogPost to allow for changing text and icon color

packages/ndla-ui/src/Programme/Programme.tsx, packages/ndla-ui/src/Programme/ProgrammeSubjects.tsx
https://github.com/NDLANO/Issues/issues/2929
Tidligere ble klassetrinn lagt til i localStorage, men det ser ikke ut som at det faktisk gjorde noe.
=> Add grade and selectedGrade props to Programme

packages/ndla-ui/src/Frontpage/FrontpageAllSubjects.tsx, packages/ndla-ui/src/SearchTypeResult/SearchFieldHeader.tsx, packages/ndla-ui/src/SearchTypeResult/SearchHeader.tsx, packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx, packages/ndla-ui/src/SearchTypeResult/SearchNotionItem.tsx, packages/ndla-ui/src/SearchTypeResult/index.ts
En haug med småendringer som må til for at ndla.no/search kan gå i TypeScript.
=> Type adjustments to allow for SearchPage to be converted to TypeScript

packages/ndla-ui/src/NDLAFilm/FilmSlideshow.tsx, packages/ndla-ui/src/NDLAFilm/types.ts
Småplukk som ble funnet under oppgradering av pakker i ndla-frontend.
=> Minor fixes to MovieType to more accurately fit input data

packages/ndla-ui/src/LearningPaths/LearningPathInformation.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenu.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuAside.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuAsideCopyright.tsx
=> Altering learningpath types to remove unused props

package.json, packages/carousel/package.json, packages/designmanual/package.json, packages/designmanual/stories/wrappers/IconList.jsx, packages/ndla-accordion/package.json, packages/ndla-editor/package.json, packages/ndla-forms/package.json, packages/ndla-howto/package.json, packages/ndla-image-search/package.json, packages/ndla-listview/package.json, packages/ndla-modal/package.json, packages/ndla-notion/package.json, packages/ndla-pager/package.json, packages/ndla-ui/package.json, packages/ndla-zendesk/package.json, packages/tooltip/package.json, yarn.lock
Den var markert som deprecated med seks utropstegn på repoet deres. Kanskje på tide å fjerne den.
=> Remove react-prop-types dep

packages/button/package.json, packages/carousel/package.json, packages/designmanual/package.json, packages/hooks/package.json, packages/ndla-accordion/package.json, packages/ndla-audio-search/package.json, packages/ndla-code/package.json, packages/ndla-editor/package.json, packages/ndla-forms/package.json, packages/ndla-howto/package.json, packages/ndla-icons/package.json, packages/ndla-image-search/package.json, packages/ndla-licenses/package.json, packages/ndla-listview/package.json, packages/ndla-modal/package.json, packages/ndla-notion/package.json, packages/ndla-pager/package.json, packages/ndla-tabs/package.json, packages/ndla-tracker/package.json, packages/ndla-ui/package.json, packages/ndla-video-search/package.json, packages/ndla-zendesk/package.json, packages/safelink/package.json, packages/switch/package.json, packages/tooltip/package.json, yarn.lock
Påvirker vel ikke stort. Vi har fortsatt deps som ikke støtter React 17.
=> Added react 17 to every peer-dep field

Dockerfile, README.md, packages/button/README.md, packages/core/README.md, packages/designmanual/README.md, packages/designmanual/package.json, packages/eslint-config-ndla/README.md, packages/ndla-article-scripts/README.md, packages/ndla-audio-search/README.md, packages/ndla-error-reporter/README.md, packages/ndla-icons/README.md, packages/ndla-image-search/README.md, packages/ndla-licenses/README.md, packages/ndla-pager/README.md, packages/ndla-source-map-resolver/README.md, packages/ndla-tabs/README.md, packages/ndla-tracker/README.md, packages/ndla-ui/README.md, packages/ndla-video-search/README.md, packages/safelink/README.md, packages/switch/README.md, packages/util/README.md
Spesifiserer bruk av yarn for utvikling.
=> Oppdaterer readmes til å være meir konsistente.

packages/ndla-ui/src/FactBox/FactBox.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Fixes https://github.com/NDLANO/Issues/issues/3028
=> Added open/close title for FactBox button

packages/ndla-ui/src/Masthead/utils.ts
Dette løste problemet lokalt hos meg på http://localhost:3000/nn/subject:1:9b7e7534-c072-4412-b8ef-df076308cad0?disableSSR=true. Siden krasjer ikke og ingen feilmeldinger i konsoll.
=> useMastheadHeight awaits component mount before adding observer

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Trengs for https://github.com/NDLANO/ndla-frontend/pull/952
Relatert til https://github.com/NDLANO/Issues/issues/3049
=> Added new beta and outdated messages for messagebox

packages/designmanual/stories/pages/SubjectPage.jsx
Fixes https://github.com/NDLANO/Issues/issues/3063
Er noe rart med auto-scrollingen. Ser ut til å ha vært her lenge.
=> Add a parseInt to make sure item ID's align

packages/ndla-ui/src/TopicMenu/TopicMenu.jsx
https://github.com/NDLANO/Issues/issues/3060
=> Fix grade change in TopicMenu

packages/designmanual/stories/molecules/MessageBoxExample.jsx, packages/ndla-ui/src/MessageBox/MessageBox.tsx
Oppdaget ved en tilfeldighet at meldingsboks-eksempelet ikke fungerte. Rydder samtidig litt opp i koden og bruker TFunction i stedet for direkte bruk av nb-messages.
Hvordan teste:
1. Prod: Fungerer ikke:  https://designmanual.ndla.no/?path=/story/sammensatte-moduler--meldings-og-infoboks
2. PR-instans:  Fungerer: https://frontend-packages-pr-1095.ndla.sh//?path=/story/sammensatte-moduler--meldings-og-infoboks
- Sjekk at translations og bokser ser riktig ut
=> Bugfix messagebox example

packages/designmanual/stories/molecules/MessageBoxExample.jsx, packages/designmanual/stories/molecules/MessageBoxTabs.jsx, packages/designmanual/stories/pages/MessageBoxSiteExample.jsx, packages/ndla-ui/package.json, packages/ndla-ui/src/MessageBox/MessageBox.tsx, yarn.lock
Fixes https://github.com/NDLANO/Issues/issues/3072
Sticky fungerte ikke, og z-index så ikke ut til å ha noe effekt. Har testet ved å linke inn ndla-frontend, samt sjekket eksemplene i designmanualen.
=> Remove Sticky and z-index from MessageBox

packages/ndla-ui/src/Programme/ProgrammeSubjects.tsx
Relatert til https://github.com/NDLANO/Issues/issues/3001
=> Show warning for missing programme subjects as a message box

packages/ndla-licenses/src/LicenseByline/LicenseIconList.tsx, packages/ndla-ui/src/MediaList/MediaList.tsx
https://github.com/NDLANO/Issues/issues/3079
Kan testes direkte i designmanuelen ved å gå inn på "regler for bruk" i "begrepsforklaring", for deretter å sjekke at hover-teksten plasseres riktig selv etter man har scrollet.
=> Fixed positioning for LicenseIcon text

packages/designmanual/stories/article/ArticleLoader.jsx, packages/designmanual/stories/pages/index.jsx, packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Legger til tekst for artikler som kan være utdaterte.
Sjekk designmanual for eksempelside. Sjølve ordlyden avventes svar fra NDLA.
=> Adding text for possible outdated article.

packages/ndla-ui/src/Topic/Topic.tsx
Legger til støtte for messageBox for emne i fagside.
=> Adds support for message for topic.

packages/util/package.json, packages/util/src/translationValidation.ts, yarn.lock
Kan testes ved å tukle med translations-testen i ndla/ui.
=> Replaced cli-table3 with console.table. Not as pretty, but does not rely on node

packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Personvernerklæring og cookies
=> Personvernerklæring og cookies

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, packages/ndla-ui/src/model/SubjectTypes.ts, packages/ndla-ui/src/model/index.ts
Skal brukes for å skille mellom vanlige fag og ressurs-samlinger.
=> Adding subject types for more categorization

packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/molecules/MyNdlaAddToFavoritesExample.tsx, packages/designmanual/stories/molecules/SnackbarExample.tsx, packages/ndla-ui/src/SnackBar/SnackBar.tsx, packages/ndla-ui/src/SnackBar/index.ts, packages/ndla-ui/src/index.ts
• New Snackbar component
• Added to my favorites dialog example
=> Snackbar component added

.gitignore, vercel.json
Relatert til NDLANO/Issues#3109
Oppdaterer deprecated vercel-konfigurasjon basert på https://vercel.com/docs/project-configuration#legacy/routes/upgrading.
=> Rewrite deprecated vercel config

packages/designmanual/stories/molecules/MyNdlaAddToFavoritesExample.tsx, packages/designmanual/stories/molecules/TagSelectorExample.tsx, packages/ndla-ui/src/TagSelector/SuggestionInput.tsx, packages/ndla-ui/src/TagSelector/Suggestions.tsx, packages/ndla-ui/src/TagSelector/TagSelector.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
• Tag selector component, not tested on phones.
• Should handle basic keyboard input and navigation
• Tried my best to add UU for it.. 
**Note** that suggestions box has position absolute as props so we can control it better. Ideally the component would choose static vs absolute positioning based on position on screen automatically... left a TODO comment for it.
=> Waiting for QA from design
=> Tag selector finish it

packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
La til bindestrek:
Andre NDLA-nettsteder
=> Frå språkgjengen

packages/ndla-ui/src/locale/__tests__/translations-test.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://github.com/NDLANO/Issues/issues/3143
Må sammenlignes med: https://github.com/NDLANO/listing-frontend/pull/173
=> Move most translations to frontend packages

packages/designmanual/dummydata/mockExplanationService.js, packages/ndla-listview/src/ListView.tsx
Closing https://github.com/NDLANO/Issues/issues/3140
=> Fix hide filter if empty

packages/designmanual/stories/molecules/MyNdlaAddToFavoritesExample.tsx, packages/designmanual/stories/molecules/SnackbarExample.tsx, packages/ndla-ui/src/SnackBar/SnackBar.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
• Redesign
• Label (close) from i18n
• Can add button (generic for stuff like show/regret etc)
=> qa snackbar, add action buttons

packages/designmanual/dummydata/mockResources.js, packages/designmanual/stories/molecules/resources.jsx, packages/designmanual/stories/pages/ArticleAdditional.jsx, packages/designmanual/stories/pages/ArticleAssessmentResource.jsx, packages/designmanual/stories/pages/ArticleExercise.jsx, packages/designmanual/stories/pages/ArticleExternalLearningResource.jsx, packages/designmanual/stories/pages/ArticleLearningmaterial.jsx, packages/designmanual/stories/pages/ArticleSourceMaterial.jsx, packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/Article/ArticleFavoritesButton.tsx, packages/ndla-ui/src/Article/index.ts, packages/ndla-ui/src/ResourceGroup/ResourceGroup.tsx, packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx, packages/ndla-ui/src/ResourceGroup/ResourceList.tsx, packages/ndla-ui/src/index.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, packages/ndla-ui/src/types.ts
Add to Favorites button in Resources
Add to Favorites button in Articles
(uses same button)
Trello: https://trello.com/c/ulZth8Gi/8-hjerte-ressurser-i-launchpad
Trello: https://trello.com/c/HmwlnZKO/3-hjerte-artikkelside
=> added Add to favorites to Resources

packages/ndla-ui/src/Breadcrumb/HeaderBreadcrumb.tsx
Manglet hvit variant av breadcrumb med header (den som brukes i Masthead) til ndla film.
=> Add light version of header breadcrumb

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Ikkje bytta bilder/lisensar på bilder.
=> Skulestart 2022: nye blogginnlegg

packages/designmanual/.storybook/designmanual.scss, packages/designmanual/stories/ComponentInfo.jsx, packages/designmanual/stories/atoms/TooltipExample.jsx, packages/designmanual/stories/simple-components.jsx, packages/ndla-licenses/package.json, packages/ndla-licenses/src/LicenseByline/LicenseIconList.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenu.tsx, packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx, packages/ndla-ui/src/Search/ActiveFilters.jsx, packages/ndla-ui/src/Search/ContentTypeResult.tsx, packages/ndla-ui/src/SearchTypeResult/ActiveFilters.tsx, packages/ndla-ui/src/TopicIntroductionList/TopicIntroduction.tsx, packages/ndla-ui/src/TopicIntroductionList/TopicShortcutItem.tsx, packages/ndla-ui/src/all.scss, packages/tooltip/README.md, packages/tooltip/package.json, packages/tooltip/src/Tooltip.tsx, packages/tooltip/src/all.css, packages/tooltip/webpack.config.js, yarn.lock
=> Skrive om Tooltip med ReachUI

packages/designmanual/stories/atoms/ButtonExample.js
Bare endringer i designmanualen.
=> Add some button example helpers to drastically reduce code size

packages/ndla-ui/package.json
Manglende dependency krasjet tester i f.eks ndla-frontend
=> Add `ndla-editor` to `ndla-ui` dependencies

packages/ndla-editor/package.json, packages/ndla-editor/src/FileListEditor.tsx, packages/ndla-ui/package.json, packages/ndla-ui/src/TreeStructure/FolderNameInput.tsx
En syklisk avhengighet innført fordi Spinner ble importer i `ndla/ui` fra `ndla/editor` og ikke som relativ import fra `ndla/ui`
=> Fix cyclic dependency

packages/button/src/MenuButton.tsx, packages/core/src/colors.ts, packages/designmanual/stories/molecules/TreeStructureExample.tsx, packages/ndla-icons/src/action/TrashCanOutline.tsx, packages/ndla-icons/src/action/index.ts, packages/ndla-icons/src/common/Tag.tsx, packages/ndla-icons/svg/action/TrashCanOutline.svg, packages/ndla-ui/src/TreeStructure/FolderItem.tsx, packages/ndla-ui/src/TreeStructure/FolderItems.tsx, packages/ndla-ui/src/TreeStructure/TreeStructure.tsx, packages/ndla-ui/src/TreeStructure/TreeStructure.types.ts, packages/ndla-ui/src/TreeStructure/TreeStructureWrapper.tsx
• Optional children passed to tree structure for rendering dots/menu for folder items
• Adjustments to MenuButton, minor styling + z-index fix
=> Add menu dots to tree structure

packages/designmanual/stories/molecules/TagSelectorExample.tsx, packages/designmanual/stories/pages/SubjectPage.jsx, packages/ndla-ui/src/TagSelector/SuggestionInput.tsx, packages/ndla-ui/src/TagSelector/Suggestions.tsx, packages/ndla-ui/src/TagSelector/TagSelector.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
• Better suggestion handling
• Show rest of the word as "placeholder"-text
• No spacing allowed in tags + logic for adding space key
• Backspace removes tags (if any and when input === '')
• Label updates
• Animation so we better see the tags we add (onAdd)
• Do not sort tags, last one we added will be shown last, less confusion for user.
=> Tag selector qa ux

packages/button/src/MenuButton.tsx, packages/designmanual/stories/molecules/MyNdlaResourceView.tsx, packages/designmanual/stories/molecules/TreeStructureExample.tsx, packages/designmanual/stories/molecules/breadcrumbs.tsx, packages/designmanual/stories/pages/MyNdla.tsx, packages/ndla-ui/src/MyNdla/Resource/Folder.tsx, packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx, packages/ndla-ui/src/Resource/resourceComponents.tsx
Kan nå sende inn props til Folder-komponenten for å vise knapp med popup-meny.
Kan teste på "Folder" på denne siden: https://frontend-packages-pr-1204.ndla.sh/?path=/story/min-ndla--elementer
=> Add menuItems prop to Folder

packages/designmanual/stories/pages/MyNdla.tsx, packages/ndla-ui/src/Resource/ListResource.tsx
Tall images now longer go outside own box.
=> :lipstick: Add overflow to StyledImageWrapper in ListResource

packages/ndla-ui/src/Masthead/Masthead.tsx, packages/ndla-ui/src/Messages/MessageBanner.tsx, packages/ndla-ui/src/TopicMenu/TopicMenu.jsx
https://github.com/NDLANO/Issues/issues/3166 
Må sammenlignes med: https://github.com/NDLANO/ndla-frontend/pull/1040
- Er fikset at banner i masthead kan lukkes
- Har lagt til border-bottom for å skille mellom bannere dersom det er flere
=> 3166 banner and masthead

package.json, packages/designmanual/stories/pages/LearningPathExample.jsx, packages/ndla-ui/src/LearningPaths/LearningPathMenu.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuIntro.tsx, yarn.lock
Bumpet også `caniuse` fordi det kom sinnsyke mengder advarsler under install.
=> Add ability to favorite learningpaths

packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaFolderContent.tsx, packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaMyPageContent.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Lagt til translations for minside
=> Add myndla translations

packages/ndla-ui/src/LearningPaths/LearningPathInformation.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuAsideCopyright.tsx
Teksten er nå erstattet med ikoner,
Closing https://github.com/NDLANO/Issues/issues/3165
=> Replace license text with icons

packages/ndla-ui/src/TreeStructure/TreeStructure.tsx
=> Make TreeStrucutre onNewFolder optional

packages/ndla-ui/src/Search/ContentTypeResult.tsx
Closes https://github.com/NDLANO/Issues/issues/3153
=> Remove tab-index on resource links

packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx
Clsoes https://github.com/NDLANO/Issues/issues/3175
=> Remove z-index to make 'Ask NDLA' visible when screen adjusting

packages/ndla-ui/src/ContentLoader/index.tsx, packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Dette var ikke noe kult å gjøre i det hele tatt. Prøvde originalt å lage en diger shimmer for hele komponenten, men det endte opp med å bli for komplisert. Tror dette er beste fremgangsmåten.
=> Loading shimmers for folder resources

packages/designmanual/stories/organisms/CompetenceGoalsExample.jsx, packages/ndla-ui/src/CompetenceGoalTab/CompetenceGoalItem.tsx, packages/ndla-ui/src/CompetenceGoalTab/CompetenceGoalTab.tsx, packages/ndla-ui/src/CompetenceGoalTab/CompetenceItem.tsx, packages/ndla-ui/src/CompetenceGoalTab/SearchButton.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, packages/ndla-ui/src/types.ts
Gjør sånn at søk på kompetansemål fra embedda side ikkje feiler.
NDLANO/Issues#3161
Første steg i å åpne lenker til søk fra embedda sider i nytt vindu. Legger også til manglende oversettelser.
=> Legger til isOembed-parameter og påfølgende target.

packages/button/src/AddButton.tsx, packages/button/src/MultiButton.tsx, packages/ndla-ui/src/TreeStructure/FolderItem.tsx, packages/ndla-ui/src/TreeStructure/TreeStructure.tsx, packages/ndla-ui/src/TreeStructure/TreeStructureWrapper.tsx, packages/ndla-ui/src/TreeStructure/types.ts, yarn.lock
AddButton / "Ny mappe"-knapp:    
- /?path=/story/min-ndla--elementer   ----> På side  
- Fjernet padding slik at elementet aligner bedre med andre elementer.
- Lagt til offset på outline slik at det blir litt luft mellom knappens innhold og outline.
Trestruktur:
- ?path=/story/enkle-komponenter--treestruktur-komponent
- Blå outline ved tabbing/pilnavigering
- Trestruktur som ikke er framed har ikke fullwidth bakgrunn på mappene (se siste eksempel)
- Ved oppretting av ny mappe trigges onSelectFolder (kan ikke testes i frontend-packages)
=> My ndla fixes

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, yarn.lock
Lagt til to nye translations for info og knapp for sletting av konto.
=> Myndla translations

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/7upCp59j/98-tooltip-p%C3%A5-view-options
=> Fix card view translations

packages/ndla-ui/src/Article/ArticleFavoritesButton.tsx
https://trello.com/c/DfEfAUuk/148-feil-aria-label-p%C3%A5-hjerter
=> Reverse add to favorites aria labels

packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/YbzUmuFm/128-metabilder-hentes-i-un%C3%B8dig-stor-filst%C3%B8rrelse
https://trello.com/c/G9gBh00p/131-veiledning-om-hjerter-blir-feil-for-l%C3%A6ringssti
=> Add max width for my ndla resource images. Fix storage info translation

packages/ndla-ui/src/MyNdla/Resource/FolderInput.tsx, packages/ndla-ui/src/TreeStructure/FolderItems.tsx, packages/ndla-ui/src/TreeStructure/FolderNameInput.tsx
https://trello.com/c/kjxkX28r/108-n%C3%A5-jeg-skal-lage-ny-mappe-savner-jeg-en-lagre-knapp-fordi-jeg-ikke-vet-at-jeg-kan-m%C3%A5-trykke-enter-for-%C3%A5-f%C3%A5-mappen-lagret og en hel haug med andre kort. Kritiser gjerne design.
=> Add confirm button to folder name inputs

packages/ndla-ui/src/TagSelector/SuggestionInput.tsx, packages/ndla-ui/src/TreeStructure/FolderNameInput.tsx, packages/ndla-ui/src/TreeStructure/TreeStructure.tsx
https://trello.com/c/xnSAmtRk/159-f%C3%A5r-to-mapper-hvis-jeg-trykker-enter-veldig-raskt-to-ganger-p%C3%A5-rappen
=> Unset new folder input after clicking enter or tab

packages/ndla-ui/src/User/UserInfo.tsx
https://trello.com/c/KYG8uPhK/165-spionere-anonymt-takk
=> Suppress user info in hotjar

packages/ndla-ui/src/Navigation/NavigationHeading.tsx, packages/ndla-ui/src/Programme/Programme.tsx
Gjør det mulig å skippe til hovedinnhold på program- og fag-sider.
=> Make navigation headings programmatically tab accessible

packages/ndla-ui/src/Masthead/MastheadSearchModal.tsx, packages/ndla-ui/src/Search/SearchField.tsx, packages/ndla-ui/src/Search/SearchFieldForm.tsx
Fixes https://github.com/NDLANO/Issues/issues/3220
Kan sjekkes ved å kjøre en skjermleser og teste ut søkefeltene i masthead og på forsiden. Sammenlign med f.eks w3.org
=> Add aria labels to front page and masthead search

packages/ndla-licenses/src/licenses.ts
viss ein har med www. i url får ein sertifikatfeil.
=> delrett.no - fiks

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Retta tilsvarande på nn, nb, en
en: 'This is not a complete course, but a collection of resources we hope you will find useful.',
nb: 'Dette er ikke et komplett læremiddel, men ei ressurssamling som vi håper kan være nyttig for deg.',
nn: 'Dette er ikkje eit komplett læremiddel, men ei ressurssamling som vi håper kan vere nyttig for deg.',
=> Justere varseltekst på ressurssamlinger

packages/designmanual/stories/pages/SubjectPage.jsx, packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
=> La til aria-label på tilleggsressurser

packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/my-ndla.jsx, packages/designmanual/stories/pages/index.jsx, packages/ndla-ui/src/ErrorMessage/ErrorMessage.tsx, packages/ndla-ui/src/Subject/SubjectHeader.tsx
/story/min-ndla--feilmelding
La til feilmeldingsside for når innlogging feiler for minNDLA
https://trello.com/c/xVOoBjjh/155-feil-ved-innlogging-via-bunn
=> Login Feilet

packages/ndla-ui/src/Article/ArticleByline.tsx
Fixes https://github.com/NDLANO/Issues/issues/3258
=> Do not escape ampersands in ArticleByline

packages/ndla-forms/src/InputV2.tsx
Feilmeldinger blir nå lest opp automatisk når de oppstår.
=> Add aria-assertive to ErrorText if it exists. Align error text with input

packages/designmanual/stories/molecules/MyNdlaAddToFavoritesExample.tsx, packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaFolderContent.tsx, packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaMyPageContent.tsx, packages/designmanual/stories/molecules/MyNdlaResourceView.tsx, packages/designmanual/stories/pages/MyNdla.tsx, packages/designmanual/stories/pages/MyNdlaMyPage.tsx, packages/ndla-ui/src/MyNdla/Resource/Folder.tsx, packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Relatert til fokushåndtering i lister.
=> Add translations and ability to pass id to folder and resource components

packages/ndla-ui/src/Breadcrumb/Breadcrumb.tsx
Fixes https://github.com/NDLANO/Issues/issues/3274
=> Use href as key to avoid having new breadcrumbs rendered every render

packages/button/src/MenuButton.tsx, packages/ndla-ui/src/Breadcrumb/ActionBreadcrumb.tsx
=> Prevent default on keydown for MenuPopover

packages/ndla-ui/src/i18n/i18n.ts, packages/ndla-ui/src/index.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, packages/ndla-ui/src/types.ts
Legger til se som kode der det trengs.
=> Forbereder støtte for nordsamisk språk i frontend.

packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaFolderContent.tsx, packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaMyPageContent.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/H12qzkdJ/205-oppdatere-dette-henter-vi-om-deg-fra-feide-til-dette-henter-vi-om-deg-gjennom-feide-og-setning-om-hva-man-skal-gj%C3%B8re-om-informas
Endret teksten etter forespørsel.
=> Feide Info Tekst

packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
=> verktøykassa: masse -> mange

packages/ndla-ui/src/Frontpage/FrontpageAllSubjects.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, packages/ndla-ui/src/model/SubjectCategories.ts
Legger til phrase for å få til forside med ressurser fra taksonomi.
=> Sletter gamle data 

packages/designmanual/stories/atoms/DrawerExample.tsx, packages/designmanual/stories/atoms/ModalV2Example.tsx, packages/designmanual/stories/simple-components.jsx, packages/ndla-modal/src/Drawer.tsx, packages/ndla-modal/src/ModalHeaderV2.tsx, packages/ndla-modal/src/ModalV2.tsx, packages/ndla-modal/src/StyledDialogOverlay.tsx, packages/ndla-modal/src/animations.ts, packages/ndla-modal/src/index.ts, packages/ndla-modal/src/modalStyles.ts, packages/ndla-modal/src/types.ts
https://trello.com/c/acOmU35k/178-ny-navigasjon-via-skuff
Ligger eksempler på begge i designmanualen!
=> Create a more malliable modal, allowing for ease of styling. Also added a specialized Modal, the Drawer

packages/designmanual/stories/molecules/MyNdlaAddToFavoritesExample.tsx, packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaFolderContent.tsx, packages/designmanual/stories/molecules/MyNdlaPages/MyNdlaMyPageContent.tsx, packages/designmanual/stories/molecules/MyNdlaResourceView.tsx, packages/designmanual/stories/organisms/ResourcesExample.tsx, packages/designmanual/stories/pages/MyNdla.tsx, packages/designmanual/stories/pages/MyNdlaMyPage.tsx, packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx, packages/ndla-ui/src/Resource/resourceComponents.tsx, packages/ndla-ui/src/model/ContentType.ts, packages/ndla-ui/src/model/index.ts
Da slipper vi å endre dataen på to forskjellige måter i frontenden hvert eneste sted en ressurs brukes.
=> Rewrote List- and BlockResource to accept a list of resourcetypes

packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx
https://trello.com/c/aaOahs7p/233-uu-feil-tittelniv%C3%A5er-repeterende-h2
=> Add dynamic title levels

packages/ndla-notion/src/Notion.tsx, packages/ndla-ui/src/Notion/ConceptNotion.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Oppdaterte synligheten til begrepsforklaring på etterspørsel:
https://trello.com/c/adhybj8e/209-begrepslenker-i-tekst-er-for-svak-og-lite-synlig
Gjorde også at den lyser opp ved fokus for å vise at den er selected ved tabbing.
=> Oppdaterte begrepsikon synlighet i design

packages/ndla-ui/src/SearchTypeResult/SearchItem.tsx, packages/ndla-ui/src/SearchTypeResult/SearchItemList.tsx, packages/ndla-ui/src/SearchTypeResult/components/ItemResourceHeader.tsx, packages/ndla-ui/src/SearchTypeResult/components/ItemTopicHeader.tsx
OBS. ikke ferdig. 
Underveis på å fjerne merkelig hover funksjonalitet på søkesiden.
https://trello.com/c/St1WybB3/210-rydde-hoverstiling-av-kortvisning-i-s%C3%B8keresultat
I følge designer skal ingenting bevege seg eller bytte plassering på hover.
=> fjerner merkelig hover funksjonalitet

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Gjør klar translations for alt-bilde på forsiden av min ndla. Se https://trello.com/c/LvaVD9S0/239-sirkelbildet-b%C3%B8r-endre-alttekst
=> Add myndla mypage image alt translations

packages/ndla-ui/src/locale/messages-nn.ts
https://trello.com/c/UxfYycps/264-test-6-oktober-jeg-vil-hjertemerke-en-artikkel-jeg-har-hjertemerket-fra-f%C3%B8r-av-jeg-pr%C3%B8ver-%C3%A5-legge-den-i-samme-mappe-men-lagre-er
=> Change 'legg til mappe/tag' to 'legg til mappe/emneknagg' for nn

packages/ndla-ui/src/User/UserInfo.tsx, packages/ndla-ui/src/User/__tests__/parseUserObject-test.ts, packages/ndla-ui/src/User/apiTypes.ts, packages/ndla-ui/src/User/parseUserObject.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fixes https://github.com/NDLANO/Issues/issues/3243
Viser mobilnummer, foretrukket språk og eventuelle grepkoder dersom dataen eksisterer. Kan testes ved å linke ndla-ui inn i ndla-frontend.
=> Show phone number and preferred language if present. Show grep codes if present

packages/button/src/MenuButton.tsx, packages/ndla-ui/src/MyNdla/Resource/Folder.tsx, packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx, packages/ndla-ui/src/Resource/resourceComponents.tsx
Implementerer sykkeldesign på mappe og ressurs. Dette for å få bedre visning på telefon og andre smaler skjermer. Send melding for link til figma-skisser
Kan og burde testes sammen med https://github.com/NDLANO/ndla-frontend/pull/1167 slik at man kan se de forskjellige visningene i bruk.
Hva som må testes:
- Sammenlikne design med figmaskisser.
- Teste i applikasjon og se om det er tilfeller der designet brekker.
- Sjekke at alle klikkbare elementer i ressurs og mappe har en størrelse på minst 44x44px
=> Myndla wcag size

package.json, packages/eslint-config-ndla/package.json, packages/ndla-accordion/src/AccordionSection.tsx, packages/ndla-accordion/src/Accordions.tsx, packages/ndla-accordion/src/accordionUtil.ts, packages/ndla-editor/src/SlateBlockMenu.tsx, packages/ndla-editor/src/ndlaFilm/ThemeEditorModal.tsx, packages/ndla-listview/src/ListView.tsx, packages/ndla-ui/src/Article/ArticleHeaderWrapper.tsx, packages/ndla-ui/src/Footer/FooterLinks.tsx, packages/ndla-ui/src/Frontpage/FrontpageFilm.tsx, packages/ndla-ui/src/Frontpage/FrontpageMultidisciplinarySubject.tsx, packages/ndla-ui/src/Frontpage/FrontpageToolbox.tsx, packages/ndla-ui/src/LearningPaths/LearningPathLastStepNavigation.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuAside.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMobileHeader.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMobileStepInfo.tsx, packages/ndla-ui/src/Masthead/MastheadSearchModal.tsx, packages/ndla-ui/src/Messages/MessageBox.tsx, packages/ndla-ui/src/NDLAFilm/CategorySelect.tsx, packages/ndla-ui/src/SearchTypeResult/ActiveFilterContent.tsx, packages/ndla-ui/src/SearchTypeResult/SearchHeader.tsx, packages/ndla-ui/src/SearchTypeResult/SearchNotionsResult.tsx, packages/ndla-ui/src/SearchTypeResult/SearchTypeHeader.tsx, packages/ndla-ui/src/Subject/SubjectCarousel.tsx, packages/ndla-ui/src/ToolboxPage/ToolboxInfo.tsx, packages/ndla-ui/src/utils/createUniversalPortal.tsx, packages/util/src/createUniversalPortal.tsx, yarn.lock
Fikk problemer med typesjekking av `WithTranslation` HoC'en på ny typescript-versjon så jeg skrev om til å bruke hook'en alle steder HoC'en var i bruk.
Kan testes ved å sjekke at alt funker som før, spesielt ndla-film og artikler kanskje siden der de største omskrivingene var (selvom alle var ganske små :smile:)
=> Bump typescript version

packages/ndla-ui/src/index.ts
Trenger en checkbox i https://github.com/NDLANO/editorial-frontend/pull/1590
=> Export toggle item from @ndla/ui

packages/button/src/Button.tsx, packages/button/src/ButtonV2.tsx, packages/button/src/IconButton.tsx, packages/button/src/IconButtonV2.tsx, packages/button/src/MultiButton.tsx, packages/button/src/MultiButtonV2.tsx, packages/button/src/index.ts, packages/designmanual/stories/atoms/ButtonExample.js, packages/designmanual/stories/atoms/ButtonV2Example.tsx, packages/designmanual/stories/collated-components.jsx, packages/designmanual/stories/simple-components.jsx
Har skrevet om multibutton til å ta i bruk buttonV2. 
button type="submit" skapte problemer igjen fordi det automatisk submitter formik og andre forms, i dette tilfellet artikkelform i ed. Har derfor gjort type="button" som default i knappene. Dette var også default i Button v1.
Test i designmanual:
Se /?path=/story/enkle-komponenter--knapper og sammenlikn design og funksjonalitet med samme side i designmanual.ndla.no
Test i applikasjon:
Link inn button i ed (og mulig ndla-ui from å unngå feilmelding):
https://github.com/NDLANO/editorial-frontend/pull/1592
=> Multibutton v2

packages/ndla-ui/src/TopicMenu/TopicMenu.jsx
Fixes https://github.com/NDLANO/Issues/issues/3313
=> Close masthead menu when navigating to front page

packages/designmanual/package.json, packages/ndla-code/package.json, packages/ndla-code/src/Codeblock/Codeblock.tsx, yarn.lock
Slipper unna en ufin xss-vuln fra Prism.
=> Update prism to avoid vuln

packages/ndla-ui/src/User/apiTypes.ts
Trengs for å kunne sende fylke til tagmanager.
=> Add baseOrg to be able to send to GA

css.webpack.config.js, package.json, packages/button/package.json, packages/ndla-ui/package.json, packages/ndla-ui/webpack.config.js, packages/tooltip/package.json, packages/tooltip/webpack.config.js, yarn.lock
Påvirker kun generering av css fra scss.
=> Upgrade webpack-cli

packages/core/scss/global/settings/settings.colors.scss, packages/core/src/colors.ts, packages/designmanual/stories/basic-styles.jsx
Oppdater dokumentasjon til å bruke faktiske farger, samt legg til manglende.
Fixes NDLANO/Issues#3335
=> Ny kontrastfarge for oppgaver og aktiviteter

packages/ndla-ui/package.json, yarn.lock
=> Update learningpath types in ui

package.json, yarn.lock
Default-port gikk fra å være 5000 til 3000, så må sette 5000 eksplisitt for å ikke innføre noe breaking. 
Fikser https://github.com/NDLANO/frontend-packages/security/dependabot/54
Fikser https://github.com/NDLANO/frontend-packages/security/dependabot/7
Fikser https://github.com/NDLANO/frontend-packages/security/dependabot/5
Fikser https://github.com/NDLANO/frontend-packages/security/dependabot/8
=> Update serve package

scripts/build.js
Gir ikke helt mening å ha `.stories`-filer publisert på NPM.
=> Do not add storybook files to build folders

packages/designmanual/stories/pages/ResourceBoxExample.jsx, packages/ndla-ui/README.md, packages/ndla-ui/src/ResourceBox/ResourceBox.tsx
…cle-converter
NDLANO/Issues#3354
=> Fjerner bruk av useTranslation fra ResourceBox fordi denne brukes i article-converter

packages/carousel/package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/Filter/FilterCarousel.tsx, yarn.lock
=> Bump react-swipeable for react 18 compat

packages/ndla-code/src/Codeblock/Codeblock.tsx
Fixes https://github.com/NDLANO/Issues/issues/3319
Ganske vanskelig å targette stylingen til denne komponenten. Tror dette er det nærmeste jeg kommer.
=> Change styling to adapt to inline line numbers

packages/ndla-ui/src/Image/Image.tsx, packages/ndla-ui/src/Image/ImageLink.tsx, packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap, packages/tooltip/src/initTooltips.tsx
Fixes https://github.com/NDLANO/Issues/issues/3357
=> Ensure that svg's placed in Image components always takes up the available width and height

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Brukes for å gå tilbake til toppnivå i skuffen.
=> Add a translation for navigating back to the main menu

packages/ndla-ui/src/Footer/FooterPrivacy.tsx, packages/ndla-ui/src/locale/messages-nn.ts
Glemte å forandre teksten på den ene linken fra forrige PR. Fjernet også noe ubrukt kode som jeg fant.
=> Fixed typo

packages/ndla-ui/src/SearchTypeResult/SearchItemList.tsx
Fixes https://github.com/NDLANO/Issues/issues/3364
=> Fix image scale crop on safari search list view

packages/ndla-ui/src/Footer/FooterPrivacy.tsx
La til spacing mellom linkene i footeren.
=> La til spacer mellom privacy links

packages/ndla-ui/src/Footer/FooterPrivacy.tsx
Lars har nå idag lært å ikke noen gang herved lage PR i frontend-packages uten å dobbeltsjekka alt, selv om det er en liten endring.
=> Fixed styling error from earlier pr

packages/ndla-ui/src/Figure/FigureLicenseDialog.tsx
Gir ikke mening å starte på h3 i en modal.
=> Use h1 for figure dialog title

packages/ndla-howto/src/StaticInfoComponents/index.ts
=> Fjerner youtube fra video. Legger til podkast.

packages/button/src/MenuButton.tsx
Fikser en feil der menubutton ikke lukkes etter trykk på valg. Det er viktig å teste at dette fungerer på min ndla på en ressurs.
Hvordan teste:
Link inn button og ndla-ui i ndla-frontend
Åpne min ndla og gå til en mappe som har ressurs
Bruk både mus, enter og click til å teste at menyknapp fungerer og lukker seg ved menyvalg. Bekreft også at det ikke skjer en uventet navigering til den markerte ressurser.
=> Close MenuButton on click or keydown

packages/button/src/ButtonV2.tsx
Gjør også mer av css'en statisk. Tror det er mer performant.
=> Ensure that IconButton contents are not white when not in active state

packages/ndla-ui/src/ResourceGroup/ResourceGroup.tsx, packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
Fixes https://github.com/NDLANO/Issues/issues/3388
=> Fix tooltip errors in ResourceList

packages/ndla-ui/src/Footer/Footer.tsx, packages/ndla-ui/src/Footer/FooterLinks.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
* Add label to footer navs
* Make h1 heading h3.
* Remove sections in favor of navs.
* Move feide auth inside of footer
=> Footer accessibility changes.

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Oversettelser hovedsakelig til bruk for skjermleser på fagsiden på ndla.no
=> Add translations for subjects page

packages/ndla-licenses/src/licenseRights.ts, packages/ndla-licenses/src/licenses.ts
=> public domain

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Mangler oversettelser for "Mine favorittfag"
=> Add my favorite subjects translation

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fikser https://trello.com/c/C2EZiUyr/88-legge-til-faglig-ved-oppdatert-dato
=> Add "faglig" to lastUpdated for article.

packages/ndla-ui/src/LearningPaths/LearningPathMenuContent.tsx
Fixes https://github.com/NDLANO/Issues/issues/3406
=> Add describedby to indicate whether a learning step has been read or not

packages/ndla-ui/src/LanguageSelector/LanguageSelector.tsx
NDLANO/Issues#3425
https://trello.com/c/qQLDDMh2/104-uu-spr%C3%A5kvelger
Endring:
- Flytter radio til venstre side
- Legger på litt padding på sidene for å matche design bedre
- Endret bakgrunn til hvit som i designet
- Fjern outline ved hover/aktiv-markering av valg.
=> Designendringer LanguageSelector

packages/types-embed/package.json, packages/types-embed/src/audioTypes.ts, packages/types-embed/src/brightcoveTypes.ts, packages/types-embed/src/codeTypes.ts, packages/types-embed/src/conceptTypes.ts, packages/types-embed/src/contentLinkTypes.ts, packages/types-embed/src/externalTypes.ts, packages/types-embed/src/fileTypes.ts, packages/types-embed/src/footnoteTypes.ts, packages/types-embed/src/h5pTypes.ts, packages/types-embed/src/iframeTypes.ts, packages/types-embed/src/imageTypes.ts, packages/types-embed/src/index.ts, packages/types-embed/src/relatedContentTypes.ts, packages/types-embed/tsconfig.build.json, scripts/_getPackages.js, yarn.lock
Originalt opprettet i https://github.com/NDLANO/frontend-packages/pull/1514, men vi trenger den merget inn for å kunne ta graphql videre.
=> Add @ndla/types-embed package

dummydata/mockPrograms.js, packages/core/scss/global/settings/settings.colors.scss, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-sma.ts, stories/basic-styles.jsx, stories/molecules/mastheads.jsx, stories/pages/NdlaFilmFrontpage.jsx, stories/pages/index.jsx, stories/produksjonssystem/index.js
Språkfolka melder om at NDLA Film skal skrivast NDLA film.
=> Film -> film

packages/ndla-licenses/src/licenses.ts
=> Feil nynorsktekst i PD-lisensinfo

package.json, packages/hooks/package.json, packages/ndla-scripts/package.json, packages/ndla-tabs/package.json, packages/ndla-ui/package.json, packages/tooltip/package.json, yarn.lock
Sniker inn en liten bump av react-device-detect også.
=> Minor bump octokit to fix vuln

packages/ndla-ui/src/User/apiTypes.ts, packages/ndla-ui/src/User/index.ts, packages/ndla-ui/src/index.ts
Glemte å propagere exporten av AffiliationType
=> fix export of AffiliationType and change eduPersonPrimaryAffiliation

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
La til nye oversettinger til deling av mapper for min NDLA.
=> Added local for folder sharing modal

packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx, packages/ndla-ui/src/Embed/ExternalEmbed.tsx, packages/ndla-ui/src/Embed/H5pEmbed.tsx, packages/ndla-ui/src/Embed/IframeEmbed.tsx, packages/ndla-ui/src/Embed/conceptComponents.tsx
Tror dette skal sørge for bedre resizing av iframes!
=> Unset height and width after setting aspect ratio on iframe embeds

packages/ndla-tracker/src/MatomoTagManager.tsx, packages/ndla-tracker/src/index.ts
NDLANO/Issues#3484
Henter kode fra trello.
=> Add matomo tagmanager

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://docs.google.com/spreadsheets/d/1LAeIhx3wze8hJ-YqY4-Gu2M_qXv5jcLOfpO6I_Bo7-k/edit
=> New translations for sharing

packages/ndla-ui/src/Footer/Footer.tsx, stories/collated-components.jsx, stories/molecules/footers.jsx, stories/pages/index.jsx
Fixes https://github.com/NDLANO/Issues/issues/3489
Dette kommer nok til å kreve at vi gjør en liten endring i ED, samt at vi alltid må sette `inverted` i ndla-frontend.
=> Move Language Selector into footer

packages/article-converter/src/plugins/divPlugin.tsx
Fikser bugen vi fant i article-converter under testing. 
Kan testes på https://test.ndla.no/nn/subject:1:26a01df2-376e-4090-b0bf-eec2ca3d41dd/topic:2:192655/resource:1:191206
=> Expand bodyboxes when they contain a table

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/Rs64cASO/314-test-deling-tekst-i-modal-for-deling
=> Add an additional description line when sharing a folder

packages/ndla-pager/src/Pager.stories.tsx, packages/ndla-pager/src/Pager.tsx, stories/collated-components.jsx
Legger til small og colorTheme som options for Pager. Legger også til story for Pager.
Kan kanskje liksågreit slette [denne her](https://designmanual.ndla.no/?path=/story/sammensatte-moduler--paginering) i samme PR?
=> Updates Pager

packages/types-embed/src/index.ts
Glemte å legge til export i index
=> Added export to index

packages/ndla-ui/src/Image/Image.tsx, packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap
relates to https://github.com/NDLANO/Issues/issues/3466
Testet dette på flere artikler fant ingen som oppførte seg annerledes enn på test.
=> Flex display on image wrapper, image justified center

packages/button/src/MenuButton.tsx, packages/ndla-ui/src/MyNdla/Resource/Folder.tsx, packages/ndla-ui/src/MyNdla/Resource/FolderMenu.tsx, packages/ndla-ui/src/MyNdla/SettingsMenu.tsx, packages/ndla-ui/src/MyNdla/index.ts, packages/ndla-ui/src/Resource/BlockResource.tsx, packages/ndla-ui/src/Resource/ListResource.tsx, packages/ndla-ui/src/index.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/LgHWePa7/322-meny-p%C3%A5-mobil-min-ndla
=> New settings menu for my ndla

package.json, scripts/build.js, yarn.lock
String-length brukes bare til statiske formål. Da trenger vi det egentlig ikke.
=> Remove string-length in favor of constant number

packages/article-converter/src/plugins/embed/blogPostEmbedPlugin.tsx, packages/article-converter/src/plugins/embed/index.ts, packages/ndla-ui/src/BlogPost/BlogPost.stories.tsx, packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/BlogPost/index.ts, packages/ndla-ui/src/index.ts, packages/types-embed/src/blogPostTypes.ts, packages/types-embed/src/index.ts
Fixes https://github.com/NDLANO/Issues/issues/3510
Usikker på om vi skal kalle det bloggpost, eller om vi skal kalle det noe annet.
=> Create new Blog Post embed

package.json, packages/ndla-ui/src/TreeStructure/TreeStructure.tsx, packages/types-embed/src/audioTypes.ts, yarn.lock
relates to https://github.com/NDLANO/backend/pull/211
=> Types from types-backend

packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/types-embed/src/blogPostTypes.ts
Ble først oppdaget når jeg satt inn en bloggpost i ED.
=> Ensure that image takes up remaining space without overflowing author text

packages/ndla-ui/src/TreeStructure/FolderItem.tsx, stories/molecules/TreeStructureExample.tsx
Fikser litt av https://trello.com/c/Gtd4zVDI/342-markere-delt-mappe-n%C3%A5r-man-legger-til-ny-ressurs
=> Shared icon for tree structure

packages/eslint-config-ndla/base.js, packages/eslint-config-ndla/package.json, yarn.lock
Dette bør gjøre det litt greiere å holde bundle-størrelsen vår i sjakk.
=> Disallow importing from lib, es and src directories

package.json, packages/ndla-audio-search/package.json, packages/ndla-image-search/package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/Embed/RelatedContentEmbed.tsx, packages/ndla-ui/src/RelatedArticleList/RelatedArticleV2.tsx, packages/types-embed/package.json, packages/types-embed/src/relatedContentTypes.ts, yarn.lock
Prøver å gjøre komponenten brukbar både i ED og i ndla-frontend, uten å inngå for mange kompromisser.
=> Pass props through to RelatedArticleListV2. Allow passing buttons into heading row

packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx, packages/ndla-ui/src/Embed/BrightcoveEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/types-embed/src/index.ts
I all hovedsak disse fire som vil endre seg med ny byline, så starter med disse.
=> Add stories for the big 4 embeds

packages/select/src/Select/Select.tsx
Trengs for å knytte `label` til `select` blandt annet
=> Add id field to select

packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx
Fikser delvis https://github.com/NDLANO/Issues/issues/3544
=> Flip brightcove vt buttons

packages/article-converter/src/plugins/embed/audioEmbedPlugin.tsx, packages/article-converter/src/plugins/embed/imageEmbedPlugin.tsx, packages/ndla-accordion/src/AccordionContent.tsx, packages/ndla-ui/package.json, packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/Article/ArticleByline.tsx, packages/ndla-ui/src/Article/ArticleFootNotes.tsx, packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx, packages/ndla-ui/src/Embed/AudioEmbed.tsx, packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/EmbedErrorPlaceholder.tsx, packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx, packages/ndla-ui/src/Embed/conceptComponents.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.stories.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx, packages/ndla-ui/src/LicenseByline/LicenseDescription.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, stories/molecules/ConceptBlockExample.tsx, stories/molecules/ConceptBlockListExample.tsx
Kjempebreaking for NDLA-frontend. Neppe noe særlig breaking for andre steder. 
Sikkert greit å ikke ta inn denne før eksamensperioden er over, men også sikkert greit å reviewe denne litt innen den tid.
=> New bylines and accordions for article

packages/ndla-ui/src/Embed/EmbedErrorPlaceholder.tsx, packages/ndla-ui/src/Embed/ExternalEmbed.stories.tsx, packages/ndla-ui/src/Embed/ExternalEmbed.tsx, packages/ndla-ui/src/Embed/H5pEmbed.stories.tsx, packages/ndla-ui/src/Embed/H5pEmbed.tsx, packages/ndla-ui/src/Embed/IframeEmbed.stories.tsx, packages/ndla-ui/src/Embed/IframeEmbed.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, packages/types-embed/src/index.ts, yarn.lock
Inneholder også noen småfikser for EmbedByline.
=> Add fail states and stories to IframeEmbed, H5pEmbed and ExternalEmbed

packages/article-converter/src/plugins/embed/campaignBlockPlugin.tsx, packages/article-converter/src/plugins/embed/index.ts, packages/ndla-ui/src/index.ts, packages/types-embed/src/campaignBlockTypes.ts, packages/types-embed/src/index.ts
Har ikke testet, men tror den skal være grei.
=> Add article-converter support and embed types for campaign block

packages/ndla-ui/src/AudioPlayer/SpeechControl.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fixes https://github.com/NDLANO/Issues/issues/3566
Kan sjekkes ved å søke på "lydavspiller" i designmanual.
=> Make use of IconButtonV2 for SpeechControl button

packages/ndla-ui/src/List/OrderedList.tsx, packages/ndla-ui/src/List/UnOrderedList.tsx
Legger til padding på liste elementen. Må overstyre global css for Ul og  Ol når det gjelder paragraph margin og padding-left of Ul
=> Update padding and margin list-style

packages/ndla-ui/src/Embed/AudioEmbed.tsx, packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx, packages/ndla-ui/src/Embed/conceptComponents.tsx
Fixes https://github.com/NDLANO/Issues/issues/3483
=> Do not show heart button on copyrighted embeds

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fikser delvis https://trello.com/c/dqNcEONC/348-sende-tverrfaglig-case-ut-av-kontekst-som-l%C3%A6ringsstier
Fikser https://trello.com/c/ZlFS1mYY/356-tekstforslag-endre-kopier-og-del-denne-lenka-til-trykk-p%C3%A5-lenke-for-%C3%A5-kopiere
=> Change wording for copy link for shared folder and unsupported shared resource items

packages/ndla-ui/src/List/OrderedList.tsx, packages/ndla-ui/src/List/UnOrderedList.tsx, packages/types-embed/src/keyFigureTypes.ts
=> Fixed the margin on lists. Updated padding on unordered list

packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/Embed/BrightcoveEmbed.tsx, packages/ndla-ui/src/Embed/IframeEmbed.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx
Fortsatt litt lodash her som er greit å beholde.
=> Remove redundant usage of lodash in ndla ui

packages/ndla-accordion/src/AccordionItem.tsx
Oppdatere Accordion med ny farge på border og legge til border radius.
https://trello.com/c/A0kySRQz
=> uppdated accordionitem border color and border radius

packages/ndla-ui/src/List/OrderedList.tsx, packages/ndla-ui/src/List/UnOrderedList.tsx
Oppdaterer liste styling etter kommentarer fra Hedvig
=> Fixed margin and padding. Adjusted font size

packages/ndla-ui/src/KeyFigure/KeyFigure.tsx
Fikser design kun ved små telefoner
=> Subtitle design was not triggered

packages/ndla-howto/src/StaticInfoComponents/index.ts
fixes https://github.com/NDLANO/Issues/issues/3521
=> Add BlogPost, ContactBlock and GridBlock how to

packages/article-converter/README.md, packages/button/README.md, packages/hooks/README.md, packages/ndla-accordion/README.md, packages/ndla-audio-search/README.md, packages/ndla-code/README.md, packages/ndla-editor/README.md, packages/ndla-forms/README.md, packages/ndla-howto/README.md, packages/ndla-image-search/README.md, packages/ndla-listview/README.md, packages/ndla-notion/README.md, packages/ndla-pager/README.md, packages/ndla-tabs/README.md, packages/ndla-ui/README.md, packages/ndla-video-search/README.md, packages/ndla-zendesk/README.md, packages/safelink/README.md, packages/tooltip/README.md
=> Arbitrary readme changes for publish

packages/ndla-ui/src/List/OrderedList.tsx, packages/ndla-ui/src/List/UnOrderedList.tsx
=> Added font-size

packages/ndla-tracker/src/tracker.ts
=> Delete ga-tracking. Breaking!

packages/article-converter/src/plugins/divPlugin.tsx, packages/core/src/colors.ts, packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/Grid/Grid.stories.tsx, packages/ndla-ui/src/Grid/Grid.tsx
=> Make grid cells expand to full size

packages/article-converter/src/plugins/ddPlugin.tsx, packages/article-converter/src/plugins/dtPlugin.tsx, packages/article-converter/src/plugins/index.ts, packages/ndla-ui/src/DefinitionList/DefinitionDescription.tsx, packages/ndla-ui/src/DefinitionList/DefinitionTerm.tsx, packages/ndla-ui/src/DefinitionList/index.tsx, packages/ndla-ui/src/index.ts
Definisjonsliste elementene må gå igjennom article-converter da de er komponenter.
=> Added definition element plugins

packages/ndla-ui/src/MultidisciplinarySubject/MultidisciplinarySubject.tsx, packages/ndla-ui/src/MultidisciplinarySubject/MultidisciplinarySubjectHeader.tsx
Relatert til https://github.com/NDLANO/Issues/issues/3455
=> Add breadcrumbs to multidisciplinary headers

packages/core/scss/global/settings/settings.config.scss, packages/core/src/fonts.ts, packages/core/src/spacing.ts, stories/basicStyles/banners.stories.tsx, stories/basicStyles/spacing.stories.tsx
Første steg i endring i standardoppsettet. Skal tas opp i møte med NDLA neste veke.
=> New default base units.

packages/ndla-ui/src/Embed/ImageEmbed.tsx, packages/types-embed/src/audioTypes.ts, packages/types-embed/src/brightcoveTypes.ts, packages/types-embed/src/conceptTypes.ts, packages/types-embed/src/h5pTypes.ts, packages/types-embed/src/imageTypes.ts
I stedet for å gjenbruke en image-prop legger eg heller til nye for alle typer som har egne sider på ndla.no
=> Add new pageUrl prop for several types

packages/ndla-ui/src/Article/ArticleByline.tsx
=> new font sizes for article accordion headers

packages/core/scss/global/elements/_elements.lists.scss
Mikroendring for å unngå hardkoda størrelser.
=> Using spacing to style quote in list.

packages/article-converter/src/plugins/divPlugin.tsx, packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/Grid/Grid.stories.tsx, packages/ndla-ui/src/Grid/Grid.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx
Adjusted sizing of grid elements. KeyFigure sizing is more consisten. Blogpost scales better with long images
=> Grid optimalisering

babel.config.js, scripts/build.js
Denne er litt snillere enn browserslist sin `default`-query. 
https://browsersl.ist/#q=%3E+0.25%25+and+not+dead
=> Set browserslist target for babel

packages/article-converter/src/plugins/embed/imageEmbedPlugin.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx, packages/ndla-ui/src/Image/Image.tsx, packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Enforcer slik at bilder i grid alltid vil bli displayet som ved små skjermer
=> Added vertical byline to images when in grid

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fixes https://github.com/NDLANO/Issues/issues/3608
=> Add resource agnostic add translation for resource/embeds

packages/ndla-ui/src/Image/Image.tsx, packages/ndla-ui/src/Image/__tests__/__snapshots__/Image-test.jsx.snap, packages/ndla-ui/src/types.ts
Fixes https://github.com/NDLANO/Issues/issues/3618
Fikser også en typefeil som oppsto etter merging av react 18.
=> Ensure svg images take up the available space in imageembed

packages/ndla-licenses/src/__tests__/getCopyString-test.ts, packages/ndla-licenses/src/licenses.ts, packages/ndla-licenses/src/types.ts
Fixes https://trello.com/c/gIVk1aTX/308-feil-lisensnavn
Sikkert greit å se nøye gjennom selv om testene går grønt.
=> Add translations for copyrighted and pd abbrevations

packages/article-converter/src/plugins/copyParagraphPlugin.tsx
Fixes https://github.com/NDLANO/Issues/issues/3619
=> Only show copy link on top level h2

packages/ndla-ui/src/MediaList/MediaList.tsx, packages/ndla-ui/src/MediaList/component.medialist.scss, stories/article/LicenseBox.jsx
Kommer en korresponderende PR i ndla-frontend.
=> Re-add media list img icon

packages/ndla-ui/src/Embed/ImageEmbed.tsx
Relatert til https://github.com/NDLANO/ndla-frontend/pull/1432
=> Do not link to images if they are copyrighted

packages/ndla-ui/src/Navigation/NavigationBox.tsx, packages/ndla-ui/src/Programme/ProgrammeSubjects.tsx
Trengs for at data fra https://github.com/NDLANO/graphql-api/pull/343 skal matche bedre med koden.
=> Make props more optional to match backend types.

packages/ndla-ui/src/Programme/ProgrammeSubjects.tsx, packages/ndla-ui/src/ProgrammeCard/ProgrammeCard.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts, stories/molecules/MessageBoxExample.jsx
Desktop og mobile var litt misvisende fordi bredt bilde skal brukes på mobil. Gjorde dei optional slik at vi kan kun laste ned bilda som faktisk skal vises.
Har også justert phrases litt.
=> Rename programme images, and make them optional.

packages/ndla-ui/src/index.ts
=> Export Gloss-component

packages/ndla-ui/src/TreeStructure/ComboboxButton.tsx, packages/ndla-ui/src/TreeStructure/FolderItem.tsx, packages/ndla-ui/src/TreeStructure/FolderItems.tsx, packages/ndla-ui/src/TreeStructure/TreeStructure.tsx
Skal se klin lik ut i begge visningene.
=> No styled props in tree structure

packages/ndla-ui/src/AudioPlayer/AudioPlayer.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
=> No styled props for AudioPlayer. Fix error in EmbedByline

package.json, packages/eslint-config-ndla/base.js, packages/eslint-config-ndla/package.json, packages/ndla-ui/src/AudioPlayer/initAudioPlayers.tsx, packages/ndla-ui/src/CopyParagraphButton/initCopyParagraphButtons.tsx, packages/tooltip/src/Popover/initPopover.tsx, packages/tooltip/src/Tooltip/initTooltips.tsx, yarn.lock
Ganske så breaking, men ser ut som at vi slapp ganske så billig unna.
=> Major bump of tslint

packages/article-converter/src/plugins/embed/linkBlockEmbedPlugin.tsx, packages/article-converter/src/plugins/index.ts, packages/article-converter/src/plugins/navPlugin.tsx, packages/ndla-ui/src/LinkBlock/LinkBlock.stories.tsx, packages/ndla-ui/src/LinkBlock/LinkBlock.tsx, packages/ndla-ui/src/LinkBlock/LinkBlockSection.tsx, packages/ndla-ui/src/LinkBlock/index.ts, packages/ndla-ui/src/index.ts, packages/types-embed/src/index.ts, packages/types-embed/src/linkBlockTypes.ts, packages/types-embed/src/relatedContentTypes.ts
Kommer noe tilsvarende i graphql-api og i ed.
=> Support a list of LinkBlock in article-converter

packages/article-converter/src/plugins/divPlugin.tsx, packages/ndla-ui/src/Grid/Grid.tsx, packages/ndla-ui/src/Grid/index.ts, packages/ndla-ui/src/index.ts
Tar over for https://github.com/NDLANO/frontend-packages/pull/1764
=> Support parallax in grid cells

packages/ndla-licenses/src/__tests__/getCopyString-test.ts, packages/ndla-licenses/src/licenses.ts
Skip uppercase for text-description
=> Remove upper case for license text descriptions

packages/ndla-audio-search/src/AudioBar.tsx, packages/ndla-audio-search/src/AudioSearch.tsx, packages/ndla-audio-search/src/AudioSearchForm.tsx
Skriver om AudioBar, AudioSearch og AudioSearchForm i ndla-audio-search fra klassebasert til å bli funksjonelle
=> Refactor ndla-audio-search to functional

packages/article-converter/src/plugins/embed/index.ts, packages/article-converter/src/plugins/embed/linkBlockEmbedPlugin.tsx, packages/article-converter/src/plugins/navPlugin.tsx, packages/ndla-ui/package.json, packages/ndla-ui/src/ContactBlock/ContactBlock.tsx, packages/ndla-ui/src/LinkBlock/LinkBlock.tsx
contact blocks. Properly format date passed into LinkBlock
=> Fix link block rendering in article-converter. Add spacing between

packages/article-converter/src/plugins/embed/imageEmbedPlugin.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx
Fikser delvis https://github.com/NDLANO/Issues/issues/3655
=> Do not link to images with path equal to page path

packages/ndla-ui/src/Logo/Logo.tsx, packages/ndla-ui/src/NDLAFilm/VisualElement.tsx
Gjør det mulig å vise video på forsida til ndla-film i fullskjerm. 
Legger til title på lenke på logo pga wcag-krav.
=> Remove old properties to fix fullscreen

packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx, packages/ndla-ui/src/FrontpageArticle/FrontpageArticle.tsx, packages/ndla-ui/src/FrontpageArticle/index.ts, packages/ndla-ui/src/index.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Legger for det meste til riktige marginer på overskrifter og kampanjeblokk.
=> Adapt FrontpageArticle styling to fit about NDLA article design

packages/ndla-ui/src/Article/Article.tsx
Fixes https://trello.com/c/blTiP4Ce/354-uu-hopp-til-innhold-mangler
=> Set ID on article heading

packages/ndla-ui/src/Article/ArticleByline.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Fixes https://github.com/NDLANO/Issues/issues/3667
=> Add suppliers to byline. Use dash instead of colon for embed type delimiter

packages/ndla-ui/src/Masthead/Masthead.tsx, packages/ndla-ui/src/Masthead/MastheadSearchModal.tsx, packages/ndla-ui/src/Masthead/index.ts, packages/ndla-ui/src/Search/ToggleSearchButton.tsx, packages/ndla-ui/src/index.ts, stories/collated-components.jsx, stories/molecules/mastheads.jsx
Fjerner også MastheadItem og en masthead-story som kun inneholdt logo.
=> Modify masthead to match new design

packages/ndla-ui/src/TreeStructure/FolderItem.tsx
Oppdaterer visning i trestruktur mappevisning for å bedre indikere hvilke mapper som er på samme nivå
**Tidligere:**
**Nå:**
=> Fix left spacing on folders in TreeStructure

packages/ndla-ui/src/List/OrderedList.tsx, packages/ndla-ui/src/List/UnOrderedList.tsx, stories/basicStyles/lists.stories.tsx
fixes https://github.com/NDLANO/Issues/issues/3687#event-10191697105
Mistet tilgang til listresets når navnet ble forandret. La også til muligheten til å sette start punkt på de andre nivåene
=> Added list start functionality to all levels.

packages/ndla-ui/src/Table/Table.tsx
=> Adding overflow-x to handle table growing outside div

packages/ndla-ui/src/Table/Table.tsx
Overflow styling ble ikke riktig og kutta ut enden av tabellen.
=> Added table scroll design to proper overflow

packages/article-converter/src/plugins/embed/blogPostEmbedPlugin.tsx, packages/article-converter/src/plugins/embed/campaignBlockPlugin.tsx, packages/article-converter/src/plugins/embed/linkBlockEmbedPlugin.tsx, packages/ndla-ui/src/Article/ArticleByline.tsx, packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx, packages/ndla-ui/src/ContactBlock/ContactBlock.tsx, packages/ndla-ui/src/Grid/Grid.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx, packages/ndla-ui/src/LinkBlock/LinkBlock.tsx, packages/ndla-ui/src/utils/relativeUrl.ts
Fixes https://github.com/NDLANO/Issues/issues/3697
Ting som Hedvig har bedt meg fikse. Kommer fler etter vi har fått noen avklaringer til, men denne kan tas inn inntil videre.
=> Even more about UI improvements. Convert NDLA urls to relative urls

packages/safelink/src/SafeLink.tsx
Fjerner også en unødvendig undefined-sjekk!
=> No dynamic styles in safelink. Only create regex once

packages/ndla-ui/src/Footer/FooterPrivacy.tsx, packages/ndla-ui/src/LearningPaths/LearningPathSticky.tsx, packages/ndla-ui/src/Masthead/MastheadSearchModal.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Småting jeg fant med unlighthouse
=> Accessibility improvements

packages/ndla-ui/src/Masthead/SkipToMainContent.tsx
Fixes https://github.com/NDLANO/Issues/issues/3701
Vet ikke hvorfor det brakk. Vet heller ikke hvorfor det funker igjen. Skrev CSS til ting fungerte
=> Make SkipToMainContent work in chrome

packages/ndla-ui/src/TreeStructure/FolderItem.tsx
Fikser at folder item hopper til fokus i trestruktur
=> unecessary ref focus made scrollIntoView jump not smoothly

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/vTAtvvJj/392-skjermleser-iphone-min-ndla
=> Remove italic from login pitch, as it caused screen reader problems

packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx
Etter design-diskusjon med Hedvig.
=> Make campaign block link look like default anchor

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
=> Twitter byttar namn

packages/ndla-ui/src/Table/Table.tsx
Fikser padding og styling av lister i tabell!
=> Updated line-size/height and spacing between list elements

packages/core/scss/global/elements/_elements.lists.scss, packages/ndla-howto/src/Styles.ts, packages/ndla-ui/src/CompetenceGoalTab/CompetenceItem.tsx, packages/ndla-ui/src/List/UnOrderedList.tsx, packages/ndla-ui/src/NDLAFilm/FilmMovieSearch.tsx
Fjerner list-style-image på globalt nivå som vi har allerede gjort på lister i artikler.
=> Remove usage of svg in bullet point list

packages/ndla-editor/src/SlateBlockMenu.tsx, packages/ndla-forms/src/DropdownInput.tsx, packages/ndla-image-search/src/ImageSearchResult.tsx, packages/ndla-image-search/src/PreviewImage.tsx, packages/ndla-modal/src/ModalBody.tsx, packages/ndla-modal/src/ModalCloseButton.tsx, packages/ndla-modal/src/ModalHeader.tsx, packages/ndla-ui/src/Topic/Topic.tsx, packages/ndla-video-search/src/VideoSearchResultBrightcove.jsx, packages/ndla-video-search/src/VideoSearchResultYouTube.jsx, stories/productionSystem/MultiSelectDropdownExample.jsx
Fjewrner også noen ubrukte selectors
=> Rename data cy to testid

packages/ndla-ui/src/Article/ArticleByline.tsx
Får dobbel border når du åpner accordion og matcher ikke designet
=> Removed double border

packages/ndla-ui/src/Search/SearchResultSleeve.tsx
Dette lar oss trykke enter i søkeboksen og lukke søkemodalen.
=> Prevent less events in SearchResultSleeve to make Enter key play more nicely

package.json, packages/ndla-audio-search/package.json, packages/ndla-image-search/package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/ContactBlock/Contactblock.stories.tsx, packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/IframeEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx, packages/ndla-ui/src/types.ts, packages/types-embed/package.json, stories/molecules/ConceptBlockExample.tsx, stories/molecules/ConceptBlockListExample.tsx, yarn.lock
Bare for ordens skyld, ingen funksjonelle endringer
=> Bump '@ndla/types-backend'

packages/ndla-notion/src/Notion.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/ConceptListEmbed.tsx, packages/ndla-ui/src/Embed/conceptComponents.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Oppdaterer conceptEmbed til å støtte gloss også!
=> Added support for gloss in ConceptEmbed

README.md
Oppdaterer så lenkene fungerer! 😄
=> Update links to designmanual from readme

packages/ndla-ui/src/BannerCard/BannerCard.tsx, packages/ndla-ui/src/LearningPaths/LearningPathLastStepNavigation.tsx
Fixes https://trello.com/c/f0KAV2xm/434-manglende-skille-l%C3%A6ringsstiendu
=> Do not place the two "last learning path step" texts within the same heading

packages/ndla-ui/src/FrontpageArticle/FrontpageArticle.tsx
Prøver å gjøre spacing litt bedre på forside og "om ndla".
=> Add spacing between adjacent grids. Do not use LayoutItem

packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Gloss/Gloss.tsx
fixes https://github.com/NDLANO/Issues/issues/3734
Legger også til håndtering av at glossData i Gloss kan være undefined
=> Fix broken ConceptEmbed story

packages/ndla-icons/src/common/LogOut.tsx, packages/ndla-icons/svg/common/LogOut.svg, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Legger til nye navn på meny i tablet form.
=> Logout icon static color

packages/article-converter/src/plugins/embed/blogPostEmbedPlugin.tsx, packages/article-converter/src/plugins/embed/campaignBlockPlugin.tsx, packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx, packages/types-embed/src/blogPostTypes.ts, packages/types-embed/src/campaignBlockTypes.ts
Legger til alt-felt for BlogPost og CampaignBlock
=> Add alt property to BlogPost and CampaignBlock

packages/select/src/Select/BaseOption.tsx, packages/select/src/Select/Select.stories.tsx
Legger til disabled styling til options i Select, relaterer til å kunne få disablet statuser i status select
=> Add disabled styling to select option

packages/ndla-ui/src/MyNdla/Resource/Folder.tsx
Gjør Folder litt mer responsiv til størrelsen vi kjører på frontenden.
=> Adpated the styling to more match the changes on the frontend

packages/ndla-ui/src/Hero/Hero.tsx
=> Remove bottom padding hero for preview on About ndla articles

packages/ndla-licenses/src/licenses.ts
Krever at det opprettes en artikkel: Opphavsrett på ndla.no
=> delrett.no is no more

packages/ndla-icons/src/Icon.stories.tsx, stories/simple-components.jsx, stories/wrappers/IconList.tsx
Fixes https://github.com/NDLANO/Issues/issues/3766
Trengs egentlig noe mer enn dette?
Gjorde noen små styling-endringer på fremvisning av ikon-listen, slik at de ikke endrer størrelse når man hoverer
=> Make new icon story

packages/article-converter/src/plugins/embed/KeyFigureEmbedPlugin.tsx, packages/types-embed/src/keyFigureTypes.ts
Added alt as property to embed
=> Added optional field alt on keyfigures

packages/safelink/src/SafeLink.stories.tsx, packages/safelink/src/SafeLinkButton.stories.tsx, packages/safelink/src/SafeLinkIconButton.stories.tsx, stories/simple-components.jsx
=> Refactor link story. Add stories for SafeLinkButton and

packages/ndla-howto/src/StaticInfoComponents/index.ts
depends on https://github.com/NDLANO/editorial-frontend/pull/2085
=> Update FramedContent howto

packages/ndla-ui/src/Embed/conceptComponents.tsx
fixes https://trello.com/c/o63Ah8U0/479-bugfix-glose-fjerne-ordliste-ord-fra-tittel-glose
=> Hide title for gloss

packages/article-converter/src/plugins/embed/KeyFigureEmbedPlugin.tsx, packages/article-converter/src/plugins/embed/blogPostEmbedPlugin.tsx, packages/article-converter/src/plugins/embed/campaignBlockPlugin.tsx
relates to https://github.com/NDLANO/editorial-frontend/pull/2095
=> Remove image alt text as fallback value for KeyFigure, BlogPost and CampaignBlock

packages/ndla-ui/src/Footer/Footer.stories.tsx, packages/ndla-ui/src/Footer/Footer.tsx, packages/ndla-ui/src/Footer/FooterLinks.tsx
I forbindelse med ny forside flyttes lenker fra frontend-packages til ndla-frontend.
=> Flytter liste med lenker til ndla-frontend.

stories/ndlaUrls.stories.tsx
Fixes https://github.com/NDLANO/Issues/issues/3797
=> Add figma links to ndlaUrls story

packages/ndla-ui/src/ContactBlock/ContactBlock.tsx
Fikser 1 og 2 på https://github.com/NDLANO/Issues/issues/3787
=> Show copyright as link for Contact Block image

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-sma.ts
Forbedra ein del språk. Rettingane kjem frå dei språkallmektige.
=> Podkast: vis mer -> Vis meir

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://github.com/NDLANO/Issues/issues/3815
=> Add gloss license translations

packages/ndla-ui/src/Gloss/Gloss.tsx
Fixes https://github.com/NDLANO/Issues/issues/3816
=> Add language tags to examples and "title"

packages/ndla-ui/src/Gloss/Gloss.tsx
Fixes https://github.com/NDLANO/Issues/issues/3793
Eller vil vi lowercase hele ordet?
=> lowerCase first character of word class

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Tekstene til "Last opp profilbilde" modalen
Tekstene skal inn i [https://github.com/NDLANO/ndla-frontend/pull/1521](url) PRen
=> added texts for upload profile picture modal

packages/core/scss/global/tools/tools.functions.scss, packages/core/src/fonts.ts, packages/ndla-ui/src/Gloss/Gloss.tsx, packages/typography/src/Heading.stories.tsx, packages/typography/src/Text.stories.tsx
Fixes https://github.com/NDLANO/Issues/issues/3817
Man kan "melde seg ut" av forstørret kinesisk tekst ved å legge `data-pinyin=""` på et element.
=> More gloss fixes

packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
https://github.com/NDLANO/Issues/issues/3777
Krever litt i ndla-frontend også
=> Add language to resource link if it exists

packages/ndla-tabs/src/Tabs.stories.tsx, packages/ndla-tabs/src/Tabs.tsx
Visstnok noe Katrine ønsket seg
=> Redesign round tabs to account for more than two tabs

packages/article-converter/src/plugins/embed/contactBlockEmbedPlugin.tsx, packages/ndla-ui/src/ContactBlock/ContactBlock.tsx
Kanskje lurt å faktisk bruke den faktiske alt-overriden også
=> Add alt override for contact block embed

packages/ndla-accordion/src/AccordionHeader.tsx, packages/ndla-ui/src/Gloss/Gloss.tsx
Fixes NDLANO/Issues3827
For å være litt snillere med skjermlesere som skal lese opp gloser.
=> Add span as possible accordion header

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Phrases som skal støttes utifra det jeg ser på figma!
=> Added messages for arean notifications

stories/welcome.stories.tsx
=> Brukskvalitetsplattformen har flytta

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Det er en liten endring av tekstene mens vi venter på arena
=> updated my profile texts

packages/ndla-forms/src/InputV3.tsx, packages/ndla-forms/src/TextArea.stories.tsx
La merke til at nye TextArea først resizet seg etter at man interagerte med den.
=> Resize TextArea on initial render, allowing for it to adapt its size to existing content

packages/ndla-image-search/src/ImageSearch.tsx, packages/ndla-ui/src/MyNdla/Resource/FolderInput.tsx, packages/ndla-ui/src/TreeStructure/TreeStructure.stories.tsx, stories/basicStyles/banners.stories.tsx
Soft deprecation av Input og InputV2. Denne er breaking for ndla/ui
=> Use new input component

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Forbereder visning av navn på den som deler mappe.
=> Add phrases for shared by teacher.

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Ny oversettelse for postCard edit button label/title.
=> added edit button translation

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
=> Add translations for recent arena posts. Modified newFavourites

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Kan avvente med denne til andre PR'en er klar. Vil være litt breaking for knappene som allerede ligger ute
=> Added texts for modal/editor

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Legger til oversettelser for flagging av post i arena
=> Add translations for flagged post

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Trenger nok litt hjelp med nynorsk
=> Locale for deleting post/topic

packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
=> små rettingar i språk

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Glemte denne når jeg la inn de andre. Oops.
=> Forgot to add the preview text

packages/ndla-ui/src/locale/messages-en.ts
Liten fiks for å gjøre icontekst mindre etter ønske fra Hedvig.
=> Changed iconMenu subjects text

packages/carousel/src/Carousel.tsx, packages/core/src/spacing.stories.tsx, packages/core/src/spacing.ts, packages/ndla-editor/src/ndlaFilm/ThemeEditorModal.tsx, packages/ndla-forms/src/Input.tsx, packages/ndla-forms/src/InputV2.tsx, packages/ndla-forms/src/Styles.ts, packages/ndla-howto/src/Styles.ts, packages/ndla-ui/src/Footer/Footer.tsx, packages/ndla-ui/src/Footer/FooterLinks.tsx, packages/ndla-ui/src/FrontpageArticle/FrontpageArticle.tsx, packages/ndla-ui/src/LearningPaths/LearningPathInformation.tsx, packages/ndla-ui/src/LearningPaths/LearningPathLastStepNavigation.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuAside.tsx, packages/ndla-ui/src/LearningPaths/LearningPathMenuContent.tsx, packages/ndla-ui/src/NDLAFilm/MovieGrid.tsx, packages/ndla-ui/src/NDLAFilm/filmStyles.ts, packages/ndla-ui/src/Subject/SubjectHeader.tsx
Fixes NDLANO/Issues#3874
Vi bruker spacingUnit * 3 så mange plasser at den kan være egen spacing.
snormal brukes kun for å sette bredde på ikoner, og er ikkje en spacing så tar denne bort igjen.
Henter spacings fra figma. Dvs Hedvig har satt  24 * 4 som xlarge, men eg har foreslått det som xxlarge.
=> Add new spacings

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Er det dagen alt er riktig på først forsøk?
=> Added fetch more translations

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fikser: [Trello](https://trello.com/c/66VJmQrP/630-endre-infotekst-under-kategoriar)
=> added requested texts

packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Fixes https://github.com/NDLANO/Issues/issues/3878
Resultatet er ikke noe særlig vakkert, men det funker.
=> Wrap Embed byline on smaller sizes

packages/ndla-ui/src/FileList/FileList.tsx
=> Remove data-icon styling

packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx, packages/ndla-ui/src/LinkBlock/LinkBlock.tsx, packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
https://trello.com/c/iyFj1tC7/592-uu-endre-span-nb-til-span-no
Var visst noen flere steder som trengte å oppdateres
=> Update nb -> no

packages/button/src/ButtonV2.tsx
fixes https://github.com/NDLANO/Issues/issues/3864
=> Separate border-color for focus-visible

packages/ndla-ui/src/FileList/Format.tsx
Liten fiks i forbindelse med refakturering av filelist, fikser opp i:
=> Filelist: Fix overflow-wrap

packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx
[#3889](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=48061359)
=> link is optional

.storybook/manager.ts, packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx, packages/ndla-ui/src/Embed/BrightcoveEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/ExternalEmbed.stories.tsx, packages/ndla-ui/src/Embed/FootnoteEmbed.stories.tsx, packages/ndla-ui/src/Embed/H5pEmbed.stories.tsx, packages/ndla-ui/src/Embed/IframeEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/Embed/RelatedContentEmbed.stories.tsx
La oss prøve å splitte opp storybook litt. Synes dette blir en logisk gruppering. Noe annet som burde ligge der?
=> Move embeds to top-level stories

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Oversettelser ment å brukes som aria-labels for nav-elementer i ndla-frontend. Om noen har sterke meninger om at de skal "hete" noe annet, så har jeg ingen sterke meninger utover at dette var det beste jeg kom på.
=> Translations for ndla frontend navs

packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx
Om du setter crop slik at en av verdiene blir 0 så fungerer ikkje forhåndsvisninga. Sammenlign ed og forhåndsvisning på https://ed.test.ndla.no/subject-matter/learning-resource/38510/edit/nb. 
Denne pr må linkes inn, eller du kan sjekke oppdatert storybook med upperleft satt til 0.
=> Handle that crop values can be 0

packages/ndla-ui/src/FramedContent/FramedContent.tsx
=> Wrap FramedContent in forwardRef

packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx, packages/ndla-ui/src/SearchTypeResult/components/ItemContexts.tsx
Fikser https://trello.com/c/krNXbju6/653-t-og-k-i-s%C3%B8keresultat-for-skjermleser
=> Add aria-label to relevance icons

packages/ndla-ui/src/Embed/AudioEmbed.tsx
Fikser: [#3903](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=49552643 )
=> change EmbedByLine conditional to show right type

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Brukes på admin sidene :smile:
=> Add translations for arena admin page

packages/ndla-ui/src/Embed/ConceptEmbed.tsx
[#3922](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=50836369)
Har diskutert litt med Hedvig og da ble det en liten designendring på _hover/active_ i tillegg.
=> Adjust position and styling of InlineConcept button

packages/ndla-ui/src/ResourceGroup/ResourceItem.tsx
Fikser: [#3912](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=50272659)
=> Update hover on ResourceItem component

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
=> Add more arena translations

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
=> Add translations for search placeholder

packages/ndla-ui/src/Grid/Grid.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx
Fikser: [Trello](https://trello.com/c/GMCHnLZt/691-padding-i-grid)
Har også justert på _KeyFigure_ komponenten for å få teksten på samme linje
Burde sjekkes i ed om det slår ut noe visuelt
=> add padding to Grid component

packages/ndla-ui/src/Hero/Hero.tsx
Fixes https://github.com/NDLANO/Issues/issues/3927
Manglet padding på venstre side telefon modus
=> Add padding on left side for ndla-film

packages/ndla-ui/src/Embed/ConceptEmbed.tsx
Ei lita justering for å få med z-index også på ikke-mobiler.
=> Justering Z-index

.github/workflows/ci.yml, package.json, yarn.lock
Løser forhåpentligvis problemet med bygge-feil ved merge te master.
=> Bump yarn to 4.1.0

packages/tooltip/src/Tooltip/Tooltip.tsx
Greit å kunne styre hvor fort tooltipen skal dukke opp
=> Add delayDuration prop to tooltip

packages/ndla-ui/src/ExpandableBox/ExpandableBox.stories.tsx, packages/ndla-ui/src/ExpandableBox/ExpandableBox.tsx
Fikser: [#3931](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=51622224)
Ikke noe særlig pent, men sleit å fikse det på en annen måte. Åpen til bedre forslag
=> style summary for expandable box

packages/ndla-ui/src/types.ts
For å kunne støtte rendring av tittel med formatering
=> Title må være ReactNode for å kunne sendes inn som html-rendra tekst.

packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx
Gjør at teksten i disclaimeren ikke er mulig å velge eller merke.
=> Disclaimer no select text

packages/ndla-accordion/src/AccordionHeader.tsx, packages/ndla-accordion/src/AccordionItem.tsx, packages/ndla-ui/src/Gloss/Gloss.tsx, packages/ndla-ui/src/Gloss/GlossExample.tsx
[#3938](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=52373828)
Dette kan testes på [http://localhost:3000/article/38466](http://localhost:3000/article/38466) og sammenlignes med det gamle her  [https://test.ndla.no/article/38466](https://test.ndla.no/article/38466)
Når du kobler sammen ndla-frontend og fronend-packages så får accordion en flicker bug ved lukking. Virker som det forsvinner etter det er publisert i Test (dette skjer også når du kobler sammen master og master)
=> New gloss design

packages/ndla-forms/src/RadioButtonGroup/RadioButtonGroup.tsx, packages/ndla-forms/src/RadioButtonGroup/RadioButtonItem.tsx
Liten fiks som gjør at oppførselen blir riktig når man bruker radio buttons med FormControl
=> useFormControl in RadioButtonItem for correct FormControl usage

packages/ndla-ui/src/Gloss/Gloss.stories.tsx, packages/ndla-ui/src/Gloss/Gloss.tsx, packages/ndla-ui/src/Gloss/GlossExample.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
- justert litt på _GlossExample_ designet siden den er i bruk i ED
- lagt til aria-label på _Trigger_ knappen
- fikset sånn at fonten og skriftstørrelsene ikke blir overskrevet
=> adjusted GlossExample styling

packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/Article/component.article.scss, packages/ndla-ui/src/Layout/LayoutItem.tsx
Hedvig ville visst ha det sånn her
=> Increase article sizing even more

packages/ndla-ui/src/AudioPlayer/SpeechControl.tsx, packages/ndla-ui/src/Gloss/Gloss.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
=> minor gloss styling changes

packages/ndla-ui/src/index.ts
Denne hadde vært kjekk å ha for å refaktorere noe preview greier i ed :smile:
=> Export `ArticleType` from `@ndla/ui`

packages/ndla-ui/src/Search/ActiveFilters.tsx, packages/ndla-ui/src/Search/SearchField.tsx
=> Make prettier border on hover

package.json, packages/article-converter/package.json, packages/ndla-audio-search/package.json, packages/ndla-image-search/package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/RelatedContentEmbed.stories.tsx, packages/ndla-ui/src/TreeStructure/TreeStructure.stories.tsx, packages/types-embed/package.json, yarn.lock
Lett å oversjå disse dependenciene i og med at dei ikkje ligger i package.json på rota.
=> Bump backend types

packages/core/src/stackorder.ts
Fixes https://github.com/NDLANO/Issues/issues/3974
Gir mer og mer mening at en modal dukker opp over popovers, også med fotfeste i det issuet som oppstod her. Men den bør testes for å sikre at det ikke skaper problemer noen andre steder. Har sjekka de stedene jeg fant / kunne komme på at popover-verdien er i bruk, for å prøve å finne konflikter. Ikke funnet noen.
=> Change modal and popover stackOrder order

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
[Trello](https://trello.com/c/Ykb3h0zq/770-legge-til-tekst-p%C3%A5-mine-fag-under-min-ndla-dersom-man-ikke-har-noen-hjertemerkede-fag)
=> Uppdatet nofavortes text

packages/article-converter/src/plugins/embed/campaignBlockPlugin.tsx, packages/ndla-ui/src/CampaignBlock/CampaignBlock.stories.tsx, packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx, packages/types-embed/src/campaignBlockTypes.ts
https://github.com/NDLANO/Issues/issues/3976
=> Display HTML in campaign block

packages/ndla-ui/src/KeyFigure/KeyFigure.stories.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx
https://github.com/NDLANO/Issues/issues/3976
=> Parse html in Key FigurParse html in Key Figure

packages/ndla-ui/src/locale/messages-nn.ts
Korreksjon på nynorsk tekst.
[Trello](https://trello.com/c/3FPvEOnk/760-endre-innloggingsmodal-min-ndla)
=> Uppdated messages-nn with correct spelling

packages/article-converter/src/plugins/embed/conceptEmbedPlugin.tsx, packages/article-converter/src/plugins/types.ts, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/conceptComponents.tsx
Fikser: [#3981](https://github.com/orgs/NDLANO/projects/2/views/9?pane=issue&itemId=56430110)
Kan testes her: [localhost](http://localhost:3000/nb/concept/959)
=> add prop to hide h1 in gloss embed

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://github.com/NDLANO/Issues/issues/3994
=> Add translations for recent favourite subjects block

packages/ndla-forms/src/FormControl.stories.tsx, packages/ndla-forms/src/FormControl.tsx, packages/ndla-forms/src/InputV3.tsx, packages/ndla-forms/src/Label.tsx, packages/safelink/src/SafeLink.tsx
Input should be red when it is aria-invalid.
Add some base padding in FormControl.
Set margin to none by default on Label.
=> Form changes

packages/article-converter/src/plugins/embed/contentLinkEmbedPlugin.tsx, packages/ndla-ui/src/Embed/ContentLinkEmbed.tsx, packages/types-embed/src/contentLinkTypes.ts
Fixes https://github.com/NDLANO/Issues/issues/4004
Ser ut som at vi fortsatt slipper unna NBSP-problematikken.
=> Parse content-link children to allow for html within links

packages/safelink/src/SafeLinkIconButton.tsx
`to` er vel strengt tatt ikke en streng
=> Simplify SafeLinkIconButtonProps

packages/ndla-ui/src/MediaList/MediaList.tsx
Liten bug på små enheter [Trello](https://trello.com/c/cUaRcYGO/802-kulepunkt-skal-fjernes-i-regler-for-bruk)
=> remove list style in cite or use for small screens

packages/ndla-ui/src/AudioPlayer/Controls.tsx
Fixes https://github.com/NDLANO/Issues/issues/4012
=> Use onSelect on DropdownItem, not on SpeedValueButton

packages/ndla-ui/src/Embed/FootnoteEmbed.tsx
Fixes https://github.com/NDLANO/Issues/issues/4014
=> Remove footnote target style

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Oversettelser for mapper delt av andre.
[Figma](https://www.figma.com/file/fyzyLEJ8GtOef12Ya3xAIz/MinNDLA-redesign?type=design&node-id=1-6&mode=design&t=43OFpBuQJTTACbzd-0)
=> added new translations for folders shared by others

packages/ndla-audio-search/src/AudioSearchList.tsx, packages/ndla-forms/src/RadioButtonGroup/RadioButtonItem.tsx, packages/ndla-icons/src/Spinner.tsx, packages/ndla-ui/src/Article/ArticleNotions.tsx, packages/ndla-ui/src/AudioPlayer/AudioPlayer.tsx, packages/ndla-ui/src/AudioPlayer/Controls.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Filter/ToggleItem.tsx, packages/ndla-ui/src/Image/Image.tsx, packages/ndla-ui/src/Notion/Notion.tsx, packages/ndla-ui/src/Search/SearchResult.tsx, packages/ndla-ui/src/SearchTypeResult/SearchTypeHeader.tsx, packages/ndla-ui/src/SearchTypeResult/SearchTypeResult.tsx, packages/ndla-ui/src/SearchTypeResult/SearchViewType.tsx, packages/ndla-ui/src/SearchTypeResult/components/ItemTopicHeader.tsx, packages/safelink/src/SafeLink.tsx, packages/select/src/Select/BaseControl.tsx, packages/select/src/Select/BaseMenu.tsx, packages/tooltip/src/Tooltip/Tooltip.tsx
Tok i bruk spacing og misc verdier noen steder mens jeg loket litt i koden
=> small clean up in code

packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/LearningPaths/LearningPathContent.tsx
Fixes https://github.com/NDLANO/Issues/issues/4030
Given a breakpoint for tablets which places the popover differently.
=> Adjust concept popover for tablets

packages/core/scss/global/elements/_elements.aside.scss, packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/Article/ArticleHeaderWrapper.tsx, packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx, packages/ndla-ui/src/Embed/BrightcoveEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/ExternalEmbed.stories.tsx, packages/ndla-ui/src/Embed/H5pEmbed.stories.tsx, packages/ndla-ui/src/Embed/IframeEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/Embed/RelatedContentEmbed.stories.tsx, packages/ndla-ui/src/Embed/UuDisclaimerEmbed.stories.tsx, packages/ndla-ui/src/Hero/Hero.tsx, stories/welcome.stories.tsx, stories/wrappers/StoryBody.tsx
Denne må testes _veldig_ nøye. Livredd for å bomme på artikkel-styling og oppførsel
=> Reduce c article usage

packages/ndla-audio-search/src/AudioSearch.tsx
Trengs for å utvide søket etter lyder
=> Adds fallback-param to audio-search

packages/hooks/src/useComponentSize.ts, packages/ndla-ui/src/FrontpageArticle/FrontpageArticle.tsx
Tar over for https://github.com/NDLANO/frontend-packages/pull/2251
=> Refactor useComponentSize to be more generic. Use it instead of having a custom `useMastheadHeight` hook.

packages/article-converter/src/plugins/copyParagraphPlugin.tsx, packages/ndla-ui/src/Embed/UuDisclaimerEmbed.stories.tsx
=> Support rendering of h2-link in uu-disclaimer

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-sma.ts
Kommunikasjon ønsker at det står "under utvikling". Betafag gir ikkje meining.
=> Ikkje betafag, under utvikling

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Trengte noen tekst linjer for de som heller vil ha en fet tittel
=> Added en fagperson text

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fått nytt design så må ha like message som vi gjør med kopier mappe
=> Added messages for LoginModal for save link

packages/ndla-ui/src/Figure/Figure.tsx
https://github.com/NDLANO/Issues/issues/4052
=> Do not use utility classes for floating figures. Instead, use emotion

packages/ndla-ui/src/Embed/AudioEmbed.stories.tsx, packages/ndla-ui/src/Embed/BrightcoveEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/ExternalEmbed.stories.tsx, packages/ndla-ui/src/Embed/H5pEmbed.stories.tsx, packages/ndla-ui/src/Embed/IframeEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/Embed/RelatedContentEmbed.stories.tsx, packages/ndla-ui/src/Embed/UuDisclaimerEmbed.stories.tsx, packages/ndla-ui/src/Layout/LayoutItem.tsx
https://github.com/NDLANO/Issues/issues/4052
Ikke så overraskende, men vi hadde litt for mye scss her. Dette hadde nesten ikke trengt å være to forskjellige ting.
=> Refactor layout item

packages/ndla-ui/src/Embed/ConceptEmbed.tsx
fixes https://github.com/NDLANO/Issues/issues/4036
Disabled autoscroll in editor. Moved selection when clicking inline concept.
=> Fjerner autoscroll i editor og gir tilgang til å flytte selection ved klikk

packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx
Vi veit jo bredden på disse så kan like gjerne bruke det for å redusere forsidestørrelsen,
=> Set width on frontpage component images

packages/primitives/src/ExpandableBox.stories.tsx, packages/primitives/src/ExpandableBox.tsx, packages/primitives/src/index.ts
Magien med negativ margin kommer [herfra](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary)
=> Add ExpandableBox component

packages/primitives/src/ArticleLists.tsx, packages/primitives/src/ArticleOrderedList.stories.tsx, packages/primitives/src/ArticleUnorderedList.stories.tsx, packages/primitives/src/index.ts
=> Add article list components

.storybook/preview.tsx, packages/preset-panda/panda.config.ts, packages/primitives/panda.config.ts, panda.config.ts
Begynner å bli litt vel teit at jeg bruker dette lokalt, men ikke i master. Får heller tåle at alt ikke ser ut som før i designmanualen.
=> Stop loading scss in designmanual, as it causes too many visual bugs

package.json, packages/preset-panda/package.json, packages/preset-panda/src/animations.ts, packages/preset-panda/src/semanticTokens.ts, packages/primitives/package.json, packages/primitives/src/Accordion.stories.tsx, packages/primitives/src/Accordion.tsx, packages/primitives/src/createStyleContext.tsx, packages/styled-system/package.json, yarn.lock
Kom gjerne med tilbakemeldinger! Jeg har slitt litt med animasjon av border-radius mellom åpen og lukket tilstand, bare å prøve seg hvis dere tror dere kan forbedre det!
Fokus-staten er ikke akkurat fantastisk; Den er global akkurat nå. Tenker at fjerner buttons fra global fokus-styling, så styler jeg heller ting som `Button` og `AccordionTrigger` med sine egne implementasjoner av fokus.
=> Add accordion

packages/ndla-ui/src/Table/Table.stories.tsx, packages/ndla-ui/src/Table/Table.tsx, packages/primitives/src/Table.stories.tsx, packages/primitives/src/Table.tsx
Legger til styling så vi fortsatt har mulighet til å align innholdet til de ulike sidene.
=> Table add alignment styling

packages/preset-panda/src/animations.ts, packages/primitives/src/Tooltip.stories.tsx, packages/primitives/src/Tooltip.tsx
Litt usikker på animasjonen, men lar det være inntil videre.
=> Add Tooltip component

packages/primitives/src/FormControl.stories.tsx, packages/primitives/src/Input.tsx, packages/primitives/src/Label.tsx, packages/primitives/src/Switch.stories.tsx, packages/primitives/src/Switch.tsx
Hadde egentlig tenkt å ta inn et par til, men avventer litt på design.
=> Add Switch component

packages/primitives/src/Badge.stories.tsx, packages/primitives/src/Badge.tsx
=> Add Badge component

packages/primitives/src/Checkbox.stories.tsx, packages/primitives/src/Checkbox.tsx
CheckboxGroup kommer senere. Ark utvikler den nå!
=> Add Checkbox

packages/primitives/src/Menu.stories.tsx, packages/primitives/src/Menu.tsx
MERK: Det er en bug i zag (det som ligger under ark) som gjør at lenker automatisk får fokus. Det er en fiks på dette i master allerede, så bare å vente på at de bumper pakker. Synes det er greit å se på denne uansett.
=> Add Menu components

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Oppdaterte messages med tekst til fjerning av lenker fra mine mapper.
=> Uppdate folder button with unfavorite text

packages/preset-panda/src/animations.ts, packages/primitives/src/Skeleton.stories.tsx, packages/primitives/src/Skeleton.tsx
Går for en litt ny tilnærming til Skeleton-komponenten. Gjerne kom med tilbakemelding på om dere liker stylingen, og evt om dere foretrekker måten man bruker de gamle skeleton-komponentene på.
=> Add Skeleton component

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Glemte disse når jeg la inn ikonene. Oops.
=> Texts for upvote buttons

packages/primitives/src/Tabs.stories.tsx, packages/primitives/src/Tabs.tsx
Vil tro at den som er tiltenkt ED kommer til å endre seg på sikt, men tenkte det var greit å ha koden uansett.
=> Add basic tabs

packages/ndla-ui/src/Embed/ImageEmbed.tsx, packages/types-embed/src/imageTypes.ts, stories/article/FigureImage.tsx
Depends on https://github.com/NDLANO/backend/pull/502
Legger til støtte for to nye data-flagg, og også veldig temporær støtte for den eine.
=> Add new attributes in image embed, and support both old an new flag.

packages/preset-panda/src/semanticTokens.ts, packages/primitives/src/Checkbox.stories.tsx, packages/primitives/src/Checkbox.tsx
Halvparten av Chip, men den vi kommer til å bruke aller flest steder!
=> Add chip variant to Checkbox

packages/primitives/src/Checkbox.stories.tsx, packages/primitives/src/Checkbox.tsx
Tenker å åpne en PR i ark som legger til CheckboxGroupLabel på et tidspunkt, men tar det litt senere.
=> Add CheckboxGroup

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Legger til tekst for skjermlesere for antall stemmer på en post.
=> Added number of posts-text

packages/ndla-ui/src/LicenseByline/LicenseDescription.tsx
fikser en bug der byline overflowet i grid container
=> Fix byline in grid container

packages/primitives/src/Figure.stories.tsx, packages/primitives/src/Figure.tsx
Legger til en drastisk forenklet versjon av `Figure`. Den største endringen er nok at vi i mindre større grad tar hensyn til margin på figure. Har fortsatt et håp om at alle komponenter kan ha "lik" margin innad i en artikkel til slutt.
=> Add Figure

packages/preset-panda/src/conditions.ts, packages/primitives/src/Button.tsx, packages/primitives/src/Combobox.stories.tsx, packages/primitives/src/Combobox.tsx, packages/primitives/src/Select.stories.tsx, packages/primitives/src/Select.tsx, packages/primitives/src/TagsInput.stories.tsx, packages/primitives/src/TagsInput.tsx, packages/primitives/src/storybookHelpers/data.ts, packages/util/src/contains.ts, packages/util/src/index.ts
Brorparten av koden er eksempel-kode. Disse komponentene kommer til å få wrappers i både ndla-frontend og ED, men ikke her. Tenker det gir mest mulig fleksibilitet.
=> Add Select and Combobox

packages/ndla-ui/src/AudioPlayer/AudioPlayer.tsx
Fixes https://github.com/NDLANO/Issues/issues/4080
=> Remove image overflow

packages/ndla-ui/src/Embed/ImageEmbed.tsx
Hedvig mente det holdt med mindre størrelse på knappen sida hele bildet er klikkbart (24x24). Så here goes.
=> Downsize button for image resizing

packages/ndla-ui/src/BlogPost/BlogPost.tsx, packages/ndla-ui/src/types.ts, packages/preset-panda/src/globalCss.ts
Sjekk designet. Denne ligger under "Forside"
=> Convert BlogPost to panda

packages/ndla-ui/src/FactBox/FactBox.tsx, packages/ndla-ui/src/FactBox/Factbox.stories.tsx
Har fjernet en del default-styling for lister og headings. Har oppdatert eksemplet i master så man kan sammenligne nytt og gammelt. Har også gjort hele greia litt mer tilgjengelig enn den var før!
=> Refactor FactBox to new design (and panda).

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Oppdaterer i henhold til nytt design!
Hva burde jeg gjøre med sma/se? Prøve å oppdatere oversettelsen?
=> Update competence goal translation

packages/ndla-ui/src/TagSelector/TagSelectorNew.stories.tsx, packages/ndla-ui/src/TagSelector/TagSelectorNew.tsx, packages/primitives/src/Combobox.tsx, packages/primitives/src/TagsInput.stories.tsx, packages/primitives/src/TagsInput.tsx, packages/primitives/src/index.ts
Sjekk at dere er fornøyde med API'et og at dere ikke klarer å finne noen bugs. Før noen spør: Man kan kun navigere med piltaster mellom tags når combobox-menyen er lukket.
Det eneste som mangler er oversettelser; Tar det i morgen.
=> Initial pass at new TagSelector

packages/ndla-ui/src/Embed/UuDisclaimerEmbed.stories.tsx, packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx
Marginer mellom elementer kommer til å tas i den fremtidige `Article`-komponenten.
=> Refactor UUDisclaimer

packages/ndla-ui/src/LinkBlock/LinkBlock.stories.tsx, packages/ndla-ui/src/LinkBlock/LinkBlock.tsx, packages/ndla-ui/src/LinkBlock/LinkBlockSection.tsx
Tror designet er litt halvferdig her. Vi får se hva som skjer etterhvert.
=> Refactor LinkBlock to use panda

packages/ndla-ui/src/Embed/ExternalEmbed.tsx, packages/ndla-ui/src/Embed/IframeEmbed.tsx, packages/ndla-ui/src/ResourceBox/ResourceBox.tsx
Mangler noe greier med bildet på fullscreen
=> Refactor external and iframe embed

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
relates to https://github.com/NDLANO/ndla-frontend/pull/1918
=> All subject page translations

packages/primitives/src/Tabs.tsx
Mye tid brukt på liten fiks! menmen 😅 
**NB**: Jeg har ikke rørt outline-varianten(det er vel egentlig ikke noe design på denne enda 🤔 )
=> Fix Tabs view on smaller screen sizes

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://github.com/NDLANO/ndla-frontend/pull/1924
Kan eventuelt fjerne oversettelsen herfra og flytte over til ndla-frontend
=> Accordion translations

packages/primitives/package.json, packages/primitives/src/Field.tsx, packages/primitives/src/FieldErrorMessage.tsx, packages/primitives/src/FieldHelper.tsx, packages/primitives/src/Input.stories.tsx, packages/primitives/src/Input.tsx, packages/primitives/src/Label.tsx, packages/primitives/src/RadioGroup.tsx, packages/primitives/src/index.ts, yarn.lock
Tror jeg skal lage en PR i ark for å koble helper- og error-teksten opp mot fieldsettet. Annet enn det tror jeg dette skal være good!
=> Fieldset primitive

packages/ndla-ui/src/FactBox/FactBox.tsx, packages/ndla-ui/src/Grid/Grid.tsx, packages/primitives/src/ExpandableBox.tsx, packages/primitives/src/FramedContent.tsx
Første og siste punkt her: https://github.com/NDLANO/Issues/issues/4097
=> Fix block-elements positioning with float-elements

packages/ndla-ui/src/ErrorMessage/ErrorMessage.tsx
Fixes https://github.com/NDLANO/Issues/issues/4105
=> Center illustrationwrapper

packages/article-converter/src/plugins/divPlugin.tsx, packages/ndla-ui/src/Grid/Grid.stories.tsx, packages/ndla-ui/src/Grid/Grid.tsx, packages/ndla-ui/src/Grid/GridParallaxItem.tsx, packages/ndla-ui/src/Grid/index.ts, packages/ndla-ui/src/KeyFigure/KeyFigure.stories.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx
Implementerer `KeyFigure` og `Grid` i henhold til design (tror jeg).
Måtte gjette litt på noen ting, men syns det ser aight ut selv i alle fall :smile:
=> Reimplement `KeyFigure` and `Grid` according to new design

packages/primitives/src/Checkbox.tsx, packages/primitives/src/RadioGroup.tsx
Fixes https://github.com/NDLANO/Issues/issues/4123
=> fix: ensure that radio and checkbox controls always take up their intended widths

packages/ndla-ui/src/Breadcrumb/Breadcrumb.tsx, packages/ndla-ui/src/Breadcrumb/BreadcrumbItem.tsx, packages/ndla-ui/src/Breadcrumb/HomeBreadcrumb.tsx
Bytter ikon og justerer på noen gaps
[Figma](https://www.figma.com/design/E4Y9nwHcDVTETrEQFxf3bD/Components-2024?node-id=1-8&m=dev)
=> small breadcrumb styling changes

packages/primitives/src/Accordion.tsx, packages/primitives/src/Button.tsx, packages/primitives/src/Checkbox.tsx, packages/primitives/src/Combobox.tsx, packages/primitives/src/Dialog.tsx, packages/primitives/src/Figure.tsx, packages/primitives/src/Menu.tsx, packages/primitives/src/Popover.tsx, packages/primitives/src/RadioGroup.tsx, packages/primitives/src/Select.tsx, packages/primitives/src/Skeleton.tsx, packages/primitives/src/Slider.tsx, packages/primitives/src/Spinner.tsx, packages/primitives/src/Switch.tsx, packages/primitives/src/Tabs.tsx, packages/primitives/src/TagsInput.tsx, packages/primitives/src/Toast.tsx, packages/primitives/src/Tooltip.tsx
~~Mest et forslag, men tenker det kan være lurt å droppe pulse-animation dersom bruker har satt preferance om reduserte animasjonseffekter.~~
Støtter reduced motion preference på komponenter.
=> Honouring reduced motion preference

packages/preset-panda/src/globalCss.ts
Hedvig ville se hvordan dette ser ut, så vi tar det inn inntil videre med mindre noen har noen store innvendinger!
=> Adjust article margins

packages/ndla-ui/src/utils/__tests__/relativeUrl-test.tsx, packages/ndla-ui/src/utils/relativeUrl.ts
Fixes NDLANO/Issues#4131
Tar vare på params i lagra urler.
=> Keeps url-params in saved urls

packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/Article/ArticleByline.stories.tsx, packages/ndla-ui/src/Article/ArticleByline.tsx, packages/ndla-ui/src/Article/ArticleFootNotes.tsx, packages/ndla-ui/src/Article/index.ts, packages/ndla-ui/src/index.ts, packages/primitives/src/Accordion.tsx, packages/primitives/src/index.ts
Makan til vanskelig dette skulle være. 
Dette legger til støtte for de utfordrende footer-elementene som nå skal finnes i flere artikkel-komponenter:
* Ressurser på artikkelside
* Footer på Om NDLA
Gjerne vurder hvorvidt vi skal øke footer-paddingen. Inntil videre er det klin lik padding på header, content og footer. Footer fortjener kanskje mer padding? 
Kan testes med https://github.com/NDLANO/ndla-frontend/pull/1985
=> Support new article compositions

packages/ndla-ui/src/CopyParagraphButton/CopyParagraphButton.tsx
Skal visst forbli en knapp :')
=> Refactor CopyParagraphButton

package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/Embed/RelatedContentEmbed.tsx, packages/types-embed/src/relatedContentTypes.ts, yarn.lock
Første steg av overgang til å gjøre punycode-konvertering på server. Etter at denne er merget kan vi bumpe pakker og ta inn https://github.com/NDLANO/graphql-api/pull/479
=> Replace punycode with converted result from graphql

packages/preset-panda/src/semanticTokens.ts, packages/primitives/src/Button.tsx
Sjekk figma. Hedvig har laget "selected"-states for knapper også, men lurer litt på om vi kanskje heller bruker de som en guide for eventuelle steder der en knapp kan bli "selected".
=> New active states for button

packages/ndla-licenses/src/licenseRights.ts
Anne melder at det skal stå _gir_ i staden for _gjev_ og _dele_ i staden for _dela_
=> typo: gjev og dele

.storybook/main.ts, packages/ndla-audio-search/package.json, packages/ndla-audio-search/panda.config.ts, packages/ndla-audio-search/src/AudioSearch.stories.tsx, packages/ndla-audio-search/src/AudioSearch.tsx, packages/ndla-audio-search/src/AudioSearchForm.tsx, packages/ndla-audio-search/src/AudioSearchList.tsx, packages/ndla-audio-search/src/AudioSearchResult.tsx, yarn.lock
NB: venter på oppdatert styling i ListItem sånn at vi ikke får hover-styling på ListItems
Forslag til hvordan det kan se ut!
=> Refactor AudioSearch to panda + to new components

packages/primitives/src/ListItem/ListItem.tsx
Ble visst en liten compound-variant ja.
=> fix issue with nonInteractive and list variant

packages/primitives/src/Checkbox.tsx
Fikser cursor på hover disabled checkbox og fjernet farge på checked disabled checkbox border.
=> Fix disabled state new checkbox

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Teksten på knappen for å slette brukerprofil på Min NDLA blir oppdatert, [se figma](https://www.figma.com/design/E4Y9nwHcDVTETrEQFxf3bD/Components-2024?node-id=5989-65929&t=WOJFfZ9v7VByPJkH-0)
=> Change button text for profile page

packages/primitives/src/FileUpload.stories.tsx, packages/primitives/src/FileUpload.tsx
Prøvd å følge logikk fra andre komponenter. 
~Mangler å få `FileUploadItemName` og `FileUploadItemSizeText` til å fungere ordentlig~
=> Fileupload WIP

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Fra [Trello](https://trello.com/c/egJfwEEq/905-endre-tooltip-tekst-for-reaksjon-p%C3%A5-arena)
=> Updated likes button hoover text

packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/Article/index.ts, packages/ndla-ui/src/index.ts
fixes https://github.com/NDLANO/Issues/issues/4145
Er ikke 100% fan av løsningen, men den fungerer og har samme design som forrige bare uten at knappen kan flyte over teksten. 
Har gjort endringene i frontend også om denne blir approva
=> Made article hgroup into grid

packages/primitives/src/Select.stories.tsx
Fikser retning på chevron til å matche [Figma](https://www.figma.com/design/E4Y9nwHcDVTETrEQFxf3bD/Components-2024?node-id=2289-49016&m=dev).
=> Updated chevron direction

packages/primitives/src/Toast.stories.tsx
Legger til litt luft mellom toast knappene i toast.stories.
=> Added margin to toast button

packages/primitives/src/Toast.stories.tsx, packages/primitives/src/Toast.tsx
Fixes https://github.com/NDLANO/Issues/issues/4121
=> feat: add variant to toast, allowing for light or dark backgrounds

packages/ndla-audio-search/README.md, packages/ndla-audio-search/src/AudioSearchResult.tsx
Tenker vi fjerner h1-heading nivå her og!
=> AudioSearch: Update h1 heading to p + update readme

packages/ndla-audio-search/src/AudioSearch.tsx, packages/ndla-image-search/README.md, packages/ndla-image-search/src/ImageSearch.stories.tsx, packages/ndla-image-search/src/ImageSearch.tsx, packages/ndla-image-search/src/ImageSearchResult.tsx, packages/ndla-image-search/src/PreviewImage.tsx, packages/ndla-ui/src/i18n/index.ts, packages/ndla-ui/src/i18n/useComponentTranslations.ts, packages/ndla-ui/src/index.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
lar denne være draft bittelitt i tilfelle det er mer
=> ImageSearch, AudioSearch: styling fix + add translation hooks

packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx
Fjerner knapp for ekspandering av byline.
=> Remove expand byline button

packages/primitives/src/Button.tsx
Tar over for https://github.com/NDLANO/frontend-packages/pull/2455
=> fix: adjust button sizes to better match design. Adjust link variant to look more like a regular link

packages/ndla-ui/src/Embed/InlineTriggerButton.tsx
fikser [trello](https://trello.com/c/FerSkfMZ/59-forklaringsstrek-for-langt-ned)
=> change padding for the inline concept trigger

packages/ndla-ui/src/AudioPlayer/Controls.tsx
fikser [trello](https://trello.com/c/gSBTS0wM/64-ulik-oppf%C3%B8rsel-p%C3%A5-slidere)
=> adjust video player progress and volume sliders

packages/ndla-image-search/src/ImageSearchResult.tsx, packages/ndla-image-search/src/PreviewImage.tsx, packages/ndla-ui/src/Embed/EmbedErrorPlaceholder.tsx, packages/ndla-ui/src/Embed/ImageEmbed.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx, packages/ndla-ui/src/ResourceBox/ResourceBox.tsx, packages/primitives/src/Image.stories.tsx, packages/primitives/src/Image.tsx, packages/primitives/src/ListItem/ListItem.tsx
Gjerne se over om dette er noe som burde settes flere steder
=> Add rounded variant to Image

packages/primitives/src/index.ts
Trenger disse i ndla-frontend jeg :smile:
=> Export `ErrorMessage` components

packages/primitives/src/ArticleLists.tsx
Liten justering på paddingen til første liste objekt for å få markers dypere inn på siden.
=> Letter article padding

packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
fikser [trello](https://trello.com/c/v7fNM5Lg/89-vismindre-lenke-mangler-spacing)
=> add margin to make space between text and button

packages/types-embed/src/keyFigureTypes.ts
Hadde visst glemt å gjøre denne optional
=> Make imageId optional on `KeyFigureEmbedData` type

packages/ndla-ui/src/FactBox/FactBox.tsx, packages/ndla-ui/src/FactBox/Factbox.stories.tsx
Forslag til tuning av gradient! si fra hvis noe annet var tanken bak kommentaren
=> Tune FactBox gradient

packages/primitives/src/Tabs.tsx
https://trello.com/c/qh4zzMO8/107-dobbeltstrek-som-fanemark%C3%B8r
=> Fix Tabs current indicator styling when zoomed in

packages/ndla-ui/src/Embed/CodeEmbed.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/EmbedErrorPlaceholder.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Glemte visst å opprette PR på denne :D
=> feat: redesign EmbedErrorPlaceholder, and use it in CodeEmbed

packages/ndla-ui/src/CampaignBlock/CampaignBlock.tsx
[https://trello.com/c/sitByMnR/63-endringer-kampanjeblokk](https://trello.com/c/sitByMnR/63-endringer-kampanjeblokk)
=> new campaignblock design

packages/primitives/src/ArticleLists.tsx, packages/primitives/src/ArticleOrderedList.stories.tsx, packages/primitives/src/ArticleUnorderedList.stories.tsx
https://trello.com/c/oEUB1Fai/112-alfabetiske-punkter-henger-utenfor-tekstspalte
=> Add more margin to ol

packages/primitives/src/ArticleLists.tsx
Gjør dette så Jonas blir litt mer sint på meg for dårlig testing 👯‍♀️
=> Adjust unordered-list spacing

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
https://trello.com/c/LM0KW3PV/135-endre-tekst-i-modal-for-mapper-ta-bort-siste-linje
=> Update shared folder description translations

packages/ndla-ui/src/Embed/CopyrightEmbed.tsx, packages/ndla-ui/src/Embed/EmbedWrapper.tsx, packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx, packages/ndla-ui/src/Embed/index.ts, packages/ndla-ui/src/index.ts, packages/preset-panda/src/globalCss.ts, packages/primitives/src/Figure.tsx
Fixes https://github.com/NDLANO/Issues/issues/4184
Små-endringer som gjør at vi kan få bedre artikkel-styling i editor. I første omgang trenger man bare å sjekke at artikler i ndla-frontend fortsetter å se riktig ut.
=> Improve ED compatibility for embed components

packages/ndla-ui/src/FactBox/FactBox.tsx, packages/primitives/src/ArticleLists.tsx, packages/primitives/src/ArticleOrderedList.stories.tsx
Ordered list overflower litt inne i aside.
=> Added margin to lists to escape overflow

packages/ndla-audio-search/src/AudioSearch.tsx, packages/ndla-audio-search/src/AudioSearchForm.tsx, packages/ndla-image-search/src/ImageSearch.tsx
fixes https://github.com/NDLANO/Issues/issues/4182
Fikser i tillegg at pagination overflower på mindre skjermer!
=> image-search/audio-search: pagination overflow fix + submit event propagation fix

packages/ndla-ui/src/Grid/Grid.stories.tsx, packages/ndla-ui/src/KeyFigure/KeyFigure.tsx
https://trello.com/c/SSc6uAkU/119-n%C3%B8kkeltall-har-for-lite-padding
=> Fix key figure padding

packages/ndla-ui/src/AudioPlayer/Controls.tsx, packages/ndla-ui/src/TagSelector/TagSelector.stories.tsx, packages/ndla-ui/src/TagSelector/TagSelector.tsx, packages/ndla-ui/src/i18n/useComponentTranslations.ts, packages/primitives/package.json, packages/primitives/src/Combobox.stories.tsx, packages/primitives/src/Combobox.tsx, packages/primitives/src/Select.stories.tsx, packages/primitives/src/Select.tsx, yarn.lock
Bare breaking changes i Select og Combobox for vår del!
=> chore: bump ark to v4

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
fikser https://trello.com/c/IDp6Zuh3/148-likes-tolkes-som-oppstemming
Mine forslag for nye tekster i aria label på upvotes
=> Update text to more appropriate text

packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx
fikser https://trello.com/c/5fvFu2pD/155-uu-lenke-er-usynlig
=> Add decoration to uu-embed-link

packages/primitives/src/Tabs.tsx
=> refactor: slightly improve look of outline tabs

packages/ndla-ui/src/Breadcrumb/BreadcrumbItem.tsx
fikser https://trello.com/c/gVy5V3Nu/147-lilla-lenker-arena
=> adjust visited breadcrumb color

packages/ndla-ui/src/Embed/ImageEmbed.stories.tsx, packages/ndla-ui/src/LicenseByline/EmbedByline.tsx
Dersom caption er "" skal den ikkje vises. Og dersom hideByline er satt så trengs ikkje figcaption å vises i det heile tatt.
=> Do not display figcaption at all if no data

packages/primitives/src/Image.tsx, packages/primitives/src/__tests__/Image-test.tsx
Convert function parameters to an option object
=> feat: add ability to pass in `imageLanguage` to image functions and components.

packages/primitives/src/ListItem/ListItem.stories.tsx, packages/primitives/src/ListItem/ListItem.tsx
Flytter dette til ndla-frontend der det brukes istedet!
=> ListItem: remove current related styling

packages/ndla-audio-search/src/AudioSearchResult.tsx, packages/ndla-video-search/src/VideoListItem.tsx, packages/primitives/src/Combobox.stories.tsx, packages/primitives/src/ListItem/ListItem.stories.tsx, packages/primitives/src/ListItem/ListItem.tsx
Replace it with an actual variant, that can either be `subtle` or `intense`
=> feat: replace the regular List item variant with `context`. 

packages/preset-panda/src/globalCss.ts
Fixes https://trello.com/c/dtf12309/265-noen-rare-brudd-i-overskrifter
=> fix: do not balance wrapped headings

packages/ndla-ui/src/AudioPlayer/AudioPlayer.tsx
Fixes https://trello.com/c/Wj51N2H5/258-for-tett-tekst-i-podkast
=> fix: add paragraph margin to audio text version

packages/ndla-ui/src/TagSelector/TagSelector.tsx
Skal gjøre litt freaky greier med denne i ED :')
=> fix: properly merge Combobox and TagsInput into TagSelector.

packages/preset-panda/src/globalCss.ts
Fixes https://trello.com/c/4TTybu5I/263-linjeskift-i-sitatboks-gir-veldig-lite-luft
=> fix: reduce blockquote text size in ndla articles

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Ny generell meta description. Språkvaska og godkjent.
=> ny generell meta desc

packages/ndla-ui/src/Grid/Grid.tsx, packages/ndla-ui/src/Pitch/Pitch.stories.tsx
https://trello.com/c/khclNxug/295-pitch-p%C3%A5-forside-juster-storleik
Posisjonerer pitch i grid på bunnen sånn at elementene ligger på linje når beskrivelsen har ulik lengde. Dette gjelder kun for pitch brukt i grid.
=> Fix grid with pitch image positioning

packages/ndla-ui/src/Pitch/Pitch.tsx
Kom litt klager på at bildene i test er kornete og har dårlig res
=> increase pitch image size

packages/ndla-ui/src/Grid/Grid.tsx, packages/ndla-ui/src/Pitch/Pitch.stories.tsx
Da prøver vi igjen 😄 
https://trello.com/c/khclNxug/295-pitch-p%C3%A5-forside-juster-storleik
=> Second try on fixing image positioning for pitch in grid

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Trenger dette til denne [trello](https://trello.com/c/qUpYvgXF/84-innholdstyper-b%C3%B8r-lables-p%C3%A5-s%C3%B8keresultat)
=> add translation for searchpage card

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts
Reverts NDLANO/frontend-packages#2563
Dei var visst ikkje heilt sikre likevel
=> Revert "Ønske fra kommunikasjon!"

packages/ndla-ui/src/AudioPlayer/Controls.tsx
Fikser en feil i sentry tydeligvis
=> fix: only change slider value if a new value exists

packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/ConceptInlineTriggerButton.tsx, packages/ndla-ui/src/Embed/GlossEmbed.tsx, packages/ndla-ui/src/Embed/InlineTriggerButton.tsx
=> feat!: make InlineTriggerButton generic. Move styling to ConceptInlineTriggerButton

packages/ndla-tracker/src/MatomoTracker.tsx
Noe Guttorm ville prøve
https://matomo.org/faq/how-to/faq_33087/
=> feat: enable SendBeacon

packages/ndla-video-search/src/VideoResultList.tsx, packages/primitives/src/Spinner.tsx
Tok litt inspirasjon fra gamle spinner og setter `marginInline` til `auto`. Vil nok hjelpe en del steder!
=> fix: automatically center spinner

packages/primitives/src/NdlaLogo.tsx
Trengs for å skjule logo fra skjermlesere
=> Adding alt-prop to logo

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
trenger dette for å løse https://github.com/NDLANO/Issues/issues/4218
=> add new footer translation

packages/primitives/src/Layout/PageContainer.tsx, packages/primitives/src/index.ts
Hentet rett ut fra ndla-frontend. Tenker den kan gjenbrukes i ED.
=> feat: add PageContainer

packages/ndla-image-search/src/ImageSearch.tsx
Ikke nødvendig i NDLA-frontend
=> Set onError as condtional

packages/ndla-ui/src/Article/ArticleByline.tsx
Her har vi ikke fulgt våre egne eksempler!
=> fix: use valid html in byline accordion

packages/primitives/src/RadioGroup.tsx
=> fix: Do not render RadioGroupLabel as label. It should be a div

packages/primitives/src/Table.tsx
Lat løsning, men ikke kjempeproblematisk.
=> fix: make tables tabbable, since they can overflow

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
=> Add trait texts

packages/ndla-ui/src/Embed/RelatedContentEmbed.tsx
Vi bruker ikkje lenger path fra node i ndla-frontend.
=> Use url from node rather than path

packages/ndla-ui/src/Embed/AudioEmbed.tsx, packages/ndla-ui/src/Embed/IframeEmbed.tsx, packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx, packages/ndla-ui/src/RelatedArticleList/RelatedArticleList.tsx, packages/primitives/src/Table.tsx
fixes https://github.com/NDLANO/Issues/issues/4255
Tror dette skal være alle det gjelder for!
=> Fix block embeds positioning with float elements

packages/ndla-ui/src/Embed/BrightcoveEmbed.stories.tsx, packages/types-embed/src/brightcoveTypes.ts
https://github.com/NDLANO/Issues/issues/4264
Legger til henting av link url for origin.
=> Link url to be used as origin.

packages/ndla-ui/src/Embed/GlossEmbed.tsx
Disse hadde falt ut ved en omskriving
=> Set exampleIds and exampleLangs on gloss

packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx
=> Remove PopoverTitle from disclaimer

package.json, yarn.lock
=> Add vercel to dev deps

packages/ndla-ui/src/Embed/UuDisclaimerEmbed.tsx
Greit at denne ikke kan vokse så stor den vil, tilsvarende styling som for forklaringer!
=> Update PopoverContent disclaimer styling

packages/ndla-ui/src/Article/ArticleByline.tsx
Gir mulighet til å ikke ha timestamp i timeline
=> Only show last updated if we have updated date

packages/ndla-ui/src/Embed/ExternalEmbed.stories.tsx, packages/ndla-ui/src/Embed/ExternalEmbed.tsx, packages/types-embed/src/externalTypes.ts
Fjerner externalembed variant som vi ikke skal ha
=> Removed externallink variant

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
relatert til https://trello.com/c/QBFwlYTp/1217-oppdatert-min-profil-side
=> Update my profile translations according to new design

packages/primitives/src/ExpandableBox.tsx
https://trello.com/c/qIIXxYcA/1223-h%C3%B8yrestilte-bilder-i-ekspanderende-boks
=> Overflow hidden to expandable box to ensure floated content remains inside

packages/primitives/package.json, packages/primitives/src/Tree/Tree.stories.tsx, packages/primitives/src/Tree/Tree.tsx, packages/primitives/src/index.ts, yarn.lock
Har utsatt dette altfor lenge, fordi Tree-komponenten til Ark har hatt en breaking endring. Har skrevet den om, og ser ut til å fungere enda bedre enn før, mot at vi taper litt fleksibilitet (kanskje ikke?). Kommer en korresponderende PR i ndla-frontend for å fikse tree-pickeren vår.
=> feat: upgrade ark to latest version. Revise Tree component

packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts, packages/ndla-ui/src/locale/messages-sma.ts
Disse kan vel også brukes i ED?
=> chore: add translations for RichTextEditor

packages/editor-components/src/hooks/useListToolbarButton.ts, packages/editor-components/src/hooks/useMarkToolbarButton.ts
Fixes https://github.com/NDLANO/Issues/issues/4289
=> fix: ensure editor has path when asserting active state

packages/primitives/src/ListItem/ListItem.tsx
=> feat: add a neutral variant to ListItem

packages/ndla-image-search/src/ImageSearch.stories.tsx, packages/ndla-image-search/src/ImageSearch.tsx, packages/ndla-image-search/src/ImageSearchResult.tsx
Denne dataen finnes allerede i søkeresultatet!
=> Remove unecessary fetchImage-function + small cleanup

packages/ndla-ui/src/i18n/useComponentTranslations.ts, packages/primitives/src/Button.tsx
Disse dukker opp litt på måfå når man profiler.
=> perf: memoize unstable references

package.json, packages/ndla-scripts/package.json, yarn.lock
Aner ikke om denne går gjennom, men vi prøver!
=> chore: bump vercel

packages/ndla-ui/src/AudioPlayer/Controls.tsx, packages/primitives/package.json, stories/licenseDescriptions.stories.tsx, yarn.lock
PR'en min for å fikse checkboxer er inne, så denne skal være klar!
=> chore: upgrade ark to v5

packages/editor/src/core/createPlugin.ts
Ingen grunn til å utvide disse funksjonene dersom man ikke har sendt inn noe!
=> fix: only set void or inline when provided

packages/ndla-ui/src/Article/ArticleByline.tsx, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts
https://github.com/NDLANO/Issues/issues/4324
Legger til variant for external step i ArticleByline
=> add external learningpath step message to ArticleByline

packages/ndla-ui/src/locale/messages-nn.ts
lagt til i staden for lagd til
=> laeringssti-typo

packages/article-converter/src/plugins/embed/index.ts, packages/article-converter/src/plugins/embed/symbolEmbedPlugin.tsx, packages/types-embed/src/index.ts, packages/types-embed/src/symbolTypes.ts
=> Add symbol plugin

packages/ndla-ui/src/FactBox/FactBox.tsx
Trengs for å få til DND i faktaboks
=> feat: conditionally apply overflow: "hidden" when the factbox is closed

packages/ndla-ui/src/FileList/File.tsx
=> Add query param for filename of downloaded attachments

package.json, packages/article-converter/package.json, packages/ndla-audio-search/package.json, packages/ndla-image-search/package.json, packages/ndla-scripts/package.json, packages/ndla-ui/package.json, packages/ndla-ui/src/Concept/Concept.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.stories.tsx, packages/ndla-ui/src/Embed/ConceptEmbed.tsx, packages/ndla-ui/src/Embed/GlossEmbed.stories.tsx, packages/ndla-ui/src/Gloss/Gloss.stories.tsx, packages/ndla-ui/src/Gloss/Gloss.tsx, packages/types-embed/package.json, yarn.lock
=> Support HTML in Concept title

packages/editor-components/package.json, packages/ndla-ui/package.json, packages/primitives/package.json, yarn.lock
=> chore: bump ark to newest

packages/ndla-licenses/src/index.ts, packages/ndla-licenses/src/licenseRights.ts, packages/ndla-licenses/src/licenses.ts, packages/ndla-licenses/src/types.ts
I all hovedsak bare en omstrukturering av lisens-objektene, men ser ut til å spare litt på det!
=> refactor: reduce licenses size

packages/ndla-licenses/src/__tests__/contributorTypes-test.ts, packages/ndla-licenses/src/contributorTypes.ts, packages/ndla-ui/src/locale/messages-en.ts, packages/ndla-ui/src/locale/messages-nb.ts, packages/ndla-ui/src/locale/messages-nn.ts, packages/ndla-ui/src/locale/messages-se.ts
=> refactor: contributor types

packages/ndla-licenses/src/licenses.ts
=> fix: use correct link to by-nc-nd

packages/icons/src/Icon.tsx
Hedvig ønsker seg store ikoner
=> feat: add large icon variant

packages/ndla-ui/src/Article/Article.tsx, packages/ndla-ui/src/FileList/File.tsx
=> chore: do not use stack components
